### PR TITLE
Allow kafka group.id to be configured

### PR DESCRIPTION
**Pull request by pdepaepe**
Signed-off-by: Pierre De Paepe <pierre.de-paepe@corp.ovh.com>

## Description

This little patch will allow graylog administrators to define a custom Kafka group_id in related input panel.
To avoid update issue, current group "graylog2" remains the default value.

## Motivation and Context

If you have a big Kafka cluster with multiple graylog clusters subscribed on, each time a unhealthy consumer flaps, the rebalancing order is sent to all graylog nodes introducing unecessary stress on log ingestion.
An easy way to avoid it, consists to define for each graylog cluster a specific consumer group name.

## How Has This Been Tested?
In production : ~20 graylog clusters for one kafka.

## Screenshots (if appropriate):

group id

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x ] My code follows the code style of this project.
- [x ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by pbr0ck3r** [comment]
@pdepaepe Awesome work. Can confirm this is a much needed change! Fixes GL constantly re-balancing because GL is originally only using 1 consumer for all kafka inputs.

**Comment by bernd** [comment]
@pdepaepe Thank you for the PR and sorry for the very late response!

Could you quickly edit the PR and let it point to `Graylog2:master` instead of `Graylog2:2.4`? That would be great! That allows us to merge it directly into the master branch.

**Comment by pdepaepe** [comment]
Hum... i guess i should close this PR, starts from a recent master branch and attempt to add a new one?

**Comment by bernd** [comment]
> Hum... i guess i should close this PR, starts from a recent master branch and attempt to add a new one?

Heh, I guess that's easier, yes. :smiley: Thank you!

**Pull request closed without merging**
