### PR TITLE
Allowing non-admin users to create dashboards.

### PR DESCRIPTION
**Pull request by dennisoelkers**
## Motivation and Context
Before this change,  non-admin users possessing the `dashboards:create` permission were able to create new dashboards, but were never able to access them if they do not have the global `dashboards:read` permission (which is not desired in many cases, because it allows users to access _all_ dashboards).

With this change, users creating a dashboard which lack the permission to read/edit that dashboard get the required permissions assigned dynamically. Upon dashboard deletion the user list is traversed and permissions for this specific dashboard are revoked.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by bernd** [comment]
@dennisoelkers I am getting the following error when navigating to the dashboards page.

```
TypeError: this.state.dashboards is undefined
Stack trace:
render@webpack:///./src/components/dashboard/DashboardListPage.jsx?:79:9
_renderValidatedComponentWithoutOwnerOrContext/renderedElement<@http://localhost:8080/vendor.js:28541:16
measureLifeCyclePerf@http://localhost:8080/vendor.js:27821:12
_renderValidatedComponentWithoutOwnerOrContext@http://localhost:8080/vendor.js:28540:25
_renderValidatedComponent@http://localhost:8080/vendor.js:28567:27
performInitialMount@http://localhost:8080/vendor.js:28107:25
mountComponent@http://localhost:8080/vendor.js:28003:16
mountComponent@http://localhost:8080/vendor.js:7008:18
performInitialMount@http://localhost:8080/vendor.js:28116:18
mountComponent@http://localhost:8080/vendor.js:28003:16
mountComponent@http://localhost:8080/vendor.js:7008:18
performInitialMount@http://localhost:8080/vendor.js:28116:18
mountComponent@http://localhost:8080/vendor.js:28003:16
mountComponent@http://localhost:8080/vendor.js:7008:18
_updateRenderedComponent@http://localhost:8080/vendor.js:28510:24
_performComponentUpdate@http://localhost:8080/vendor.js:28469:5
updateComponent@http://localhost:8080/vendor.js:28390:7
performUpdateIfNecessary@http://localhost:8080/vendor.js:28306:7
performUpdateIfNecessary@http://localhost:8080/vendor.js:7119:5
runBatchedUpdates@http://localhost:8080/vendor.js:5730:5
perform@http://localhost:8080/vendor.js:8787:13
perform@http://localhost:8080/vendor.js:8787:13
perform@http://localhost:8080/vendor.js:5669:12
flushBatchedUpdates@http://localhost:8080/vendor.js:5752:7
closeAll@http://localhost:8080/vendor.js:8853:11
perform@http://localhost:8080/vendor.js:8800:11
batchedUpdates@http://localhost:8080/vendor.js:31760:14
enqueueUpdate@http://localhost:8080/vendor.js:5780:5
enqueueUpdate@http://localhost:8080/vendor.js:10103:3
enqueueSetState@http://localhost:8080/vendor.js:10297:5
__vendor</</ReactComponent.prototype.setState@http://localhost:8080/vendor.js:68980:3
module.exports/desc.componentDidMount/<@webpack:///./node_modules/react-proxy-loader/mixinReactProxy.js?:20:6
loadComponent/<@webpack:///./src/pages/DashboardsPage.jsx?:8:18
run@webpack:///./node_modules/core-js/modules/es6.promise.js?:66:22
notify/<@webpack:///./node_modules/core-js/modules/es6.promise.js?:79:30
```

**Comment by dennisoelkers** [comment]
I cannot reproduce the problem. Did you restart the `webpack-dev-server` process before trying it? It is necessary when just switching branches, because it keeps a stale reference to `DashboardsStore.ts`, which was deleted.

**Comment by bernd** [comment]
@dennisoelkers Yep, I restarted the dev server and also removed all node modules and installed them again. I also tested with an artifact build and got a different issue. (tested it twice)

image

**Comment by bernd** [comment]
I am also getting the following when loading a page. (even on the login page)

image

**Comment by bernd** [comment]
And on another machine I get the following with a production build. Something is wrong... :confused: 

image

**Comment by bernd** [comment]
@dennisoelkers I am getting the following error when navigating to "System/Authentication/Roles":

```
Invariant Violation: mergeIntoWithNoDuplicateKeys(): Tried to merge two objects with the same key: `dashboards`. This conflict may be due to a mixin; in particular, this may be caused by two getInitialState() or getDefaultProps() methods returning objects with clashing keys.
Stack trace:
invariant@http://localhost:8080/vendor.js:39546:15
mergeIntoWithNoDuplicateKeys@http://localhost:8080/vendor.js:69331:9
mergedResult@http://localhost:8080/vendor.js:69365:7
createClass/Constructor<@http://localhost:8080/vendor.js:69553:49
_constructComponentWithoutOwner/<@http://localhost:8080/vendor.js:27875:18
measureLifeCyclePerf@http://localhost:8080/vendor.js:27656:12
_constructComponentWithoutOwner@http://localhost:8080/vendor.js:27874:16
_constructComponent@http://localhost:8080/vendor.js:27865:14
mountComponent@http://localhost:8080/vendor.js:27768:16
mountComponent@http://localhost:8080/vendor.js:6985:18
mountChildren@http://localhost:8080/vendor.js:32283:28
_createInitialChildren@http://localhost:8080/vendor.js:29303:27
mountComponent@http://localhost:8080/vendor.js:29122:7
mountComponent@http://localhost:8080/vendor.js:6985:18
performInitialMount@http://localhost:8080/vendor.js:27951:18
mountComponent@http://localhost:8080/vendor.js:27838:16
mountComponent@http://localhost:8080/vendor.js:6985:18
mountChildren@http://localhost:8080/vendor.js:32283:28
_createInitialChildren@http://localhost:8080/vendor.js:29303:27
mountComponent@http://localhost:8080/vendor.js:29122:7
mountComponent@http://localhost:8080/vendor.js:6985:18
performInitialMount@http://localhost:8080/vendor.js:27951:18
mountComponent@http://localhost:8080/vendor.js:27838:16
mountComponent@http://localhost:8080/vendor.js:6985:18
performInitialMount@http://localhost:8080/vendor.js:27951:18
mountComponent@http://localhost:8080/vendor.js:27838:16
mountComponent@http://localhost:8080/vendor.js:6985:18
performInitialMount@http://localhost:8080/vendor.js:27951:18
mountComponent@http://localhost:8080/vendor.js:27838:16
mountComponent@http://localhost:8080/vendor.js:6985:18
_updateRenderedComponent@http://localhost:8080/vendor.js:28345:24
_performComponentUpdate@http://localhost:8080/vendor.js:28304:5
updateComponent@http://localhost:8080/vendor.js:28225:7
performUpdateIfNecessary@http://localhost:8080/vendor.js:28141:7
performUpdateIfNecessary@http://localhost:8080/vendor.js:7096:5
runBatchedUpdates@http://localhost:8080/vendor.js:5716:5
perform@http://localhost:8080/vendor.js:8748:13
perform@http://localhost:8080/vendor.js:8748:13
perform@http://localhost:8080/vendor.js:5655:12
flushBatchedUpdates@http://localhost:8080/vendor.js:5738:7
closeAll@http://localhost:8080/vendor.js:8814:11
perform@http://localhost:8080/vendor.js:8761:11
batchedUpdates@http://localhost:8080/vendor.js:31565:14
enqueueUpdate@http://localhost:8080/vendor.js:5766:5
enqueueUpdate@http://localhost:8080/vendor.js:10042:3
enqueueSetState@http://localhost:8080/vendor.js:10236:5
__vendor</</ReactComponent.prototype.setState@http://localhost:8080/vendor.js:68668:3
module.exports/desc.componentDidMount/<@webpack:///./node_modules/react-proxy-loader/mixinReactProxy.js?:20:6
loadComponent/<@webpack:///./src/pages/RolesPage.jsx?:8:18
run@webpack:///./node_modules/core-js/modules/es6.promise.js?:66:22
notify/<@webpack:///./node_modules/core-js/modules/es6.promise.js?:79:30
flush@webpack:///./node_modules/core-js/modules/_microtask.js?:18:9
```

**Comment by dennisoelkers** [comment]
Thanks! Addressed that in f06eff9.

**Pull request merged**
