### PR TITLE
Limit user details to self and admins in API

### LINKED ISSUE #5068: user detail leak via api request
## Expected Behavior
Only Administrative Users should be able to retreive the user Information of other users from the API.

## Current Behavior
When the username is known (or guessed) every user can get details about every user.

```
# http -a hulle GET https://nuci3.local.lan/graylog/api/users/Nobody
http: password for hulle@nuci3.local.lan:
HTTP/1.1 200 OK

{
    "client_address": null,
    "email": "imnobody@graylog.com",
    "external": false,
    "full_name": "I. M. Nobody",
    "id": "5af475b28c4d850001c17cb2",
    "last_activity": null,
    "permissions": [],
    "preferences": {
        "enableSmartSearch": true,
        "updateUnfocussed": false
    },
    "read_only": false,
    "roles": [
        "Reader",
        "Default - No Access"
    ],
    "session_active": false,
    "session_timeout_ms": 300000,
    "startpage": null,
    "timezone": "America/Chicago",
    "username": "Nobody"
}
```

## Possible Solution
Make the user details only available for the user themself and the Admin.

## Context
When running with multiple Users that are not known to each other on the same Graylog Setup, every User would be able to retreive Information about other users. Including what they can access. 

This is worse from a company perspective revealing their customer details to other customers, but in addition this could be used as initial informations for further attacks against Graylog.

## Your Environment
* Graylog Version: 2.4.5

### PR DESCRIPTION
**Pull request by radykal-com**
## Description
Prevent user details data leak by restricting user details endpoints to the user itself and the administrators

## Motivation and Context
Fixes #5068 

## How Has This Been Tested?
Using an administrator credentials query any user endpoint /api/users/{username} and get the user details back.
Using a regular user query any other user (included admins) endpoints and get a forbidden error.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by bernd** [comment]
@radykal-com Thank you for the PR! We will look at this soon!

**Comment by bernd** [comment]
@radykal-com Thank you for the PR, it looks good!

Can you please sign the CLA so I can merge the PR? Thank you!

**Comment by radykal-com** [comment]
Hello,

I just signed it.

Regards,

**Comment by bernd** [comment]
> Hello,
> 
> I just signed it.
> 
> Regards,

Thank you!

**Comment by bernd** [comment]
@radykal-com Hmm, are you sure that you signed it using this link? https://cla-assistant.io/Graylog2/graylog2-server?pullRequest=5079

The status is still yellow. :confused:

**Comment by radykal-com** [comment]
Yes, I see. I already had it signed from time ago. I signed it again just when you asked for it and trying again showed this:
You have signed the CLA for Graylog2/graylog2-server

**Comment by bernd** [comment]
@radykal-com Aye, this seems to be a bug. I can see you on the list of users who signed the CLA. Sorry for the trouble. I will merge your PR. Thank you very much!

**Comment by radykal-com** [comment]
You are welcome

**Pull request merged**
