### PR TITLE
Update Kafka client to 2.7.0

### LINKED ISSUE #7101: Not rebalancer consumer from kafka
## Expected Behavior
We have on `topic with 3 partitions` in `kafka cluster` and my `graylog cluster is 3 node`. I create Raw/Plaintext Kafka with `Global` (all graylog cluster node) when I start input, only `two node` graylog start consume from kafka! but I know according to Kafka’s architecture, every node must be assign a partition and consume has to be balanced, but that doesn’t happen.
## Current Behavior
when `Processor threads` with `1` balance is established, but if set `Processor threads > 1` balance is not established
## Steps to Reproduce (for bugs)
1. https://aws1.discourse-cdn.com/business6/uploads/graylog/original/2X/b/b5bbfcdbabbf55bcbe989f43cae85012f3cbc8ee.png
2.https://aws1.discourse-cdn.com/business6/uploads/graylog/original/2X/5/56fadf0362a92f5ad38eb8d30c3a7e979ae77bb8.png
3.https://aws1.discourse-cdn.com/business6/uploads/graylog/original/2X/0/0c46175033abcc146b8c44365ae9d46070b574ae.png
4.https://aws1.discourse-cdn.com/business6/uploads/graylog/original/2X/c/cade49d612b7faf4b0899cfbcfb2a905ac7104b1.png

## Your Environment
* Graylog Version:  ` v3.1.3+cda805f`
* Kafka Version: `2.3.1`
* Zookeeper Version: `3.5.6`
* Elasticsearch Version: `6.8.3`
* MongoDB Version: `4.0.12`
* Operating System: `CentOS Linux release 7.7.1908`
* Browser version: `chrome 79.0.3945.88`

### LINKED ISSUE #7783: Kafka input sasl+ssl
## Expected Behavior
setting sasl+ssl parameters and connecting to kafka sasl+ssl listener

## Current Behavior
it is failing withCaused by: org.apache.kafka.common.KafkaException: java.lang.IllegalArgumentException: You must pass java.security.auth.login.config in secure mode.

exception although sasl.jaas.config is supplied in config

## Steps to Reproduce (for bugs)

1. login to graylog
2. choose kafka raw input
3. set properties and add custom properties:
```
custom_properties:
 "ssl.truststore.location=/etc/ssl/jsse/client.truststore.jks
ssl.truststore.password=xxxxx
sasl.enabled.mechanisms=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='xxxx' password='xxxxf';
security.protocol=SASL_SSL
sasl.mechanism=PLAIN"
```
## Context
trying to make sasl_ssl encrypted authenticated connection

## Your Environment
using official docker-compose from documentation

* Graylog Version: 3.2/3.0
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

i don't see any custom sasl properties, only kerberos, which i didn't set..., looks like ignoring sasl properties? in log output...

see:

```graylog_1        | 2020-03-30 13:48:13,337 INFO : org.graylog2.inputs.InputStateListener - Input [Raw/Plaintext Kafka/5e81f89cefe6c600149a6a4a] is now STARTING
graylog_1        | 2020-03-30 13:48:13,353 INFO : org.apache.kafka.clients.consumer.ConsumerConfig - ConsumerConfig values: 
graylog_1        |      metric.reporters = []
graylog_1        |      metadata.max.age.ms = 300000
graylog_1        |      value.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
graylog_1        |      group.id = graylog2-loc
graylog_1        |      partition.assignment.strategy = [org.apache.kafka.clients.consumer.RangeAssignor]
graylog_1        |      reconnect.backoff.ms = 50
graylog_1        |      sasl.kerberos.ticket.renew.window.factor = 0.8
graylog_1        |      max.partition.fetch.bytes = 1048576
graylog_1        |      bootstrap.servers = [kafka-stage-schrzagt1.mb.security.in.pan-net.eu:9094]
graylog_1        |      retry.backoff.ms = 100
graylog_1        |      sasl.kerberos.kinit.cmd = /usr/bin/kinit
graylog_1        |      sasl.kerberos.service.name = null
graylog_1        |      sasl.kerberos.ticket.renew.jitter = 0.05
graylog_1        |      ssl.keystore.type = JKS
graylog_1        |      ssl.trustmanager.algorithm = PKIX
graylog_1        |      enable.auto.commit = true
graylog_1        |      ssl.key.password = null
graylog_1        |      fetch.max.wait.ms = 100
graylog_1        |      sasl.kerberos.min.time.before.relogin = 60000
graylog_1        |      connections.max.idle.ms = 540000
graylog_1        |      ssl.truststore.password = [hidden]
graylog_1        |      session.timeout.ms = 30000
graylog_1        |      metrics.num.samples = 2
graylog_1        |      client.id = 
graylog_1        |      ssl.endpoint.identification.algorithm = null
graylog_1        |      key.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
graylog_1        |      ssl.protocol = TLS
graylog_1        |      check.crcs = true
graylog_1        |      request.timeout.ms = 40000
graylog_1        |      ssl.provider = null
graylog_1        |      ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
graylog_1        |      ssl.keystore.location = null
graylog_1        |      heartbeat.interval.ms = 3000
graylog_1        |      auto.commit.interval.ms = 1000
graylog_1        |      receive.buffer.bytes = 32768
graylog_1        |      ssl.cipher.suites = null
graylog_1        |      ssl.truststore.type = JKS
graylog_1        |      security.protocol = SASL_SSL
graylog_1        |      ssl.truststore.location = /etc/ssl/jsse/client.truststore.jks
graylog_1        |      ssl.keystore.password = null
graylog_1        |      ssl.keymanager.algorithm = SunX509
graylog_1        |      metrics.sample.window.ms = 30000
graylog_1        |      fetch.min.bytes = 5
graylog_1        |      send.buffer.bytes = 131072
graylog_1        |      auto.offset.reset = latest
graylog_1        | 2020-03-30 13:48:13,573 ERROR: org.graylog2.shared.inputs.InputLauncher - The [org.graylog2.inputs.raw.kafka.RawKafkaInput] input with ID <5e81f89cefe6c600149a6a4a> misfired. Reason: You must pass java.security.auth.lo
gin.config in secure mode.
graylog_1        | org.graylog2.plugin.inputs.MisfireException: org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
graylog_1        |      at org.graylog2.plugin.inputs.MessageInput.launch(MessageInput.java:158) ~[graylog.jar:?]
graylog_1        |      at org.graylog2.shared.inputs.InputLauncher$1.run(InputLauncher.java:84) [graylog.jar:?]
graylog_1        |      at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:181) [graylog.jar:?]
graylog_1        |      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
graylog_1        |      at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
graylog_1        |      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
graylog_1        |      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
graylog_1        |      at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
graylog_1        | Caused by: org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
graylog_1        |      at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:648) ~[graylog.jar:?]
graylog_1        |      at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:542) ~[graylog.jar:?]
graylog_1        |      at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:524) ~[graylog.jar:?]
graylog_1        |      at org.graylog2.inputs.transports.KafkaTransport$ConsumerRunnable.<init>(KafkaTransport.java:262) ~[graylog.jar:?]
graylog_1        |      at org.graylog2.inputs.transports.KafkaTransport.lambda$doLaunchConsumer$2(KafkaTransport.java:249) ~[graylog.jar:?]
graylog_1        |      at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110) ~[?:1.8.0_242]
graylog_1        |      at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:581) ~[?:1.8.0_242]
graylog_1        |      at org.graylog2.inputs.transports.KafkaTransport.doLaunchConsumer(KafkaTransport.java:249) ~[graylog.jar:?]
graylog_1        |      at org.graylog2.inputs.transports.KafkaTransport.doLaunch(KafkaTransport.java:219) ~[graylog.jar:?]
graylog_1        |      at org.graylog2.plugin.inputs.transports.ThrottleableTransport.launch(ThrottleableTransport.java:76) ~[graylog.jar:?]
graylog_1        |      at org.graylog2.plugin.inputs.MessageInput.launch(MessageInput.java:155) ~[graylog.jar:?]
graylog_1        |      ... 7 more
graylog_1        | Caused by: org.apache.kafka.common.KafkaException: java.lang.IllegalArgumentException: You must pass java.security.auth.login.config in secure mode.
graylog_1        |      at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:74) ~[graylog.jar:?]
graylog_1        |      at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:60) ~[graylog.jar:?]
graylog_1        |      at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:79) ~[graylog.jar:?]
graylog_1        |      at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:577) ~[graylog.jar:?]
graylog_1        |      at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:542) ~[graylog.jar:?]
graylog_1        |      at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:524) ~[graylog.jar:?]
graylog_1        |      at org.graylog2.inputs.transports.KafkaTransport$ConsumerRunnable.<init>(KafkaTransport.java:262) ~[graylog.jar:?]
graylog_1        |      at org.graylog2.inputs.transports.KafkaTransport.lambda$doLaunchConsumer$2(KafkaTransport.java:249) ~[graylog.jar:?]
graylog_1        |      at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110) ~[?:1.8.0_242]
graylog_1        |      at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:581) ~[?:1.8.0_242]
graylog_1        |      at org.graylog2.inputs.transports.KafkaTransport.doLaunchConsumer(KafkaTransport.java:249) ~[graylog.jar:?]
graylog_1        |      at org.graylog2.inputs.transports.KafkaTransport.doLaunch(KafkaTransport.java:219) ~[graylog.jar:?]
graylog_1        |      at org.graylog2.plugin.inputs.transports.ThrottleableTransport.launch(ThrottleableTransport.java:76) ~[graylog.jar:?]
graylog_1        |      at org.graylog2.plugin.inputs.MessageInput.launch(MessageInput.java:155) ~[graylog.jar:?]
graylog_1        |      ... 7 more
graylog_1        | Caused by: java.lang.IllegalArgumentException: You must pass java.security.auth.login.config in secure mode.
graylog_1        |      at org.apache.kafka.common.security.kerberos.Login.login(Login.java:289) ~[graylog.jar:?]
graylog_1        |      at org.apache.kafka.common.security.kerberos.Login.<init>(Login.java:104) ~[graylog.jar:?]
graylog_1        |      at org.apache.kafka.common.security.kerberos.LoginManager.<init>(LoginManager.java:44) ~[graylog.jar:?]
graylog_1        |      at org.apache.kafka.common.security.kerberos.LoginManager.acquireLoginManager(LoginManager.java:85) ~[graylog.jar:?]
graylog_1        |      at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:55) ~[graylog.jar:?]
graylog_1        |      at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:60) ~[graylog.jar:?]
graylog_1        |      at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:79) ~[graylog.jar:?]
graylog_1        |      at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:577) ~[graylog.jar:?]
graylog_1        |      at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:542) ~[graylog.jar:?]
graylog_1        |      at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:524) ~[graylog.jar:?]
graylog_1        |      at org.graylog2.inputs.transports.KafkaTransport$ConsumerRunnable.<init>(KafkaTransport.java:262) ~[graylog.jar:?]
graylog_1        |      at org.graylog2.inputs.transports.KafkaTransport.lambda$doLaunchConsumer$2(KafkaTransport.java:249) ~[graylog.jar:?]
graylog_1        |      at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110) ~[?:1.8.0_242]
graylog_1        |      at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:581) ~[?:1.8.0_242]
graylog_1        |      at org.graylog2.inputs.transports.KafkaTransport.doLaunchConsumer(KafkaTransport.java:249) ~[graylog.jar:?]
graylog_1        |      at org.graylog2.inputs.transports.KafkaTransport.doLaunch(KafkaTransport.java:219) ~[graylog.jar:?]
graylog_1        |      at org.graylog2.plugin.inputs.transports.ThrottleableTransport.launch(ThrottleableTransport.java:76) ~[graylog.jar:?]

```

### LINKED ISSUE #9927: GELF Kafka Input - New consumer API (non-legacy) mode
## Expected Behavior
Kafka logs should get fetched without any errors.

## Current Behavior
Graylog log is continuously full of these errors:-
2021-01-18T22:54:15.192Z ERROR [KafkaTransport] WakeupException in poll. Kafka server is not responding.
2021-01-18T22:54:15.192Z ERROR [KafkaTransport] Caught recoverable exception. Retrying

## Context
I switched from the legacy mode (connection to zookeeper)

## Your Environment
cluster of 6 kafka servers (kafka-2.7.0-1)
centos 7

* Graylog Version: graylog-server-4.0.1-1
* Java Version: java-1.8.0
* Elasticsearch Version:  elasticsearch-oss-7.10.1-1
* MongoDB Version: mongodb-org-4.0.20-1
* Operating System: Centos 7

### PR DESCRIPTION
**Pull request by mpfz0r**
Using a shaded dependency of the old Kafka 0.9 client, allows us to update to a current Kafka version,
without breaking backwards compatibility on our on-disk Kafka journal.
The disk-journal and the Kafka legacy input keeps on using the old library.

## Motivation and Context
The old client has several bugs.
It is known to hang on high loads and shows problems when partitions are re-balanced.

## How Has This Been Tested?
Tested against multiple Kafka versions: `2.7.0`, `2.4.0`, `0.10.2.2` (the latter also with legacy mode)

I've extended partitions for a topic:
`bash-4.4# kafka-topics.sh  --topic=rsyslog --bootstrap-server=localhost:9092 --alter --partitions=5`

They get rebalanced just fine:
```
# kafka-consumer-groups.sh --bootstrap-server=localhost:9092 --group=graylog2 --describe

GROUP           TOPIC           PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                                                  HOST            CLIENT-ID
graylog2        rsyslog         0          3578            3578            0               gl2-cbb04ecf-6033da3e16d6d5739ecd5785-0-9f6b4529-3719-42ce-baaf-852021e9acc5 /172.16.1.1     gl2-cbb04ecf-6033da3e16d6d5739ecd5785-0
graylog2        rsyslog         1          0               0               0               gl2-cbb04ecf-6033da3e16d6d5739ecd5785-0-9f6b4529-3719-42ce-baaf-852021e9acc5 /172.16.1.1     gl2-cbb04ecf-6033da3e16d6d5739ecd5785-0
graylog2        rsyslog         2          0               0               0               gl2-cbb04ecf-6033da3e16d6d5739ecd5785-1-b67e6d4b-4742-4e5b-af14-b6c8c2afbe4a /172.16.1.1     gl2-cbb04ecf-6033da3e16d6d5739ecd5785-1
graylog2        rsyslog         3          0               0               0               gl2-cbb04ecf-6033da3e16d6d5739ecd5785-1-b67e6d4b-4742-4e5b-af14-b6c8c2afbe4a /172.16.1.1     gl2-cbb04ecf-6033da3e16d6d5739ecd5785-1
graylog2        rsyslog         4          0               0               0               gl2-cbb04ecf-6033da3e16d6d5739ecd5785-2-dbd2a9cc-9d31-4aec-bdd9-c62987375e47 /172.16.1.1     gl2-cbb04ecf-6033da3e16d6d5739ecd5785-2
```

## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)

Fixes #7101 
Fixes #7783  (tested with SASL_PLAIN and SCRAM-SHA-512)
Fixes #9927

### CODE REVIEW

**Comment by jpdstan** [comment]
Thanks so much for this!! Happy to smoke test this in our development environment -- will get back to you within the week.

**Comment by jpdstan** [comment]
i'm unable to package the jar locally
```
java: Errors occurred while compiling module 'graylog2-server'
...
java: package org.graylog.shaded.kafka09.common does not exist
```
could you package this and upload it as a github release?

**Comment by mpfz0r** [comment]
@jpdstan that artifact should be on maven central: 
https://search.maven.org/artifact/org.graylog.shaded/kafka09_2.11/0.9.0.1-5/jar

I'm about to push an update to that PR. So bear with me.

**Comment by jpdstan** [comment]
hey @mpfz0r i'm still having trouble building the jar locally, getting some strange yarn errors now, perhaps i'm using the wrong version (1.22.4). would you mind just packaging the release for me?

**Comment by mpfz0r** [comment]
@jpdstan  https://graylog2public.s3.amazonaws.com/mpf/graylog-4.1.0-SNAPSHOT-20210225160210.tgz

**Comment by yangzaizi** [comment]
@jpdstan 

Would you mind also test this scenario to see if the consumer rejoins the after broker restart? 

Essentially leave your graylog kafka input running, brings down you kakfa brokers. 

Restart your kafka brokers, put some messages into the topic, and see if the graylog input can consume those messages.

From my current testing of Graylog kafka input, I need to restart my Graylog input in order to pick up message again.

I am using Graylog 4.0.2.

Thanks.

**Comment by mpfz0r** [comment]
@yangzaizi That seems to work with the new client. (But I've never had this issue with the old one either, so...)

**Comment by jpdstan** [comment]
Been running this all weekend with the following parameters:
- 10-20 consumers and 1-5 threads
- manual consumer + broker restarts (cc @yangzaizi )
- 20+ topics and 1000+ partitions
- 2 kafka clusters in parallel (one with 15 brokers, the other with 159 brokers)

....and so far so good! Every time i've checked the consumer groups have been in a Stable state, no more "permanently stuck rebalancing" anymore. Will let you know if anything changes. Thanks so much for your work on this @mpfz0r !!!

**Comment by mpfz0r** [comment]
Thanks for testing @jpdstan Much appreciated!

**Comment by bernd** [comment]
I deployed this to my setup and didn't see any problems. :+1:

**Review by thll — APPROVED** [review]
LGTM and works 👍

**Pull request merged**
