### PR TITLE
DWH destination UI improvement

### PR DESCRIPTION
**Pull request by ousmaneo**
/nocl
/jpd  Graylog2/graylog-plugin-enterprise#8174
fix [#7823](https://github.com/Graylog2/graylog-plugin-enterprise/issues/7823)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by grotlue — CHANGES_REQUESTED** [review]
Code-wise it looks good, just a few nitpicks.

I will still need to test it.

**Review by grotlue — CHANGES_REQUESTED** [review]
Thanks for the code changes!

I also tested it and it looks very nice!

I found some minor issues:
- Dark mode:
  - "Archiving" icon button color makes it barely visible
- Data Warehouse disabled tooltip does not disappear after clicking anywhere else on the page
- Segmented Tabs -> Line height looks off, too much space at the bottom
- Back Button -> Line height looks off, too much space at the bottom
- Enabled label  -> Line height looks off, too much space at the bottom
- Retrieve from Data warehouse dialog: Input height does not match button height next to it

Screenshot 2024-08-13 at 15 29 27
Screenshot 2024-08-13 at 15 39 49
Screenshot 2024-08-13 at 15 41 24

**Comment by ousmaneo** [comment]
Thank you for the review.
The Items below relate to how we use Icon with our button component. I will create an issue so we can fix it globally for all the projects

> - Back Button -> Line height looks off, too much space at the bottom
> - Enabled label  -> Line height looks off, too much space at the bottom

For Calendar input, we have another issue in the cycle to work on the retrieval form. This fix will be included there.

> - Retrieve from Data warehouse dialog: Input height does not match button height next to it

**Review by kodjo-anipah — APPROVED** [review]
LGTM, for the other comments wie have tickets created

**Pull request merged**
