### PR TITLE
Implement {GELF,Raw,Syslog} Kafka inputs

### LINKED ISSUE #322: Let Kafka input support raw, syslog and GELF
Right now it's only accepting our own graylog2-radio MessagePack format.

### PR DESCRIPTION
**Pull request by joschi**
This PR adds Kafka-based inputs for GELF, Syslog, and Raw/Plaintext.

Closes #322

### CODE REVIEW

**Comment by bernd** [comment]
I will test it.

**Comment by bernd** [comment]
Looks like the Syslog codec does not work that well with the Kafka input.

This is a test with rsyslog 8.10.

38kdcjobv80aaaaasuvork5cyii

**Comment by bernd** [comment]
The problem is that the default template is not really syslog that can be parsed by our SyslogCodec.

A template can be used to fix that. This should probably go into our documentation.

Example rsyslog that works with the SyslogKafka input.

```
module(load="omkafka")

template(name="syslog-rfc5424"
         type="string"
         string="<%PRI%>%PROTOCOL-VERSION% %TIMESTAMP:::date-rfc3339% %HOSTNAME% %APP-NAME% %PROCID% %MSGID% %STRUCTURED-DATA% %msg%\n")

*.* action(type="omkafka"
           broker=["10.0.2.2:9092"]
           topic="graylog-syslog"
           template="syslog-rfc5424")
```

**Comment by joschi** [comment]
@bernd Thanks for trying that out! Could you please check if the predefined `RSYSLOG_SyslogProtocol23Format` (http://www.rsyslog.com/doc/master/configuration/templates.html#reserved-template-names) also works? It should be identical to the custom template you've created.

**Comment by bernd** [comment]
Yep, `RSYSLOG_SyslogProtocol23Format` works as well.

Working rsyslog config snippet:

```
module(load="omkafka")

*.* action(type="omkafka"
	       broker=["10.0.2.2:9092"]
	       topic="graylog-syslog"
	       template="RSYSLOG_SyslogProtocol23Format")
```

**Comment by bernd** [comment]
The GELF Kafka input works as well.

Tested with rsyslog again:

```
module(load="omkafka")

template(name="gelf" type="list") {
        constant(value="{\"version\":\"1.1\",")
        constant(value="\"host\":\"")
        property(name="hostname")
        constant(value="\",\"short_message\":\"")
        property(name="msg" format="json")
        constant(value="\",\"timestamp\":\"")
        property(name="timegenerated" dateformat="unixtimestamp")
        constant(value="\",\"level\":\"")
        property(name="syslogseverity")
        constant(value="\"}")
}

*.* action(type="omkafka"
	       broker=["10.0.2.2:9092"]
	       topic="graylog-syslog"
	       template="gelf")
```

80gq0zl flt 73c5lsumsw7cu5i4rgiuzta0kiaejseacepcabcqgaqliqaiskiaejbc9gak46k20pqqkiaejseacepcabcqgaqliqaiskiaeyhzqabczmrpiqaiskiaejcabcuhaahkqgaqkiaejscb6aqvw0vtpswliqaiskiaejcabcuhaahkqgaqkiaejxcygac5mmjwqgaqkiaejseacepcabcqgaqliqaisked0agrgorfslhkqg

**Comment by bernd** [comment]
LGTM :+1:

**Pull request merged**
