### PR TITLE
Feature/missing values in pivot via missing aggregation

### PR DESCRIPTION
**Pull request by luk-kaminski**
## Description
Missing values in pivot via missing aggregation have been implemented.
The screenshots show some main examples of the changes it is bringing to the UI.
"(Empty value)" string has been used to represent missing bucket, it can be of course changed if needed.

Some minor changes to the front-end have been implemented in order to support "Add to query" and "Exclude from results" functionality properly, but it is possible that more FE work will still be needed.

Is one of the tasks from this issue : #12611

## Motivation and Context
Currently, our users are not aware of how many documents miss values for certain field, cannot figure out metrics of those documents easily etc.

## How Has This Been Tested?
Integration tests have been added.
It has been tested manually, mainly on dashboards, with different aggregation types.

## Screenshots (if appropriate):
How "top values" are changed:
Screenshot 2022-06-29 at 12-43-44 Graylog - Unsaved Search

How pivot table and different charts are changed:
Screenshot 2022-06-29 at 12-45-20 Graylog - War dashboard

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Review by linuspahl — COMMENTED** [review]
The core functionality works really well!

A few suggestions regarding the frontend (as expected):
- let's create a constant for `(Empty Value)` in the UI as well. E.g. in `views/Constants.ts`
- let's extend the tests for `AddToQueryHandler.ts` and `ExcludeFromQueryHandler.ts`
- it looks like the field value "Highlight this value" is not working probably and we should probably also disable "Insert into view" and "Show documents for value"

**Comment by linuspahl** [comment]
@luk-kaminski and I discussed to take care of 2. and 3. in https://github.com/Graylog2/graylog2-server/pull/12958#pullrequestreview-1024622600 in a follow-up PR.

**Comment by linuspahl** [comment]
@luk-kaminski The tests look good!

**Review by janheise — APPROVED** [review]
LGTM!

**Comment by linuspahl** [comment]
Just a follow-up regarding point 3 the highlighting actually works correctly.

**Pull request merged**
