### PR TITLE
Update bootstrap dependency in package.json

### PR DESCRIPTION
**Pull request by pbr0ck3r**
## Description
Updating bootstrap 3.3.7 to 4.0.0

## Motivation and Context
Versions 3.3.6, 3.3.7 of this package are vulnerable to Cross-Site Scripting (XSS) attacks via the data-target attribute. This was fixed in 4.0.0.

## How Has This Been Tested?
Tested development build of graylog 2.4.3 locally. Navigated around pages, clicked buttons, etc.
Nothing seemed to be broken or display incorrectly.

## Types of changes

- Security Vulnerability

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by joschi** [comment]
> Updating bootstrap 3.3.7 to 4.0.0

You've updated [Bluebird](https://www.npmjs.com/package/bluebird), not Bootstrap in this PR…

**Comment by pbr0ck3r** [comment]
@joschi: my bad. I tested bootstrap 4.0.0 on a local build I had. Then just made the change manually in the file instead of pushing my local development build since I had several other modifications.

**Comment by edmundoa** [comment]
@pbr0ck3r Thank you for your PR.

Could you please add a link to the security issue you mentioned? It would be important even as for reference.

I would also be interested in knowing how you tested the upgrade exactly. Sorry if I sound a bit skeptical, but there are [many changes in Bootstrap v4](https://getbootstrap.com/docs/4.0/migration/) and [react-bootstrap](https://react-bootstrap.github.io) is still targeting Bootstrap 3, so I doubt everything will keep working without any further changes.

**Comment by pbr0ck3r** [comment]
Here is the PR that was made in bootstrap to fix the issue: https://github.com/twbs/bootstrap/issues/20184

Here also is a link to a snyk write up that talks about the CWE and the versions it has been fixed in (3.4.0 and greater then 4.0.0).

As to how I tested things. I compiled the frontend app locally of graylog 2.4.3 and then spent time navigating around and interacting. Such as viewing several pages, interacting with models, etc.

**Comment by edmundoa** [comment]
Thank you for the links!

It looks like both CI systems we use have troubles building the JS bundle after the version bump. Could you please take a look? https://travis-ci.org/Graylog2/graylog2-server/builds/344372627?utm_source=github_status&utm_medium=notification

**Comment by pbr0ck3r** [comment]
@edmundoaI can try updating to 3.4.0 and ensure that things work properly. Then ensure that the CI system works.

**Comment by pbr0ck3r** [comment]
@edmundoa: I will build the graylog jar locally as well to ensure that the CI system will work.

**Comment by pbr0ck3r** [comment]
Just going to move this to a open issue. Until bootstrap 3.4.0 is released. Or react-bootstrap integrates with 4.0.0

**Comment by edmundoa** [comment]
@pbr0ck3r sounds good! Closing the PR until we can safely upgrade to fix the issue.

**Comment by pbr0ck3r** [comment]
Sorry for the premature PR. My bad. Will triple check next time for sure!

**Comment by edmundoa** [comment]
@pbr0ck3r don't worry, next time will be better :)

**Pull request closed without merging**
