### PR TITLE
Use singleton scope to bind some services

### PR DESCRIPTION
**Pull request by thll**
Some services ensure that proper indexes exist in MongoDB in their constructor.

If the services are not bound as singletons, we issue a bunch of unnecessary index create calls e.g. for REST API requests.

Together with https://github.com/Graylog2/graylog-plugin-enterprise/pull/4888 this is the effect:

Before:
image

After:
image

/nocl

### CODE REVIEW

**Review by mpfz0r — COMMENTED** [review]
I think @moesterheld beat you to it

https://github.com/Graylog2/graylog2-server/pull/14965

**Comment by thll** [comment]
> I think @moesterheld beat you to it
> 
> #14965

This is so not fair 😂

**Comment by moesterheld** [comment]
I didn't take care of the DBGrantService

**Comment by thll** [comment]
> I didn't take care of the DBGrantService

Your change results in the same optimized trace, though. I think it's the binding of `UserService` as a singleton which has the biggest effect, so I'm fine with leaving this PR be.

**Pull request closed without merging**
