### PR TITLE
Email Notification Improvements

### LINKED ISSUE #20809: Support CCs in Email Notifications
## What?

Support the ability to add users/teams to the CC line of email notifications.

## Why?

- Better control over the way email notifications are sent
- Better visibility for the recipients over who else received the notification and who is the primary target of the notification

gz#1066

### PR DESCRIPTION
**Pull request by kingzacko1**
## Description

- Adds option to send notification as a single email instead of one per recipient
- Adds option to add users/emails to the email CC line
- Adds option to add users/emails to the email BCC line

## Motivation and Context

- Gives users more control over how email notifications are sent.
- Allows notification recipients to more clearly differentiate intended primary recipients vs secondary  
- Closes #20809 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by kingzacko1** [comment]
Opening as draft to get some initial reviews while looking at how easy adding Teams to the to, cc, and bcc lines might be. If it is a large change I will plan it for a separate PR and open this as ready for review.

**Comment by danotorrey** [comment]
@kingzacko1 Sorry for the delay. I'll review this ASAP.

**Comment by danotorrey** [comment]
@kingzacko1 The code LGTM! Working on testing this out this morning...

**Review by danotorrey — APPROVED** [review]
LGTM and tests successfully!

**Pull request merged**
