### PR TITLE
Empty dir error in datanode inplace migration

### PR DESCRIPTION
**Pull request by todvora**
Empty `opensearch_data_location` should be reported as invalid configuration for the inplace migration. If it's empty and users are trying to migrate, it's most likely an error in configuration, their actual data is somewhere else that they are telling us.

/nocl

## Screenshots (if appropriate):
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by moesterheld — CHANGES_REQUESTED** [review]
I would not stop them from migrating, only warn them. Without remote reindexing, this is currently the only way to switch to data node if you don't care about migrating data

**Comment by todvora** [comment]
@moesterheld added warnings to the compatibility check.

@gally47 could you please extend the frontend implementation, so it displays warning? The current response format looks like this:

```json
{
  "tdvorak-ThinkPad-T14s-Gen-1": {
    "hostname": "tdvorak-ThinkPad-T14s-Gen-1",
    "opensearch_version": "2.15.0",
    "info": {
      "nodes": [],
      "opensearch_data_location": "/home/tdvorak/bin/datanode/data"
    },
    "compatibility_errors": [],
    "compatibility_warnings": [
      "Your configured opensearch_data_location directory /home/tdvorak/bin/datanode/data doesn't contain any indices! Migration can't continue!"
    ]
  }
}
```

**Review by todvora — COMMENTED** [review]
Thanks @gally47, the frontend now works perfectly! Tested locally and everything looks good.

**Review by moesterheld — APPROVED** [review]
Tested and works fine. Backend lgtm, frontend as well.

**Pull request merged**
