### PR TITLE
Correcting usage of PropTypes, switching to new separate package.

### PR DESCRIPTION
**Pull request by dennisoelkers**
## Motivation and Context

PropTypes have moved into a separate package (prop-types), so all
imports and usages of the old way (being part of the React module) are
changed.

For more details see
https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes

This change was fabricated using a codemod
(https://github.com/reactjs/react-codemod/blob/master/transforms/React-PropTypes-to-prop-types.js)
which was executed like this:

`jscodeshift -t transforms/React-PropTypes-to-prop-types.js graylog2-server/graylog2-web-interface/src/**/*.jsx`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by edmundoa** [comment]
Other than the remark above, the changes look good to me.

We also need to do this replacement in all plugins. Should I add issues for that, @dennisoelkers?

**Comment by dennisoelkers** [comment]
Absolutely correct, good catch!

**Comment by dennisoelkers** [comment]
Regarding the changes for the plugins: If you have the time, I would be happy if you could add issues, otherwise I can do it too.

**Comment by edmundoa** [comment]
I added issues in all affected plugins and referenced to this one to get to them easily.

**Pull request merged**
