### PR TITLE
Sync cloud-4.0 branch

### PR DESCRIPTION
**Pull request by thll**
## Description

Merges the current state of `4.0` into `cloud-4.0`.
Also adds some missing license headers.

## Motivation and Context

After the license change to SSPL (see https://github.com/Graylog2/graylog2-server/pull/9504) we need to pull these changes into the `cloud-4.0` branch in order to generate the correct license headers for new files.

/jenkins-pr-deps Graylog2/graylog-plugin-cloud#589

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by edmundoa** [comment]
@thll can you try again with the latest changes in 4.0? As far as I can see we need https://github.com/Graylog2/graylog2-server/pull/9512 to make the test pass again.

**Comment by thll** [comment]
> @thll can you try again with the latest changes in 4.0? As far as I can see we need #9512 to make the test pass again.

@edmundoa done. After the release of `4.0` we now also need Graylog2/graylog-plugin-cloud#589 to get the build passing.

**Comment by thll** [comment]
The build failed due to some license checks failing. I hopefully fixed those in Graylog2/graylog-plugin-cloud#589 so I'm restarting the build.

**Review by edmundoa — APPROVED** [review]
Tested it a little and seems to work fine 👍

**Pull request merged**
