### PR TITLE
Update web dependencies

### PR DESCRIPTION
**Pull request by dennisoelkers**
Updating some web dependencies which are safe to update.

### CODE REVIEW

**Comment by edmundoa** [comment]
I'm getting this error when running in production mode:

```
2017-02-15 17:34:22.731 vendor.js:1Uncaught TypeError: Cannot read property 'call' of undefined
    at t (vendor.js:1)
    at Object.<anonymous> (offset.js from dll-reference __vendor:1)
    at t (bootstrap 69ba2bd…:19)
    at Object.<anonymous> (height.js:8)
    at t (bootstrap 69ba2bd…:19)
    at Object.<anonymous> (Affix.js:15)
    at t (bootstrap 69ba2bd…:19)
    at Object.<anonymous> (index.js:8)
    at t (bootstrap 69ba2bd…:19)
    at Object.<anonymous> (SearchSidebar.jsx:4)
    at t (bootstrap 69ba2bd…:19)
    at Object.<anonymous> (plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.69ba2bd….js:8513)
    at t (bootstrap 69ba2bd…:19)
    at Object.<anonymous> (MessageFields.jsx:3)
    at t (bootstrap 69ba2bd…:19)
    at Object.<anonymous> (MessageDetail.jsx:10)
t @ vendor.js:1
(anonymous) @ offset.js from dll-reference __vendor:1
t @ bootstrap 69ba2bd…:19
(anonymous) @ height.js:8
t @ bootstrap 69ba2bd…:19
(anonymous) @ Affix.js:15
t @ bootstrap 69ba2bd…:19
(anonymous) @ index.js:8
t @ bootstrap 69ba2bd…:19
(anonymous) @ SearchSidebar.jsx:4
t @ bootstrap 69ba2bd…:19
(anonymous) @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.69ba2bd….js:8513
t @ bootstrap 69ba2bd…:19
(anonymous) @ MessageFields.jsx:3
t @ bootstrap 69ba2bd…:19
(anonymous) @ MessageDetail.jsx:10
t @ bootstrap 69ba2bd…:19
(anonymous) @ MessageShow.jsx:4
t @ bootstrap 69ba2bd…:19
(anonymous) @ SimulationResults.jsx:5
t @ bootstrap 69ba2bd…:19
(anonymous) @ ProcessorSimulator.jsx:8
t @ bootstrap 69ba2bd…:19
(anonymous) @ SimulatorPage.jsx:7
t @ bootstrap 69ba2bd…:19
(anonymous) @ index.jsx:8
t @ bootstrap 69ba2bd…:19
(anonymous) @ bootstrap 69ba2bd…:39
(anonymous) @ bootstrap 69ba2bd…:39
2017-02-15 17:34:24.556 vendor.js:1Uncaught TypeError: Cannot read property 'call' of undefined
    at t (vendor.js:1)
    at Object.1352 (isWindow.js from dll-reference __vendor:1)
    at e (bootstrap c883cee…:47)
    at Object.1225 (height.js:12)
    at e (bootstrap c883cee…:47)
    at Object.478 (Affix.js:15)
    at e (bootstrap c883cee…:47)
    at Object.1223 (index.js:8)
    at e (bootstrap c883cee…:47)
    at Object.664 (SearchSidebar.jsx:4)
    at e (bootstrap c883cee…:47)
    at Object.60 (5.5.c883cee….js:799)
    at e (bootstrap c883cee…:47)
    at Object.394 (SearchBar.jsx:9)
    at e (bootstrap c883cee…:47)
    at Object.787 (AppWithSearchBar.jsx:6)
    at e (bootstrap c883cee…:47)
    at Object.786 (AppRouter.jsx:6)
    at e (bootstrap c883cee…:47)
    at Object.758 (LoggedInPage.jsx:2)
    at e (bootstrap c883cee…:47)
    at LoggedInPage.jsx?eb55:7
    at window.webpackJsonp (bootstrap c883cee…:18)
    at 5.5.c883cee….js:1
t @ vendor.js:1
1352 @ isWindow.js from dll-reference __vendor:1
e @ bootstrap c883cee…:47
1225 @ height.js:12
e @ bootstrap c883cee…:47
478 @ Affix.js:15
e @ bootstrap c883cee…:47
1223 @ index.js:8
e @ bootstrap c883cee…:47
664 @ SearchSidebar.jsx:4
e @ bootstrap c883cee…:47
60 @ 5.5.c883cee….js:799
e @ bootstrap c883cee…:47
394 @ SearchBar.jsx:9
e @ bootstrap c883cee…:47
787 @ AppWithSearchBar.jsx:6
e @ bootstrap c883cee…:47
786 @ AppRouter.jsx:6
e @ bootstrap c883cee…:47
758 @ LoggedInPage.jsx:2
e @ bootstrap c883cee…:47
(anonymous) @ LoggedInPage.jsx?eb55:7
window.webpackJsonp @ bootstrap c883cee…:18
(anonymous) @ 5.5.c883cee….js:1
```

I cannot reproduce the issue when using the development setup, though. Can you reproduce the issue?

**Comment by dennisoelkers** [comment]
Will check!

**Comment by dennisoelkers** [comment]
I tried to reproduce it and failed. Did you try doing it with a clean build and browser cache? From the stack trace it looks like the error you were getting came from parts that were not even touched.

**Comment by edmundoa** [comment]
I rebuilt several times and still had the same issue. Clearing the browser cache fixed it. Thank you for checking!

**Pull request merged**
