### PR TITLE
Fix AuditActor test

### PR DESCRIPTION
**Pull request by bernd**
Fixes the test for me locally.

### CODE REVIEW

**Comment by bernd** [comment]
Seems to be a local problem...

**Comment by edmundoa** [comment]
I had the same yesterday a couple of times. It fixed after cleaning and rebuilding, but not sure if there's anything else going on in there.

**Comment by bernd** [comment]
@edmundoa Thanks for the info, I will test that!

**Comment by bernd** [comment]
@edmundoa Yep, after clean and rebuild it works. Strange... :confused:

**Pull request closed without merging**
