### PR TITLE
Remove commented code

### PR DESCRIPTION
**Pull request by kyleknighted**
Previous PR #5748 for this issue had commented code.
This PR removes commented code only.

## Motivation and Context
Remove commented code

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by dennisoelkers** [comment]
@kyleknighted: Unfortunately I was not able to leave a review before #5478 was merged. I noticed that the placement of the logo is now different.

Before:

Screen Shot 2019-03-11 at 11 54 34

After:

Screen Shot 2019-03-11 at 11 55 45

There is now less padding around it, especially on the left side. Is this on purpose?

**Comment by kyleknighted** [comment]
@dennisoelkers It was intentional. I aligned the left side to the other elements on the site and removed some of the padding off to the right that felt superfluous. 

I can gladly make any adjustments if you feel like the logo needs additional "breathing room".

**Comment by dennisoelkers** [comment]
Okay, just wanted to make sure it was intentional and not accidental. I also like the more compact version better.

**Comment by lennartkoopmann** [comment]
The Chief Margin and Padding Officer (CMPO) approves.

**Pull request merged**
