### PR TITLE
feat(MessageList): terminal view

### PR DESCRIPTION
**Pull request by STRML**
Addresses #2479.

Please treat this as a work in progress as I want to gather feedback on the style we're using here. I also would like to persist these state options to localStorage, but I don't see an established pattern. I use/recommend [react-localstorage](https://github.com/STRML/react-localstorage), of course.

## Description
Adds a few buttons to easily modify list style for readability.

There are two main features here:

1. Terminal View, which shows only `date`, `source`, and `message`, and
2. A "Reverse Messages" button. This is different than simply reversing timestamp, which puts the oldest messages in the entire search at the top. I might want the oldest messages *on the current page* at the top in terminal view, so it reads like `tail -f` output.

## Motivation and Context
Modeling this view similarly to a terminal or Papertrail's output.

## How Has This Been Tested?
Has not been tested. New to development on graylog2-web-server core but happy to add tests if you have pointers.

## Screenshots (if appropriate):
screen shot 2018-08-01 at 13 31 18
screen shot 2018-08-01 at 13 31 32
screen shot 2018-08-01 at 13 26 28
screen shot 2018-08-01 at 13 26 33
screen shot 2018-08-01 at 13 26 40
screen shot 2018-08-01 at 13 26 43

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by xiaomaijiang** [comment]
use https://github.com/mxw/vim-jsx to display will be more better 😄

**Comment by postulka** [comment]
Any update on this one? Would love to see this feature in graylog.

**Comment by STRML** [comment]
The web linter build is red but I'm unable to actually check on what the problem is. Otherwise this is good to go.

**Comment by jaRobison** [comment]
Any progress here? I'm looking forward to seeing this in action.

**Comment by zgfh** [comment]
Any progress here? I'm looking forward to seeing this in action.

**Comment by dennisoelkers** [comment]
This is very much out of date. The functionality is now present through the dark mode and the log view widget, I would say. Therefore I am closing this. Thanks @STRML!

**Pull request closed without merging**
