### PR TITLE
Revert default behavior of `remove_field` to not perform regex-matching

### LINKED ISSUE #16047: Fields with '.' can not be accessed with backticks anymore
## Expected Behavior

pipeline function _remove_field removes field(s) as in 5.0

## Current Behavior

remove_field does not difference between _ and '.' in Field name

## Possible Solution

Something in 5.1 broke this feature

## Steps to Reproduce (for bugs)

1.) Create Pipeline rule

  set_field("test.duplicate", "test-1");
  set_field("test_duplicate", concat(to_string($message.`test.duplicate`),"-2"));
  remove_field("test.duplicate");

2.) observe that test_duplicate is not present

## Context

Rules which worked fine in 5.0 got broken with update on 5.1 without any processing error or other indicator
## Your Environment

* Graylog Version: 5.1
* Java Version: 17
* OpenSearch Version: 2.7
* MongoDB Version: 5
* Operating System:
* Browser version:

### LINKED ISSUE #19098: remove_field pipeline function performance regression
Adding support for removing fields with regular expressions (https://github.com/Graylog2/graylog2-server/pull/15131)
can have a huge performance impact on messages with many fields.

What used to be a `O(1)` remove from a hash map, is now looping over every message field `O(n)`
to then perform a regex match.

## Example benchmark on my system
Messages with `100` fields.
A pipeline rule with `20` `remove_field` calls. (20 is a realistic value, I've seen setups with 50)

### Now:
`org.graylog.plugins.pipelineprocessor.processors.PipelineInterpreter.executionTime`:
 `mean`: 336μs

throughput: 2500 msg/sec

### Regex change reverted:
`org.graylog.plugins.pipelineprocessor.processors.PipelineInterpreter.executionTime`:
`mean`: 5μs
throughput: 11000 msg/sec

## Expected Behavior

This change should've done by introducing a new pipeline function e.g. `remove_fields` (plural)

## Current Behavior

The current `remove_field` function creates a performance regression for lots of users, and also changes the behavior unexpectedly:
https://github.com/Graylog2/graylog2-server/issues/16047

## Possible Solution

Change this is back the way it was is not possible without introducing a breaking change for some users.
I suggest we restore the previous behavior (supporting a single field only) and move the new functionality
to a new function.

Users that already use the regex match will need to be notified and adopt their rules.

### PR DESCRIPTION
**Pull request by patrickmann**
Resolves #19098 
Resolves #16047 

Fix performance and functional regression in pipeline function `remove_field` by introducing optional parameter `is_regex`.

## Description
GL 5.1 added regex-matching to the pipeline function `remove_field`. This breaks existing pipeline rules that call
`remove_field` with a field name containing a regex reserved character, notably `.`. Performance of existing rules
may also be degraded.
Both issues are addressed by introducing a new optional parameter `is_regex`, which is `false` by default; thus reverting
to the old behavior.
If regex-matching is desired, the `remove_field` must now be called with parameter `is_regex:true`.

This is a **breaking change** for users that have started using the 5.1 regex capability. They will need to add `is_regex:true` (or revert the pattern to a previous non-regex field name, if they had changed it after upgrading).

## Motivation and Context

See discussion in linked issue.

## How Has This Been Tested?
- unit test
- performed perf testing using metric `org.graylog.plugins.pipelineprocessor.processors.PipelineInterpreter.executionTime`

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by bernd** [comment]
> GL 6.0.0 added regex-matching to the pipeline function `remove_field`.

The change was already added for Graylog 5.1.0.

**Comment by kroepke** [comment]
I don't think we should make this change this way:
* The changes introduced in 5c3eb576efbd840260bc5e7d87ed1e559766807a and de60ff6a3b5cd3047b2e223652fed649f41684f9 no longer match the function name. They could remove multiple fields instead of one.
* de60ff6a3b5cd3047b2e223652fed649f41684f9 as a fix for https://github.com/Graylog2/graylog2-server/issues/8128 doesn't allow passing in a list of fields to keep, only a pattern. It's questionable whether removing all fields except a static one is a sensible approach; the better option is to create a new message and drop the original one.
* After the breaking change added in 5.1.0, we can no longer be sure what the intention of calling `remove_field` is: should it interpret the argument as a pattern or exact string? Without migrations or at least warnings, we cannot simply revert the behavior and create another silent breaking change.

My suggestion:
* revert `remove_field` to its pre-5.1 behavior. It should remove a single named field, as the name suggests, nothing else. This operation should be fast.
* Add a `remove_fields` function that takes either a list of field names to remove (e.g., `names = ["foo", "bar", "baz"]` or taking the list from a variable, like a lookup table result) or a pattern `pattern = "foo(o*)bar"` or list of patterns `patterns = ["foo(bar)?", "debug_.+"]`). If necessary add the `invert` parameter here, although I would name it more explicitly, e.g. `keep_only_matches` or something like that)
* We need to be able to inform users about potentially broken `remove_field` calls before release the above, otherwise we run the risk of silently corrupting their processing. A check whether any rule source code contains a `remove_field` call with the passed string containing `.`, `+`, `*`, `[`, `(` should cover the common cases (please ensure that this indeed covers all relevant cases!) and whether `invert` was used. This should cause a UI warning with explanations how to fix the issue.

**Comment by kroepke** [comment]
Based on several discussions, I think we should take the following course:
For 6.0.1, let's immediately provide workarounds for performance regression and the ambiguity that arises when a fixed string, such as `foo.bar`, is passed but interpreted as a pattern.
This should come in the form of adding two functions:
 - `remove_single_field` which behaves as `remove_field` did before 5c3eb576efbd840260bc5e7d87ed1e559766807a
 - `remove_multiple_fields` which takes the following parameters:
    - `message`, optional, like all the other message-oriented functions
    - `pattern`, required, interpreted as a single pattern that removes all fields that match the given regular expression string

The above should be then backported to 5.1 and 5.2 to provide users with workarounds for the two issues.
Illuminate should get updates for those versions as well, to avoid the performance problems, please coordinate with them.

At least for 6.1 we need to have:
 - A way to deprecate functions including making users aware of this in the UI.
 - Deprecate `remove_field` with the target of full removal in 7.0.
 - Add a rate-limited logger to RemoveField, signaling the deprecation.

Improvements for later:
 - Improve `remove_multiple_fields` to support a list of patterns, a list of exact field names, and a way to invert the match.

**Comment by patrickmann** [comment]
Closing in favor of new PR #19268

**Pull request closed without merging**
