### PR TITLE
Properly close OkHttp Response objects to avoid resource leaks

### PR DESCRIPTION
**Pull request by joschi**
OkHttp Responses must be closed properly: https://github.com/square/okhttp/blob/parent-3.4.1/okhttp/src/main/java/okhttp3/ResponseBody.java#L37-L39

Refs #2811

### CODE REVIEW

**Comment by joschi** [comment]
This PR should be cherry-picked into `2.1` when merged.

**Comment by edmundoa** [comment]
LGTM 👍

**Comment by sre-jon** [comment]
Does this fix address the issue that causes the browser to wait for available sockets?

**Comment by joschi** [comment]
@sre-jon No. If you have found a bug in Graylog, please open another issue.

**Pull request merged**
