### PR TITLE
Remove Content Pack Auto Loader

### LINKED ISSUE #4940: Remove legacy auto content pack loader
The legacy content pack system had a feature that would load **and install** any content pack that exists in the `content_packs_dir` directory. We have been using this to load and install the list of default Grok patterns into graylog on the first server start.

We want to remove the automatic content pack loader in favor of the new content pack system. Users don't seem to use this and we can introduce a better version based on the new content pack system if people really need it.

## Tasks

- [x] Remove [ContentPackLoaderPeriodical](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/periodical/ContentPackLoaderPeriodical.java) class
- [x] Remove [ContentPackLoaderConfig](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/bundles/ContentPackLoaderConfig.java) class
- [x] Remove content pack loader config from MongoDB (really needed?)
- [x] Remove Content Packs Dir Configuration Option

### PR DESCRIPTION
**Pull request by kmerz**
## Description
The content pack auto loader should not be used anylonger,
instead a migration will be written for seeding the grok patterns.

## Motivation and Context
Not needed anymore.

## How Has This Been Tested?
Started the server.

Fixes #4940

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by artturik** [comment]
I have used this configuration options to bootstrap graylog server with working inputs and streams, what should be used now?

Not found any notes about the change in upgrade instructions for Graylog 3.0

**Comment by pastukhov** [comment]
@artturik Something kind of https://github.com/kolomiichenko/graylog-api

**Comment by kmerz** [comment]
As mentioned in the bug #4940:

> We want to remove the automatic content pack loader in favor of the new content pack system. Users don't seem to use this and we can introduce a better version based on the new content pack system if people really need it.

@artturik can you explain your use case more detailed, perhaps in a feature request and we will see if we can come up with something?

**Comment by artturik** [comment]
I am using graylog docker images and deploying them with docker-compose and kuberenetes, I have used these features to have graylog launched in ready to use state - it have input and streams. For having this now I should use API to apply my content-packs.

Example configuration:

```yaml
version: '2.3'
services:
  graylog:
    restart: always
    image: graylog/graylog:2.5
    environment:
      - GRAYLOG_CONTENT_PACKS_AUTO_LOAD=streams.json,tcp-input.json
    volumes:
      - ./contentpacks:/usr/share/graylog/data/contentpacks
```

tcp-input.json (Legacy Contentpack):
```json
{
  "name": "TCP GELF input on 12201",
  "description": "Adds a global TCP GELF input on port 12201",
  "category": "Input",
  "inputs": [
    {
      "id": "5c0808a43b3af50001ad1753",
      "title": "Gelf TCP",
      "configuration": {
        "..."
      },
      "static_fields": {},
      "type": "org.graylog2.inputs.gelf.tcp.GELFTCPInput",
      "global": true,
    }
  ],
}
```

As I know, I am not the only one who use this setup:

**Comment by pastukhov** [comment]
Same as @artturik 
I'm using content pack to init graylog installation with inputs in kubernetes cluster.

**Comment by snitrama** [comment]
We have the same use case as @artturik. Using content pack to init graylog with inputs on a docker swarm cluster.

**Comment by ynnt** [comment]
So, the only solution is to write some scripts for configuration using the REST API?

**Comment by Sharma-Rajat** [comment]
+1 do we have to use the REST API to configure graylog on startup now?

**Comment by Sharma-Rajat** [comment]
> So, the only solution is to write some scripts for configuration using the REST API?

+1 do we have to use the REST API to configure graylog on startup now?

**Comment by kmerz** [comment]
To make it clear: The best work around is to upload and install the content packs via REST API.

We discuss how we want to proceed with your good input and hope to find a satisfying solution soon.

**Comment by asoltesz** [comment]
"To make it clear: The best work around is to upload and install the content packs via REST API."

Maybe it is a workaround but it is not a good one.

For Docker containers, it is very convoluted to use a REST API to initialize the application. Most container authors will prefer config files that can be copied or bind-mounted into the container according to needs.

Sensible applications make it possible to provide configuration in files especially if they are complex ones like Graylog.

Maybe the original functionality needs to be brought back. There was nothing wrong with it and seemingly it WAS used.

**Comment by helmuthva** [comment]
Workaround for Ansible using API - having to retry to mitigate race with Graylog bootstrap ...

```
- name: Lists current inputs
  uri:
    url: http://YOUR_GRAYLOG_IP:9000/api/system/inputs
    method: GET
    user: "admin"
    password: "YOUR_ADMIN_PASSWORD"
    force_basic_auth: yes
    headers:
      X-Requested-By: me
    status_code: 200
  register: graylog_inputs
  retries: 10
  delay: 3
  until: graylog_inputs is not failed

- name: Find Gelf UDP input
  set_fact:
    graylog_input_gelf: "{{ graylog_inputs|json_query(query) }}"
  vars:
    query: "json.inputs[?name==`GELF UDP`] | [0]"

- name: Create global Gelf UDP input
  uri:
    url: http://YOUR_GRAYLOG_IP:9000/api/system/inputs
    method: POST
    user: "admin"
    password: "YOUR_ADMIN_PASSWORD"
    body: '{"title":"Gelf UDP","type":"org.graylog2.inputs.gelf.udp.GELFUDPInput","configuration":{"bind_address":"0.0.0.0","port":12201,"recv_buffer_size":262144,"override_source":null,"decompress_size_limit":8388608},"global":true}'
    force_basic_auth: yes
    headers:
      X-Requested-By: me
    status_code: 201
    body_format: json
  when: graylog_input_gelf is not defined or graylog_input_gelf|length==0

- name: Find Syslog UDP input
  set_fact:
    graylog_input_syslog: "{{ graylog_inputs|json_query(query) }}"
  vars:
    query: "json.inputs[?name==`Syslog UDP`] | [0]"

- name: Create global Syslog UDP input
  uri:
    url: http://YOUR_GRAYLOG_IP:9000/api/system/inputs
    method: POST
    user: "admin"
    password: "YOUR_ADMIN_PASSWORD"
    body: '{"title":"Syslog UDP","type":"org.graylog2.inputs.syslog.udp.SyslogUDPInput","configuration":{"bind_address":"0.0.0.0","port":1514,"recv_buffer_size":262144,"override_source":null},"global":true}'
    force_basic_auth: yes
    headers:
      X-Requested-By: me
    status_code: 201
    body_format: json
  when: graylog_input_syslog is not defined or graylog_input_syslog|length==0
```

**Comment by keeprocking** [comment]
Gents, do I understand it correctly that now the only suggested way to bootstrap the inputs is to use the API?

I have a bunch of functional tests in https://github.com/keeprocking/pygelf and used to configure the inputs the old way, i.e. using content packs. The new way seems to be overkill for that.

**Comment by kmerz** [comment]
There is a PR in queue for review which will bring back the autoload feature.

To speed up the process everyone willing and able is invited to test the PR and give feedback.

https://github.com/Graylog2/graylog2-server/pull/6096

**Comment by dnsmichi** [comment]
I've implemented a rudimentary but working provisioner script inside Puppet/Vagrant. This also includes how to upload and install content packs which took me a while to figure out - docs issue here: #6887. 

https://github.com/Icinga/icinga-vagrant/blob/master/.puppet/modules/profiles/templates/graylog/graylog-seed.py.erb

Keep in mind that this is an ERB template requiring several variables being replaced on Puppet apply. This is used in the `graylog` Vagrant box.

**Pull request merged**
