### PR TITLE
Display not found page

### PR DESCRIPTION
**Pull request by edmundoa**
This adds the 404 page back when the route doesn't match another component. In the end I'm sending the "funny" in the PR. The image is under a Creative Commons Zero license, so don't think there is any problem using it: http://gratisography.com/terms.html

We can also ship a more serious version if necessary :smile:

### CODE REVIEW

**Comment by bernd** [comment]
I like the funny 404 page. Any other opinions? @dennisoelkers @joschi @kroepke @lennartkoopmann @mariussturm

**Comment by joschi** [comment]
I like the funny image but can we make it a little bit smaller? I find ~500 KB and 1836x1224 pixels a little too much…

**Comment by edmundoa** [comment]
@joschi I will try, in the end it depends on how it affects the image quality. The original is 5MB so getting it down to 500KB was already a big weight loss :smile:

**Comment by bernd** [comment]
LGTM :+1:

**Pull request merged**
