### PR TITLE
Refactor PaginatedGrokPatternService to no longer extend PaginatedDbService

### PR DESCRIPTION
**Pull request by thll**
/nocl

### CODE REVIEW

**Comment by patrickmann** [comment]
The switch to `MongoPaginationHelper` looks fine. 
But the `grok/paginated` API isn't performing the way I'd expect (independent of this PR). I get the same results for different sort criteria or sort order. I would expect different results. E.g. these both return the same values in the same order:
```
/api/system/grok/paginated?page=1&per_page=3&sort=id&order=asc
/api/system/grok/paginated?page=1&per_page=3&sort=id&order=desc
```

```
{
  "total": 76,
  "page": 1,
  "per_page": 3,
  "count": 3,
  "patterns": [
    {
      "name": "NOTSPACE",
      "pattern": "\\S+",
      "content_pack": null,
      "id": "65b7ba138cdb8c534a95401a"
    },
    {
      "name": "GREEDYDATA",
      "pattern": ".*",
      "content_pack": null,
      "id": "65b7ba138cdb8c534a95401c"
    },
    {
      "name": "YEAR",
      "pattern": "(?>\\d\\d){1,2}",
      "content_pack": null,
      "id": "65b7ba138cdb8c534a95401e"
    }
  ]
}
```

**Comment by thll** [comment]
> The switch to `MongoPaginationHelper` looks fine. But the `grok/paginated` API isn't performing the way I'd expect (independent of this PR). I get the same results for different sort criteria or sort order. I would expect different results. E.g. these both return the same values in the same order:

Thanks for testing @patrickmann.

Unless there is an explicit mapping, e.g. in the REST resource, the value for the sort field is expected to be the database name. So your example should work when you use `_id` instead of id. That's not very convenient but since the `id` field is not visible in the UI and also not in the list of fields that users are [allowed to search in](https://github.com/Graylog2/graylog2-server/blob/8ce9b3f5323b52e43c59c26777688015236d4ef9/graylog2-server/src/main/java/org/graylog2/rest/resources/system/GrokResource.java#L86), I think that behaviour is in line with most of our paginated API endpoints.

**Comment by thll** [comment]
> Got it - works fine when I use the correct field names in curl or postman. I was confused because none of the allowable values for sort in Swagger actually work. We should fix that:

good point, I'll take care of that

**Review by patrickmann — APPROVED** [review]
Looks good and successfully smoke-tested

**Pull request merged**
