### PR TITLE
Dashboard widget action dropdown position (Backport of #7305 for 3.2)

### PR DESCRIPTION
**Pull request by linuspahl**
Backport of #7305 for 3.2

## Description

Dynamically place the dropdown on the opposite side if not enough room

## Motivation and Context

Dropdown on right side can disappear off of edge
Peek 2020-01-27 16-54

## Screenshots (if appropriate):
image
image
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by linuspahl** [comment]
@dennisoelkers Do you see the same behaviour on the master branch? Because we are using the same implementation there and I can't reproduce it right now. If not, I will try to reproduce it on this branch.

**Comment by dennisoelkers** [comment]
@linuspahl: No, it looks fine on `master`.

**Comment by linuspahl** [comment]
@dennisoelkers I've tried to reproduce it on this branch and was not able to do it for the data table header, but it's values. But not consistently. Right now it looks like a problem with the implementation in general. I will continue my investigation.

**Comment by linuspahl** [comment]
I've created a fix (https://github.com/Graylog2/graylog2-server/pull/7658) for the described problem and will merge the changes into this branch, once the fix got merged into master.

**Pull request merged**
