### PR TITLE
Rebuilding Date/Time Picker for more flexibility

### PR DESCRIPTION
**Pull request by kyleknighted**
## Description

Creating new Date & Time Range experience for the Search bar (Dashboard & Widgets included)

## Motivation and Context

Allowing more flexibility in the date and time chosen by the User

## Screenshots (if appropriate):
image
image
image
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Review by kmerz — CHANGES_REQUESTED** [review]
- I have problem with the number input for relative timerange, but I will create an Issue for that.
- I tested it on my machine and beside the already mentioned problem it is fine.
- The only open think is the test which was commented out. Either delete the test if it is not relevant anymore, fix the test or add a comment why you cannot activate the test.

**Review by edmundoa — APPROVED** [review]
I haven't looked at the code but clicked around. It all seemed to work and I like it a lot, it makes things way easier to understand in my opinion. Great job! 🎉

**Review by kmerz — APPROVED** [review]
LGTM :+1: 
Worked on my machine! :heavy_check_mark:

**Review by dennisoelkers — CHANGES_REQUESTED** [review]
After merging target branch in, I am seeing styling glitches in the absolute time range section:

image

Also, one suggestion: can we open the date picker when a user clicks on the timerange summary next to it?

**Comment by kyleknighted** [comment]
@dennisoelkers this is actually broken in master and not on this branch
image

**Comment by Gaya** [comment]
This should fix that problem in develop https://github.com/Graylog2/graylog2-server/pull/10026

**Review by dennisoelkers — APPROVED** [review]
All isses resolved, looks good and works fine! Happy to get this in! :tada:

**Pull request merged**
