### PR TITLE
Replace mentions of "Graylog2" with "Graylog"

### PR DESCRIPTION
**Pull request by joschi**
There are still several places where the code base mentions "Graylog2" instead of "Graylog". This PR replaces those occurrences in the configuration file (and the corresponding code) and renames the prefixes to override configuration settings to `GRAYLOG_` (environment variables) and `graylog.` (JVM system properties) respectively.

### CODE REVIEW

**Comment by bernd** [comment]
What is the upgrade path for the changed ES cluster name, index prefix and the changed MongoDB database?

**Comment by joschi** [comment]
> What is the upgrade path for the changed ES cluster name, index prefix and the changed MongoDB database?

Just the same as when users change those settings manually: They'll have to adjust the other systems accordingly. For existing users, they can simply set the configuration values to their old defaults.

**Comment by bernd** [comment]
@joschi Please add a `UPGRADE-NOTES.md` or `CHANGELOG.md` and document the upgrade steps for this.

I think we should track this information in the repository so we can compile the changelogs from this. Otherwise it's hard to track if the needed documentation is done already.

**Comment by bernd** [comment]
LGTM :+1:

**Pull request merged**
