### PR TITLE
Optimize populating of user dropdown

### PR DESCRIPTION
**Pull request by patrickmann**
As described in #12453, creating an email notification can be slow when there are a lot of users. This is due to the amount of work required to build the full set of user objects, particularly computing the set of permissions assigned to each user. Since we are only interested in the list of user emails, we should avoid fetching extraneous data.

The same thing applies to the user creation form, which fetches existing users to ensure uniqueness.

This PR adds the following optional query parameters to the `api/users` endpoint:
- include_sessions (default: true): if false, do not check current session information for users
- include_permissions (default: true): if false, do not return any permissions data

By calling `api/users?include_permissions=false&include_sessions=false` we speed up populating the email dropdown significantly. Testing with 3000 users (each with a single team membership) and 1000 sessions we observed a speed-up of approximately 5x.

**Note**: the API change is backward compatible, since the new parameters are optional with default values that preserve the legacy behavior.

### CODE REVIEW

**Review by mnin — APPROVED** [review]
LGTM

**Comment by danotorrey** [comment]
I also added a comment in https://github.com/Graylog2/graylog2-server/issues/12453#issuecomment-1142675544. But, I also think that the improvements made here will still be helpful. We will just need to decide if this PR should be merged first, and a separate should be filed to address the dropdown improvements.

I will review and test the code in this PR tomorrow morning, as well as check back for feedback from @patrickmann and @ousmaneo on the dropdown suggestion.

**Comment by patrickmann** [comment]
Lets get this merged and start a new PR for the filtered dropdown solution suggested in #12453. 
This PR is pretty low-risk and doesn't hurt anything. In certain cases it will still improve the UI responsiveness. So I think it's worth keeping it.

**Comment by patrickmann** [comment]
> I am okay with merging this PR if we have a new issue for the widget change (including the removal of the parameters we are now adding) and a plan for when it will be done.

@Bernd Here is a new issue: #12819

**Comment by danotorrey** [comment]
Thanks @patrickmann. I will finish reviewing today or tomorrow.

**Review by danotorrey — APPROVED** [review]

**Pull request merged**
