### PR TITLE
Sync cloud 4.0

### PR DESCRIPTION
**Pull request by edmundoa**
Update `cloud-4.0` with the latest `4.0` changes.

/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#2070,Graylog2/graylog-plugin-enterprise-integrations#477,Graylog2/graylog-plugin-integrations#748,Graylog2/graylog-plugin-cloud#749

### CODE REVIEW

**Comment by ousmaneo** [comment]
Hi @edmundoa, it seems there is already a new `4.0.6-SNAPSHOT`

**Review by Gaya — COMMENTED** [review]
Looks good to me, but I'll leave it up to the Java specialists 😊

**Comment by edmundoa** [comment]
Updated all PRs to use `4.0.6-SNAPSHOT`, please re-check after tests are green :)

**Review by ousmaneo — APPROVED** [review]
Legit !

**Pull request merged**
