### PR TITLE
ES/OS alias fields have their types properly resolved

### LINKED ISSUE #18526: Field types lookup does not resolve alias fields
Using `FieldTypesLookup#getType()` for a field that is of `type` `alias`
should return the type of the alias' target (known as `path`).

The alias field type is shown as a question mark in the UI, and when used for sorting, 
creates a broken query, because the type is copied into an `unmapped` sort order.

* Graylog Version: 6.0.0-SNAP

### PR DESCRIPTION
**Pull request by luk-kaminski**
## Description
Fixes #18526
/nocl

## Motivation and Context
1. Get rid of problems with `gl2_second_sort_field` alias that we have started using.
2. Have type of aliased field properly resolved.
3. Fix a problem with sorting by any alias field.

## Warning
This issue **is NOT** about introducing full support of aliased fields in **every** possible place in GL!

## How Has This Been Tested?
Manually and with additional unit tests.

## Screenshots (if appropriate):
See comments in ##18526

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Review by janheise — COMMENTED** [review]
Do we need a changelog for this?

**Comment by luk-kaminski** [comment]
> Do we need a changelog for this?

Good question. I am not sure, I'd personally prefer not to introduce the changelog, as we do not fully support aliases and we probably should not advertise alias-related fixes publicly...

@mpfz0r - what do you think???

**Review by janheise — APPROVED** [review]
LGTM, but maybe 2 more eyes are a good thing

**Review by mpfz0r — APPROVED** [review]
LGTM. Thank you for the fix :pray: 

I don't think this needs a changelog

**Pull request merged**
