### PR TITLE
Remove GC warnings

### LINKED ISSUE #8592: Nodes with too long GC pauses with G1GC
Graylog generates a lot of GC pause alerts like

> Nodes with too long GC pauses (triggered 2 days ago)
> There are Graylog nodes on which the garbage collector runs too long. Garbage collection runs should be as short as possible. Please check whether those nodes are healthy. (Node: 7ee19339-0bae-45fe-9325-56166bcf088e, GC duration: 1699 ms, GC threshold: 1000 ms)

after switching to G1 GC. I believe the alerts are in error. GC probably does take a long time with G1GC, but as the world isn't stopped it isn't an issue. This alert should probably be modernized for use with newer JVMs with newer garbage collectors.

### PR DESCRIPTION
**Pull request by thll**
Now that we [enforce usage of G1GC](https://github.com/Graylog2/graylog2-server/pull/13929), garbage collection should be much less problematic for a Graylog node. 

Graylog would emit a warning notification when the duration of a GC run exceeded a configured threshold. With G1GC, the actual pause during the GC run should be relatively short, so the overall duration of the GC run is less meaningful. 

This PR removes these notifications.

Fixes #8592

### CODE REVIEW

**Review by bernd — COMMENTED** [review]
Please add the removal of the config options to `UPGRADING.md`. Thanks!

**Comment by mpfz0r** [comment]
> Please add the removal of the config options to `UPGRADING.md`. Thanks!

we should also mention the API change in the exposed configuration response

**Comment by thll** [comment]
> > Please add the removal of the config options to `UPGRADING.md`. Thanks!
> 
> we should also mention the API change in the exposed configuration response

Right, I forgot to mention this as an open question. At first, I only deprecated the option in the exposed configuration and always returned a dummy value of `-1`. But then I thought for this specific API it would be OK to make a breaking change, which is what we now have. @mpfz0r, @bernd, do you agree?

**Review by mpfz0r — APPROVED** [review]

**Comment by bernd** [comment]
> > > Please add the removal of the config options to `UPGRADING.md`. Thanks!
> > 
> > 
> > we should also mention the API change in the exposed configuration response
> 
> Right, I forgot to mention this as an open question. At first, I only deprecated the option in the exposed configuration and always returned a dummy value of `-1`. But then I thought for this specific API it would be OK to make a breaking change, which is what we now have. @mpfz0r, @bernd, do you agree?

@thll If we don't backport this to 5.0 or earlier, I am okay with removing the value from the API response.

**Pull request merged**
