### PR TITLE
fix auth backend when downgrading to open

### PR DESCRIPTION
**Pull request by AntonEbel**
## Description

When downgrading from enterprise to open and a configured enterprise authorization backend, the server does not start due to Guice exceptions.

## How Has This Been Tested?

- configure enterprise auth backend
- remove enterprise jars/pom

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

/nocl

### CODE REVIEW

**Review by thll — CHANGES_REQUESTED** [review]
Thanks for the initiative. I tried starting Graylog open with it after configuring an auth service backend in Graylog enterprise but the Login screen renders only a spinner 

image

and this is what I can see in the server log:
```
2023-11-28 10:40:33,036 ERROR: org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
java.lang.UnsupportedOperationException: null
	at org.graylog.security.authservice.AuthServiceBackendConfig$FallbackConfig.type(AuthServiceBackendConfig.java:65) ~[graylog.jar:?]
	at org.graylog.security.authservice.rest.AuthServiceBackendsResource.getActiveType(AuthServiceBackendsResource.java:116) ~[graylog.jar:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:134) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:177) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:81) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400) ~[graylog.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [graylog.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [graylog.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [graylog.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234) [graylog.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684) [graylog.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356) [graylog.jar:?]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180) [graylog.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.base/java.lang.Thread.run(Thread.java:833) [?:?]
```

So something is still missing.

**Comment by patrickmann** [comment]
I added exception handling so server will start up cleanly.
Other things still cause problems in a downgrade, e.g. due to forwarders. But at least you can now log in successfully.

**Comment by AntonEbel** [comment]
I can confirm that the UI is now working, but I had to run the frontend without the plugins as described [here](https://graylogdocumentation.atlassian.net/wiki/spaces/GLE/pages/3086123034/Run+Graylog-Open+in+dev+mode). @thll would you like to take another look?

**Comment by thll** [comment]
I can now log in but can't access the Authentication page. Fixing this properly will require more work. I'm not sure if it's worth going down that path. It's probably easier to advise users to delete their auth backend with the enterprise plugin still loaded before fully downgrading to open. That should be possible even without a valid license.

**Comment by thll** [comment]
We decided to not pursue this any further

**Pull request closed without merging**
