### PR TITLE
Set `X-Frame-Options` header, disallow embedding by default.

### PR DESCRIPTION
**Pull request by dennisoelkers**
## Motivation and Context

This PR is adding a configuration option `http_allow_embedding`, which is configuring if embedding the web frontend (or any other API request) is allowed or not. It defaults to `false`, disallowing embedding to prevent clickjacking. It can be set to `true`, which would allow embedding "as long as the site including it in a frame is the same as the one serving the page."[*]

This is a short-term solution to prevent clickjacking. It should be replaced at some point with a complete content security policy, particularly because the `X-Frame-Options` header is deprecated by the corresponding CSP directive.

Fixes Graylog2/graylog-plugin-enterprise#3884

[*]: <https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options#directives> "MDN Docs for `X-Frame-Options`"

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Review by bernd — COMMENTED** [review]
@dennisoelkers The MDN docs on [X-Frame-Options](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) say that the option is obsoleted by [Content-Security-Policy=frame-ancestors](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors). When looking at the browser compatibility table, the main reason for using `X-Frame-Options` would be IE 8 support.

Should we use the `C-S-P=frame-ancestors` header instead?

**Comment by dennisoelkers** [comment]
@bernd: This is what I am referring to in the PR body:

> This is a short-term solution to prevent clickjacking. It should be replaced at some point with a complete content security policy, particularly because the X-Frame-Options header is deprecated by the corresponding CSP directive.

I think we should use the `X-Frame-Options`-header for now, because its implications are clear. Implementing a CSP would involve a bit more work and testing, but is beneficial and should be done soon to supersede this.

**Comment by bernd** [comment]
> @bernd: This is what I am referring to in the PR body:
> 
> > This is a short-term solution to prevent clickjacking. It should be replaced at some point with a complete content security policy, particularly because the X-Frame-Options header is deprecated by the corresponding CSP directive.
> 
> I think we should use the `X-Frame-Options`-header for now, because its implications are clear. Implementing a CSP would involve a bit more work and testing, but is beneficial and should be done soon to supersede this.

@dennisoelkers Doh! Sorry for not reading properly... :confused: 

Can you open an issue for CSP if we don't have one yet? Thank you!

**Review by bernd — APPROVED** [review]
Thank you! :pray:

**Pull request merged**
