### PR TITLE
Stream details outputs

### PR DESCRIPTION
**Pull request by ousmaneo**
Add the outputs section on the stream details page destination segment. 
- Allow add, edit, remove output and also assign existing 

/nocl

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by gally47 — CHANGES_REQUESTED** [review]
Code looks good to me, found one nitpick.
I will test next.

**Review by gally47 — CHANGES_REQUESTED** [review]
Tested it, it works as expected.

there is one UI suggestion, the icon button actions are not consistent in color, type(outlined/filled) and also in position (row/column), I think we should consolidate them.

Screenshot 2024-06-25 at 12 18 37

Screenshot 2024-06-25 at 12 19 01

**Review by gally47 — APPROVED** [review]
LGTM.

**Review by kodjo-anipah — APPROVED** [review]
LGTM 
tested adding, editing, assigning & deleting outputs

**Pull request merged**
