### PR TITLE
Handle multiple principals in mongoDB session

### PR DESCRIPTION
**Pull request by thll**
## Description

A Shiro subject may have multiple principals, with the first principal being the "primary principal" and in our case that's the user ID.
This changes checks if we have multiple principals in a session and returns the first principal when looking up a user ID.

Once merged, we should forward-port this to the `master` branch.

## Motivation and Context

The principals collection may be used to transport additional attributes of a subject from the authorization service into the session. Treating the string representation of the principals collection as the user ID is wrong in this case.

Fixes Graylog2/graylog-plugin-cloud#705

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by thll** [comment]
@mpfz0r I noticed that the branch went out of sync with `cloud-4.0` so that the project wouldn't compile anymore. I synced the branches, made the code a little more resilient and added some minimal tests in the process.

**Review by mpfz0r — APPROVED** [review]
Works and LGTM

**Comment by mpfz0r** [comment]
@thll do we want this in master as well?

**Comment by bernd** [comment]
@thll @mpfz0r I think so. :+1:  The goal is to get rid of the cloud specific branches.

**Comment by mpfz0r** [comment]
@thll wanna create a forward-port? I can review

**Comment by thll** [comment]
> @thll wanna create a forward-port? I can review

@mpfz0r thanks. Created https://github.com/Graylog2/graylog2-server/pull/10093.

**Pull request merged**
