### PR TITLE
Throttle LB status if journal utilization is too high

### LINKED ISSUE #1100: Yellow status when journal is almost full
Hello,

May you please consider to cast a yellow status on /system/lbstatus/ when journal is almost full (~90%)?

Thanks.

### PR DESCRIPTION
**Pull request by joschi**
This change set adds the load balancer status "THROTTLED", represented by HTTP status 429 (Too many requests).

The load balancer status will be changed to THROTTLED (HTTP 429) if the journal utilization exceeds a configured threshold, see `lb_throttle_threshold_percentage` setting, and will be changed to ALIVE (HTTP 200) if the utilization is lower again.

Originally written by Mikko Lehtisalo (https://github.com/mikkolehtisalo)

Closes #1100
Refs #1952

### CODE REVIEW

**Comment by joschi** [comment]
See #1952 for previous discussion.

**Comment by dennisoelkers** [comment]
Could you please rebase it? I will review it afterwards.

**Comment by joschi** [comment]
@dennisoelkers Done.

**Comment by dennisoelkers** [comment]
LGTM 👍

**Pull request merged**
