### PR TITLE
Properly register Event Notification config entity subtypes

### PR DESCRIPTION
**Pull request by danotorrey**
## Description

In order for content pack imports to work successfully for Event Notifications, a Jackson subtype must be properly registered for each `EventNotificationConfigEntity` instance. 

This PR adds a new `PluginModule.addNotificationType()` method, which also accepts the content pack entity type sting and class as arguments, and properly registers the subtype: 

```
org.graylog2.plugin.PluginModule.addNotificationType(name, notificationClass, handlerClass, factoryClass, contentPackEntityName, contentPackEntityClass)
```

The old `PluginModule.addNotificationType()` method was also deprecated in this PR and noted in the UPGRADING.md` document.

It seems appropriate to do in this general way, since all event notification types should be supported in content packs. This new method will prevent developers from accidentally forgetting to register the additional content pack entity config class.

## Motivation and Context

This resolves the error `java.lang.IllegalArgumentException: Could not resolve type id '<notification-type>' as a subtype of [simple type, class org.graylog.events.contentpack.entities.EventNotificationConfigEntity]` that occurs when attempting to import content packs that reference non-subtype-registered notification config entities.

Full exception:
```
2022-07-28 15:36:20,246 ERROR: org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
org.graylog.plugins.illuminate.installation.BundleInstallationException: Encountered an unhandled exception during installation: Could not resolve type id 'slack-notification-v1' as a subtype of [simple type, class org.graylog.events.contentpack.entities.EventNotificationConfigEntity]: known type ids = [email-notification-v1, http-notification-v1, legacy-alarm-callback-notification-v1, teams-notification-v1] (for POJO property 'config')
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.graylog.events.contentpack.entities.AutoValue_NotificationEntity$Builder["config"])
	at org.graylog.plugins.illuminate.installation.BundleInstallationException.unhandled(BundleInstallationException.java:50) ~[classes/:?]
	at org.graylog.plugins.illuminate.installation.BundleInstaller.installBundle(BundleInstaller.java:167) ~[classes/:?]
	at org.graylog.plugins.illuminate.bundle.BundleManagementService.lambda$installBundle$8(BundleManagementService.java:320) ~[classes/:?]
	at org.graylog.plugins.illuminate.bundle.BundleManagementService.suspendProcessingAndExecute(BundleManagementService.java:339) ~[classes/:?]
	at org.graylog.plugins.illuminate.bundle.BundleManagementService.installBundle(BundleManagementService.java:316) ~[classes/:?]
	at org.graylog.plugins.illuminate.rest.BundleManagementResource.installBundle(BundleManagementResource.java:173) ~[classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
```

This has been happening for many event notification types. I believe the condition occurred by accident, where developers did not know the additional subtype registration was required. This new general method should prevent that.

Refs https://github.com/Graylog2/graylog2-server/issues/7801

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by danotorrey** [comment]
Note: This PR is in draft status, because I need to open up corresponding PRs in a couple other plugin repos to fully fix the issue. I expect to do that tomorrow.

**Review by ryan-carroll-graylog — APPROVED** [review]
This all looks good! I tested Content Packs with various Notification types and they import correctly now. I really like that this approach will streamline future development.
I think the build just needs a refresh and this is good to go.

**Comment by danotorrey** [comment]
Thanks a lot for the thorough testing @ryan-carroll-graylog! Running the build again now 🤞.

**Comment by danotorrey** [comment]
I will leave this open until tomorrow for any additional reviews, then I will merge it. I am planning to backport this, since it's a bug and there is no risk of related issues.

**Pull request merged**
