### PR TITLE
add fixedvalue

### PR DESCRIPTION
**Pull request by guilongyang**
## Description
provide a fixed value way to create an event definition #10261

## Motivation and Context
When I create an event definition ,I found that it does not support a fixed value way to custom a field

## How Has This Been Tested?
run the test clea

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (non-breaking change)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by guilongyang** [comment]
I have signed.

**Comment by guilongyang** [comment]
hello, anyone here ? I signed ,but not recheck it

**Review by guilongyang — COMMENTED** [review]
i signed the cla

**Comment by bernd** [comment]
@guilongyang What's the reason for creating a separate fixed value type? It's possible to just use the template type and enter static text like this:

image

**Comment by guilongyang** [comment]
@bernd I think i missed the feature, at first i think i should create a template, and then use it .so i code the fixed value type

**Pull request closed without merging**
