### PR TITLE
Add ordering of decorators and decoration stats to UI

### PR DESCRIPTION
**Pull request by dennisoelkers**
* adds ordering of decorators (by using drag and drop) to the decorator sidebar.
* shows in message details which fields are decorated, allows to toggle displaying original content, disabled field actions for added fields.

Requires merging of #2482.

### CODE REVIEW

**Comment by kroepke** [comment]
Overall this looks really good, but there are some rough edges:

* Synthetic fields in the sidebar are not marked as such, so the quickvalues etc dropdown is shown, but those functions don't work right now
* Drag'n'drop reordering sometimes applies too early, leading to jumbled results:
image
* creating/deleting decorators does not re-render the UI immediately right now

**Comment by dennisoelkers** [comment]
> * creating/deleting decorators does not re-render the UI immediately right now

This seems to be an issue with a stale build. I just tested locally and it works fine.

**Comment by kroepke** [comment]
Looks good to me, the only thing that is breaking right now is the following, but I think we can fix this in a subsequent bug fix. If you agree, I'd merge this.

1. Add a pipeline decorator that adds a simple static field to messages.
2. Select the field to show in the message table.
3. Remove the decorator from the result.
4. The field is still show as a table column.

**Comment by kroepke** [comment]
Agreed to fix the remaining issue offline, I'll create a ticket.

**Pull request merged**
