### PR TITLE
Remove deprecated MongoDB metrics reporter

### PR DESCRIPTION
**Pull request by joschi**
The integrated MongoDB metrics reporter has been deprecated for quite some time now and should be removed.

If users really depend on functionality like this, they can use https://github.com/Graylog2/graylog-plugin-metrics-reporter/tree/master/metrics-reporter-mongodb as replacement.

### CODE REVIEW

**Comment by bernd** [comment]
:+1: - Please mention the metrics reporter plugin in UPGRADING.

**Comment by bernd** [comment]
Sorry, please rebase again. :smile:

**Comment by joschi** [comment]
> Sorry, please rebase again. :smile: 

You're doing this on purpose, aren't you? 😉

**Comment by bernd** [comment]
` ¯\_(ツ)_/¯`

**Pull request merged**
