### PR TITLE
Stating the category of the license

### PR DESCRIPTION
**Pull request by marclaporte**
- https://en.wikipedia.org/wiki/Server_Side_Public_License
- https://www.graylog.org/post/graylog-v4-0-licensing-sspl
- https://github.com/Graylog2/graylog2-server/pull/9504
- https://opensource.org/osd

## Description
Indicating that SSPL is source-available

## Motivation and Context
The SSPL is not Open Source

## Checklist:
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by marclaporte** [comment]
@bernd Just following up on this.

**Comment by marclaporte** [comment]
@bernd  In October, you wrote "in the coming weeks."

**Comment by bernd** [comment]
@marclaporte See https://github.com/Graylog2/graylog2-server/pull/15646

**Comment by marclaporte** [comment]
@bernd 

Thank you. There are some more: https://github.com/search?q=repo%3AGraylog2%2Fgraylog2-server+%22open+source%22&type=code

**Comment by marclaporte** [comment]
> 
> There are some more
>

Spin off: https://github.com/Graylog2/graylog2-server/issues/20971

**Comment by Neustradamus** [comment]
Graylog2 is not open source?

**Comment by marclaporte** [comment]
@Neustradamus 

Indeed. It is source available but not Open Source.

**Pull request closed without merging**
