### PR TITLE
Prometheus input metrics

### PR DESCRIPTION
**Pull request by thll**
Adds a new mapping type for graylog input metrics.

E.g. specifying a metric mapping like the following:
```
- metric_name: "input_incoming_messages"
   type: "input_metric"
   input_metric_name: "incomingMessages"
```

Will create prometheus metrics like the following for all configured graylog inputs:
```
gl_input_incoming_messages_total{input_id="6241bd59d5dd6c7dc77278d4", input_type="org.graylog2.inputs.gelf.http.GELFHttpInput", instance="host.docker.internal:9833", job="prometheus", node="9c0c55fa-548f-4a44-9b8f-1138b3c5c4c3"}
gl_input_incoming_messages_total{input_id="6241db4fd5dd6c7dc772bc6b", input_type="org.graylog.plugins.forwarder.input.ForwarderServiceInput", instance="host.docker.internal:9833", job="prometheus", node="9c0c55fa-548f-4a44-9b8f-1138b3c5c4c3"}
gl_input_incoming_messages_total{input_id="6246ee49b8dc9c6bba59ba8e", input_type="org.graylog.plugins.beats.Beats2Input", instance="host.docker.internal:9833", job="prometheus", node="9c0c55fa-548f-4a44-9b8f-1138b3c5c4c3"}
gl_input_incoming_messages_total{input_id="626ba5560a4722218dac067c", input_type="org.graylog2.inputs.gelf.tcp.GELFTCPInput", instance="host.docker.internal:9833", job="prometheus", node="9c0c55fa-548f-4a44-9b8f-1138b3c5c4c3"}
```

Fixes https://github.com/Graylog2/graylog2-server/issues/12421

TODO:
- [x] Pending https://github.com/Graylog2/graylog2-server/pull/12570, a note to `UPGRADING.md` has to be added

### CODE REVIEW

**Comment by danotorrey** [comment]
Thanks for the PR @thll. I did not have a chance to review today, but I should have time on Monday.

**Comment by danotorrey** [comment]
@thll I have started reviewing, but have more testing to do tomorrow. Looking good so far. 

Question: Since this PR adds the `InputMetricMapping`, is it possible to verify that it registers the metrics for at least one input type in the unit tests?

**Comment by thll** [comment]
> Question: Since this PR adds the `InputMetricMapping`, is it possible to verify that it registers the metrics for at least one input type in the unit tests?

@danotorrey: yes, that should be possible. I'll try to add some tests.

**Comment by thll** [comment]
@danotorrey I've added some tests. Please have a look if this is what you had in mind.

**Review by patrickmann — APPROVED** [review]
Thx for adding the tests.
Tested locally with Grafana and it works as expected.

**Review by danotorrey — APPROVED** [review]
LGTM and tests successfully.

**Pull request merged**
