### PR TITLE
Solved the problem of running scripts that set up and use environment…

### PR DESCRIPTION
**Pull request by binyellow**
## Description

Use cross-env compatible windows to execute environment variable commands in front-end projects

## Motivation and Context

I run npm run build on windows and report an error: disable_plugins  is not a recognized command

## How Has This Been Tested?

Run npm run build on windows and mac to test

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by dennisoelkers** [comment]
Hey @binyellow,

thanks a lot for your valuable contribution. Would you please take the time to review our [Contributor License Agreement](https://cla-assistant.io/Graylog2/graylog2-server?pullRequest=8487)? Otherwise we cannot review/merge your PR.

**Comment by binyellow** [comment]
> Hey @binyellow,
> 
> thanks a lot for your valuable contribution. Would you please take the time to review our [Contributor License Agreement](https://cla-assistant.io/Graylog2/graylog2-server?pullRequest=8487)? Otherwise we cannot review/merge your PR.

Hello, I have dealt with it, please review

**Comment by youjiti** [comment]
please review this change, it work for me, very good!

**Comment by florianpopp** [comment]
@Graylog2/frontend please review.

**Comment by binyellow** [comment]
> @Graylog2/frontend please review.

hello bro, please check

**Comment by Gaya** [comment]
@binyellow merged

**Pull request merged**
