### PR TITLE
Update List<String> streamIds to Set<String> streamIds #4898

### PR DESCRIPTION
**Pull request by EmekeN**
## Description

Updates every reference of List<String> streamIds from IndexRange.java to Set<String> streamIds

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by dennisoelkers** [comment]
Hey @EmekeN, thanks for the contribution. What is the underlying issue that you want to address?

**Comment by EmekeN** [comment]
@dennisoelkers this refers to issue #4898  Convert IndexRange#streamIds to Set from List.  I want to finish the PR myself, but I don't have read permissions to Jenkins and my changes seem to break Travis CI build. Any ideas here?

**Comment by dennisoelkers** [comment]
@EmekeN: I see. Can you fix the [build error(s)](https://travis-ci.org/Graylog2/graylog2-server/builds/484604759#L2090)?

**Comment by dennisoelkers** [comment]
@EmekeN: The build is still failing. Are you still working on this?

**Comment by dennisoelkers** [comment]
Closing due to inactivity.

**Pull request closed without merging**
