### PR TITLE
Register GracefullShutdownHook for BatchedFilteredMessageOutput

### PR DESCRIPTION
**Pull request by kodjo-anipah**
/nocl part of unreleased featured
Registering a GracefullShutdownHook for the BatchedMessageOutput to make sure that we shut down this service first before other services get exterminated by the service manager

### CODE REVIEW

**Comment by bernd** [comment]
@kodjo-anipah I don't see any usage of this flag. How would we use it?

**Comment by kodjo-anipah** [comment]
> @kodjo-anipah I don't see any usage of this flag. How would we use it?
I am using it to check in the runtime service if he finished running before I continue with the shutdown process over there
https://github.com/Graylog2/graylog-plugin-enterprise/pull/8599/files#diff-1198e7f0b9835a85afe1785c62f549dac17cf8aa898355e6b0c43616fc06fbedR110

**Review by bernd — CHANGES_REQUESTED** [review]
Check my comment in https://github.com/Graylog2/graylog-plugin-enterprise/pull/8599#pullrequestreview-2328716747. I don't think we need this change if we go with my proposed solution.

**Review by bernd — APPROVED** [review]
Thanks! :+1:

**Pull request merged**
