### PR TITLE
Allow "JSON path value from HTTP API" Input to Use POST/PUT

### PR DESCRIPTION
**Pull request by ryan-carroll-graylog**
## Description

Adds to the "JSON path value from HTTP API" Input, the ability to use GET/POST/PUT HTTP methods as opposed to only GET.

To facilitate this 3 new fields have been added to the Input configuration:
- HTTP method (optional): HTTP method to use for the requests.
- HTTP body (optional): HTTP body for POST/PUT requests. Required for POST/PUT.
- HTTP content type (optional): HTTP content type for POST/PUT requests. Required for POST/PUT.

## Motivation and Context

Closes: https://github.com/Graylog2/graylog-plugin-enterprise/issues/6040

## How Has This Been Tested?

Locally in dev environment, unit tests.

- To verify request handling this site is handy: https://requestcatcher.com/
    - Catches and displays requests with header/boy/content type info.

- To verify response handling this site is handy: https://dummy.restapiexample.com/
    - Provides a simple API that accepts and responds to requests using JSON.

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by kingzacko1** [comment]
Should we force users to clear out the content type and HTTP body if the method is `GET`? Just seems odd to allow them to be left set. Otherwise, all looks good and works well! @ryan-carroll-graylog

**Review by kingzacko1 — APPROVED** [review]

**Comment by ryan-carroll-graylog** [comment]
> Should we force users to clear out the content type and HTTP body if the method is `GET`? Just seems odd to allow them to be left set. Otherwise, all looks good and works well! @ryan-carroll-graylog

Definitely agree. The UI validation for these non step inputs only checks that required fields are filled to I'd been working with just backend validation, which is kind of clunky because the input just throws an error after the edit form is closed. Let me see if there's a way to override that though. If not I can just do it as backend validation, or maybe just clear it out if GET is selected so it doesn't show up in the overview.

**Comment by kingzacko1** [comment]
@ryan-carroll-graylog definitely don't think it is a required thing if it is going to be a ton of work, but more of a nice to have if it can be done easily.

**Review by danotorrey — APPROVED** [review]
LGTM and tests successfully.

**Comment by ryan-carroll-graylog** [comment]
Still unable to add you as a reviewer @monrax, pinging here to see if it lets me.

**Comment by monrax** [comment]
Works great to pull data from Graylog API Security. Thank you for this feature 👍

**Review by monrax — APPROVED** [review]
LGTM!

**Comment by ryan-carroll-graylog** [comment]
> Works great to pull data from Graylog API Security. Thank you for this feature 👍

Awesome! Thanks for the review and for all the help on this @monrax!

**Pull request merged**
