### PR TITLE
fix: Add saved searches and new searches working again

### PR DESCRIPTION
**Pull request by zeeklop**
Fix flashing modals when trying to add a saved search as evidence for an investigation

/nocl
/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/6466

## Description

There was a change on how the dropdown menu works on buttons, which was causing the modals to add a saved search for an investigation to show up only for an instant. With this PR the investigations search plugin follows the same pattern as the dashboard solution allowing to put the modal views outside the dropdown menu component.

## Motivation and Context

Bug found with E2E

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by danotorrey** [comment]
@zeeklop I am getting this error when clicking the `...` to add a saved search to an investigation from the search page. 

image

```
Cannot destructure property 'searchInvestigationsModal' of 'modalRefs' as it is undefined.
TypeError: Cannot destructure property 'searchInvestigationsModal' of 'modalRefs' as it is undefined.
    at CoreSearchActions (http://localhost:8081/plugin.org.graylog.plugins.enterprise.EnterprisePlugin.js:192818:11)
    at renderWithHooks (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:14803:18)
    at mountIndeterminateComponent (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:17482:13)
    at beginWork (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:18596:16)
    at HTMLUnknownElement.callCallback (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:188:14)
    at Object.invokeGuardedCallbackDev (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:237:16)
    at invokeGuardedCallback (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:292:31)
    at beginWork$1 (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:23203:7)
    at performUnitOfWork (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:22157:12)
    at workLoopSync (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:22130:22)
```

**Comment by zeeklop** [comment]
> @zeeklop I am getting this error when clicking the `...` to add a saved search to an investigation from the search page.
> 
> image
> 
> ```
> Cannot destructure property 'searchInvestigationsModal' of 'modalRefs' as it is undefined.
> TypeError: Cannot destructure property 'searchInvestigationsModal' of 'modalRefs' as it is undefined.
>     at CoreSearchActions (http://localhost:8081/plugin.org.graylog.plugins.enterprise.EnterprisePlugin.js:192818:11)
>     at renderWithHooks (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:14803:18)
>     at mountIndeterminateComponent (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:17482:13)
>     at beginWork (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:18596:16)
>     at HTMLUnknownElement.callCallback (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:188:14)
>     at Object.invokeGuardedCallbackDev (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:237:16)
>     at invokeGuardedCallback (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:292:31)
>     at beginWork$1 (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:23203:7)
>     at performUnitOfWork (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:22157:12)
>     at workLoopSync (webpack://__/./node_modules/react-dom/cjs/react-dom.development.js?:22130:22)
> ```

@danotorrey thank you for testing this so quickly. I wasn't ready yet. You'll need to have checked out on enterprise the following branch `fix/search-investigations-modals` The issue required to modify how the modals are shared through the plugin system to then be able to mount them outside the menu component.

**Review by simonychuang — APPROVED** [review]
LGTM and tests succesfully

**Review by danotorrey — APPROVED** [review]
LGTM and tests successfully!

**Pull request merged**
