### PR TITLE
Return HTTP 400 when creating/updating a user with invalid role names

### LINKED ISSUE #4665: User Create and Update API returns 500 error when unexisting role name is included in roles request parameters
## Expected Behavior

Returns the 4xx error and appropriate error message.

## Current Behavior

Response Body

```json
{
  "type": "ApiError",
  "message": ""
}
```

Response Code: 500

### In case User Create API

Run a User Create API request whose roles parameter has unexisting role name.
It is convenient to use the API browser.

http://localhost:9000/api/api-browser#!/Users/create_post_1

Show the sample request body.

```json
{
  "username": "foo",
  "email": "foo@example.com",
  "full_name": "foo",
  "permissions": ["*"],
  "password": "password",
  "roles": ["unknown"]
}
```

### In case User Update API

Run a User Update API request whose roles parameter has unexisting role name.
It is convenient to use the API browser.

http://localhost:9000/api/api-browser#!/Users/changeUser_put_2

Show the sample request body.

username: foo

```json
{
  "email": "foo@example.com",
  "full_name": "foo",
  "permissions": ["*"],
  "password": "password",
  "roles": ["unknown"]
}
```

## Your Environment

* Graylog Version: 2.4.3-1
* Elasticsearch Version: 5.6.3
* MongoDB Version: 3
* Operating System: Mac OS X
* Browser version: Google Chrome 65.0.3325.162 (Official Build) (64 bit)

Show the docker-compose.yml which I use.

```yaml
---
version: '2'
services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongodb:
    image: mongo:3
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/security-settings.html#general-security-settings
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:2.4.3-1
    environment:
      # CHANGE ME!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
```

### PR DESCRIPTION
**Pull request by radykal-com**
## Description
Check all passed roles exist in the system prior to trying to assign them to the user

## Motivation and Context
Fixes #4665 

## How Has This Been Tested?
Try to create or update users through the API, current behaviour returns 500 without any message.
New behaviour returns 400 with a descriptive message about the roles

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by radykal-com** [comment]
Done. It seems travis build had some problems with testcontainers I think it's not related to this PR

**Comment by mpfz0r** [comment]
Closing this in favor of #9722 
Thank you @radykal-com and sorry for the embarrassingly long wait

**Comment by radykal-com** [comment]
You are welcome

**Pull request closed without merging**
