### PR TITLE
Backport 6.0: Markdown remediation steps

### PR DESCRIPTION
**Pull request by simonychuang**
Backport #18958 to `6.0`. 

/nocl

### CODE REVIEW

**Review by danotorrey — APPROVED** [review]
LGTM on 6.0!

**Review by kingzacko1 — APPROVED** [review]

**Comment by zeeklop** [comment]
Working great. Thanks for porting this fix.

Do we want to also add Markdown support to Sigma Rules? I think we have it on 6.1

**Comment by danotorrey** [comment]
> Do we want to also add Markdown support to Sigma Rules? I think we have it on 6.1

@zeeklop Good catch, yeah, I think we want to add it too.

**Review by ryan-carroll-graylog — APPROVED** [review]
Looks good on 6.0

**Pull request merged**
