### PR TITLE
Migrate to Apache Log4j 2

### PR DESCRIPTION
**Pull request by joschi**
This PR replaces the logging framework Log4j 1.x with Log4j 2, as the EOL of Log4j 1.x has just been announced: https://blogs.apache.org/foundation/entry/apache_logging_services_project_announces

The primary API being used for logging is still SLF4J but the underlying logging framework has been migrated from Log4j 1.x to Log4j 2. All transitive dependencies to Log4j 1.x have been excluded and the compatibility bridge of SLF4J has been pulled in (log4j-over-slf4j).

All relevant usages of the Log4j 1.x API have been replaced by the corresponding Log4j 2 implementations and the default configurations have been updated to work with Log4j 2 (`log4j2.xml` and `log4j2-test.xml`).

### CODE REVIEW

**Comment by bernd** [comment]
One important thing we have to keep in mind is that this is a backwards incompatible change. Not really for plugins but for the operating system packages. The packages ship with a log4j.xml so this would not be a drop in replacement but requires manual steps.

**Comment by bernd** [comment]
Removed this from 1.2, sorry. This is a breaking change. :confused:

**Comment by dennisoelkers** [comment]
What are the manual changes required for anyone upgrading from graylog 1.x (including log4j) to 2.x (including log4j2)? Are these documented somewhere?

**Comment by joschi** [comment]
@dennisoelkers People that are using a customized log4j configuration need to migrate it to the new log4j 2 configuration format (https://logging.apache.org/log4j/2.x/manual/migration.html#Configuring_Log4j_2) and if they were using custom appenders (or extended log4j in any other way), they need to find equivalents for log4j 2.
Normal users will get the new log4j 2 configuration via our usual distribution channels (DEB/RPM packages, virtual machine images, tar ball).

**Pull request merged**
