### PR TITLE
Replace message field analysers dropdown

### LINKED ISSUE #2022: Improve message field analysers usability
### Problem description
Using a drop-down to select the field analyser is far from optimal. We already tried that in the past and doesn't work well.

### Environment

* Graylog Version: Graylog 2.0.0-beta.2

### PR DESCRIPTION
**Pull request by edmundoa**
Improve usability of selecting field analysers by replacing the drop-down with a collapsible panel. The main advantage of this change is that it avoids scrolling inside the search sidebar when the number of fields is small and there's space on the screen.

Fixes #2022.

### CODE REVIEW

**Comment by bernd** [comment]
Not sure if this is supposed to be fixed, but I still have to scroll in the side bar.

screenshot from 2016-04-12 17 09 54

Maybe I got your description wrong and that cannot be avoided.

**Comment by edmundoa** [comment]
You cannot avoid scrolling when there is no space at the bottom. But you can avoid it when the sidebar can expand. This is what shouldn't happen:

screen shot 2016-04-12 at 17 15 17

In that case, the sidebar does not get to the bottom of the page, but the dropdown is still hidden, making you scroll when there is no need for it. The panel version will actually increase the sidebar height, allowing you to see all options without any further action.

This is specially annoying when you have three or four fields, as you will have to scroll all the time when using dropdowns.

**Comment by bernd** [comment]
Thanks for the explanation! :smiley:

**Comment by bernd** [comment]
LGTM :+1:

**Pull request merged**
