### PR TITLE
Upgrade to Elasticsearch 1.4.2

### PR DESCRIPTION
**Pull request by joschi**
Upgrade to Elasticsearch 1.4.x.

Unfortunately some useful information has been removed from ShardSearchFailure (elasticsearch/elasticsearch@90d2cb7dd506f188b534c72de7ba125e74f6ec21) with no proper replacement. As an alternative we could probably parse the query ourselves in cases of an error using the Lucene query parser.

Refs #847

### CODE REVIEW

**Comment by bernd** [comment]
Does the REST API change with this?

**Comment by joschi** [comment]
Yes, the API will change as we won't be able to return details about why a query failed like it was before. The information is still kind of there, but only as part of the String provided by `ShardSearchFailure#getMessage()` which would be horrible to parse (haha, explaining a parse exception by parsing stuff…).

**Comment by joschi** [comment]
The motivation to upgrade to ES 1.4.x at all is that all of the CircuitBreaker exceptions (introduced with the stability features in ES 1.4.x) are simply not understood by an ES 1.3.x client (they are "downcasted") and already confused people. The ES 1.3.x node client also impacts some third-party software like Kibana 4 in an ES 1.4.x cluster as the cluster can only use the protocol and features understood by all clients.

**Comment by henrikjohansen** [comment]
Ahhh - that explains why we had silently failing searches and other assorted issues in Graylog2 when the circuit breaker coughed up hairballs :)

:+1:

**Comment by joschi** [comment]
Closing in favor of #929.

**Pull request closed without merging**
