### PR TITLE
Run against ES7 in full backend tests as well.

### PR DESCRIPTION
**Pull request by dennisoelkers**
## Motivation and Context

Before this change, the tests in the `full-backend-tests` module did rung against ES6 only. This change is adding support for ES7 as well.

In addition, it reenables the tests by changing the packaging type back to `jar`.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by juju2112 — COMMENTED** [review]
It looks good to me. There are a couple failed tests, though.

https://jenkins.ci.torch.sh/job/Graylog-Snapshots/job/graylog2-server/job/PR-9288/1/console

**Review by bernd — DISMISSED** [review]
There is a failing test:
```
[2020-10-28T13:31:01.195Z] [ERROR] Failures: 
[2020-10-28T13:31:01.195Z] [ERROR]   BackendStartupIT.importsElasticsearchFixtures:80 
[2020-10-28T13:31:01.195Z] Expecting:
[2020-10-28T13:31:01.195Z]   <[]>
[2020-10-28T13:31:01.195Z] to contain exactly (and in same order):
[2020-10-28T13:31:01.195Z]   <["hello from es fixture"]>
[2020-10-28T13:31:01.195Z] but could not find the following elements:
[2020-10-28T13:31:01.195Z]   <["hello from es fixture"]>
[2020-10-28T13:31:01.195Z] 
[2020-10-28T13:31:01.195Z] [INFO] 
[2020-10-28T13:31:01.195Z] [ERROR] Tests run: 5, Failures: 1, Errors: 0, Skipped: 0
```

**Review by mpfz0r — APPROVED** [review]
LGTM

**Review by mpfz0r — APPROVED** [review]
Even bettererer :+1:

**Pull request merged**
