### PR TITLE
Refactor RestClientProvider, used for datanode-opensearch proxy

### PR DESCRIPTION
**Pull request by todvora**
This PR adds the option to target secific datanode/opensearch instances. The URL format is now 

* /datanodes/{hostname}/request/{path: .*} for Opensearch APIs
* /datanodes/{hostname}/rest/{path: .*} for Datanode rest apis

The `hostname` path parameter can be either a real hostname of the datanode or one of `leader` and `any`  keywords.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by moesterheld** [comment]
We need to provide a changelog here as this changes the existing endpoint address/behavior

**Comment by todvora** [comment]
@moesterheld Thanks, added changelog now. I was thinking about the fallback as well, but technically it's a massive code duplication (each method and all of its annotations would have to be duplicated). And I quite like the fact that we are forcing the user to think about the node that he want to talk to. It highlights the cluster nature and makes it obvious that there are probably more nodes that can respond to a request. So I'd rather not add this fallback.

**Comment by janheise** [comment]
I also don't mind that we change behaviour - this is pretty new functionality and it's an API call that is probably mostly used manually and not in scripts etc.

**Review by janheise — APPROVED** [review]
LGTM

**Pull request merged**
