### PR TITLE
Use events to push operations on outputs to cluster nodes

### LINKED ISSUE #5634: Changed configuration of an output is not reflected on other nodes
## Expected Behavior

When changing the configuration of an output its settings should be active immediately on all nodes in the cluster.

## Current Behavior

Output configuration is not reloaded on other nodes than the one it was changed on, until these Graylog server(s) is/are restarted.

## Steps to Reproduce (for bugs)

1. Create an output (regardless of GELF or STDOUT)
2. Update its settings (e.g. change Prefix for STDOUT or host/port for GELF) on node A
3. Verify that new settings are not used on node B
4. Restart Graylog server(s) on node B
5. Verify that new settings are used on node B

## Your Environment

* Graylog Version: 3.0.0-rc.1
* Elasticsearch Version: 6.5.0
* MongoDB Version: 3.6.8
* Operating System:
* Browser version:

### LINKED ISSUE #8714: Delete from Stream in Output cluster(System/Outputs) showing 404 error and restart graylog service require to forget disconnection of output
## Expected Behavior
Remove output from the stream via the Global i.e. "System -> Outputs -> Delete from stream" should be possible. After removing output it should delete/remove all connection from Graylog cluster nodes without restarting Graylog service.

## Current Behavior
1) The main problem is that when you disconnect/delete the output from a stream, it does not get disconnected from all cluster members but only from that one node that you are accessing the Web UI from. You have to restart the Graylog services on the other nodes to make them forget about the disconnected output.

2) Try to remove output from the stream via the global "System -> Outputs -> Delete from stream" it will fail with a 404
Screenshot 2020-08-06 at 19 28 32

## Possible Solution
1) After delete or disconnect output from stream, the restart of Graylog service require to remove all output connection from cluster nodes.

2) There is a workaround to delete output from Stream--> Manage Outputs -->Delete from Stream 
Screenshot 2020-08-06 at 19 25 39

## Steps to Reproduce (for bugs)
1. run a TCP sink on a Linux box with netcat (# nc -l -p 4102 -k)
2. select a stream, manage output, create GELF TCP output (default options)
3. notice the node you are actually accessing the UI from
4. remove the output from the stream (channel disconnected message will only appear on the node where you access the UI from)
5. stop the TCP sink/netcat on the Linux box
6. see the other nodes in the cluster complaining about output destination refusing connection

## Context
https://support.graylog.com/#ticket/zoom/3762

## Your Environment

* Graylog Version: 3.3.3
* Java Version: NA
* Elasticsearch Version:
* MongoDB Version: 
* Operating System: 
* Browser version:

### PR DESCRIPTION
**Pull request by thll**
Uses events to make sure that operations on outputs are applied on all cluster nodes.

Adds two new events:

1. An `OutputChangeEvent` is triggered when the configuration of an output is modified. The event is handled on all cluster nodes by restarting the output. Previously, any cluster node except the node receiving the initial API request to change an output would keep running the output with a stale configuration. Fixes #5634
2. An `OutputDeletedEvent` is triggered when an output is globally removed. The event is handled by stopping the output on all nodes. Previously, the output would keep running run on all cluster nodes, except the node receiving the initial API request. Fixes #8714

Furthermore, adds handling for the `StreamsChangedEvent` to the `OutputRegistry`. This allows the consolidation of running outputs in regards to them being referenced in any streams. Previously, unassigning an output from a stream would lead to the output being stopped on the node receiving the initial API request, even if the output was still assigned to a different stream. In such a case, the output was immediately started again to accommodate messages on the still assigned streams. With this change, a `StreamsChangedEvent` will lead to all un-assigned but still running outputs to be stopped.

Also removes the defunct `Delete from stream` button for outputs listed on the global outputs overview page `System/Outputs`. This is another fix for #8714.

### CODE REVIEW

**Comment by thll** [comment]
Also a fix for #11531

**Comment by thll** [comment]
Fixes https://github.com/Graylog2/graylog2-server/issues/11531
Fixes https://github.com/Graylog2/graylog2-server/issues/10199

**Review by AntonEbel — CHANGES_REQUESTED** [review]
Just a small finding. I tested it, works as expected.

**Comment by thll** [comment]
@AntonEbel: Thanks for the review. I addressed your comment. Could you have a final look please?

**Review by AntonEbel — APPROVED** [review]
LGTM.

**Pull request merged**
