### PR TITLE
4.3 Backport: Use legacy Geo IP fields if GIM schema enforcement is disabled (#13094)

### PR DESCRIPTION
**Pull request by kingzacko1**
## Description

Backport of #13094 resolving #12909
## Motivation and Context

See  #13094 and #12909 
## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by roberto-graylog — APPROVED** [review]
Looks good.

**Review by ryan-carroll-graylog — APPROVED** [review]
Testing in 4.3 and everything looks good.

**Review by danotorrey — APPROVED** [review]
LGTM!

**Comment by kingzacko1** [comment]
Thanks for merging this in @danotorrey!

**Pull request merged**
