### PR TITLE
Update Kafka client to 2.7.0 (#10146)

### LINKED ISSUE #9927: GELF Kafka Input - New consumer API (non-legacy) mode
## Expected Behavior
Kafka logs should get fetched without any errors.

## Current Behavior
Graylog log is continuously full of these errors:-
2021-01-18T22:54:15.192Z ERROR [KafkaTransport] WakeupException in poll. Kafka server is not responding.
2021-01-18T22:54:15.192Z ERROR [KafkaTransport] Caught recoverable exception. Retrying

## Context
I switched from the legacy mode (connection to zookeeper)

## Your Environment
cluster of 6 kafka servers (kafka-2.7.0-1)
centos 7

* Graylog Version: graylog-server-4.0.1-1
* Java Version: java-1.8.0
* Elasticsearch Version:  elasticsearch-oss-7.10.1-1
* MongoDB Version: mongodb-org-4.0.20-1
* Operating System: Centos 7

### PR DESCRIPTION
**Pull request by mpfz0r**
* Use shaded kafka 0.9.0.1 version for disk journal

* Update scala to 2.13.4

Workaround a bug in the jackson BOM.
It doesn't contain a managed dependency for
       jackson-module-scala_2.13

This makes it being resolved through kafka to a newer
version, which prevents Jersey to start.

* Switch to current kafka client

* Update log4j2 filter for shaded kafka

* Bump kafka to version -5 which should now be on mavencentral

* Keep Kafka legacy mode using the shaded client version

* Use a better readable client.id

 - Fix use of wrong props variable
 - Use a shortened node-id because the full node-id plus input-id is
   just too long to be readable

* Remove workarounds for bugs in the old kafka client

Those are not necessary anymore

Fixes #9927

* Mention workaround for incomplete jackson BOM

This can be removed, if
 https://github.com/FasterXML/jackson-bom/pull/38
gets merged, or we move to a newer jackson release.

* Bump shaded kafka version -6

This includes missing dependencies

Refs https://github.com/Graylog2/graylog-shaded/pull/4

* Keep Kafka ConsumerConfig log level package unshaded

The log level was meant for the new consumer library.
We don't want to log the entire consumer config into our server log.
It may contain sensitive data, like passwords.

(cherry picked from commit 2cd3e2b0995cedcec5efb807fcbd925a9262ea4c)

### CODE REVIEW

**Comment by mpfz0r** [comment]
Hello @jpdstan @yangzaizi

I'm planning to backport the Kafka client update to Graylog `4.0.6`

It would be fantastic if you could help us to test this update.
I've uploaded a snapshot build to

https://graylog2public.s3.amazonaws.com/mpf/graylog-4.0.6-SNAPSHOT-20210302131538.tgz

**Comment by jpdstan** [comment]
hey @mpfz0r, unfortunately upon upgrading from 3.x to 4.x we just realized there's a breaking change that we can't afford to have at the moment https://github.com/Graylog2/graylog2-server/issues/9938

is there a way to backport this update to Graylog 3.3? we would really appreciate this, as this fix is huge for us.

**Comment by mpfz0r** [comment]
Tested and works for me.

@jpdstan Sorry, I can't make any promises, but I'll look into finding a solution for #9938

**Review by thll — APPROVED** [review]
Looks good. Tested and didn't find any issues.

**Pull request merged**
