### PR TITLE
RestAccessLogFilter to use X-Forwarded-For set by trusted proxies

### PR DESCRIPTION
**Pull request by mikkolehtisalo**
Solves #1816 for the REST API audit logging.

- Introduces new configuration value trusted_proxies (comma separated list of IPs, and subnets)
- Adds RestTools method for RestAccessLogFilter, returning X-Forwarded-For value for logging, if the header was set by trusted proxy
-  As result the REST access log produces client addresses instead of load balancer's address

The same configuration value could be used also for the HTTP based input transports for similar logic, fixing faulty gl2_remote_ip, and similar. Also using the same configuration value for REMOTE_USER implementation could be possible.

### CODE REVIEW

**Comment by runningman84** [comment]
It would be really great if you would show the last used IP address in the user list.

**Comment by mikkolehtisalo** [comment]
@runningman84 Not a bad idea, but you can get that information by sending the rest access logs to this nice log management product called Graylog ;)

**Comment by runningman84** [comment]
@mikkolehtisalo Graylog does not help here because we need this information in order to identify which user overloads the elasticsearch / graylog cluster. At this time the normal search is most likely not working anymore...

**Comment by mikkolehtisalo** [comment]
Interesting use case. I am unsure where the state information should be stored...

**Comment by joschi** [comment]
Thanks a lot!

**Pull request merged**
