### PR TITLE
Upgrade Javascript dependencies

### PR DESCRIPTION
**Pull request by joschi**
This PR upgrades the primary Javascript dependencies to Node.js 4.3.0 LTS, npm 3.7.2, and frontend-maven-plugin 0.0.28.

### CODE REVIEW

**Comment by joschi** [comment]
The build currently fails on Travis CI but succeeds locally and on our Jenkins CI instance.

**Comment by dennisoelkers** [comment]
I think as long as it fails on Travis because of this change, it is of no value for us.

**Comment by joschi** [comment]
@dennisoelkers I agree, that's why I've removed the "ready-for-review" label.

It would be of value to use a still supported version of node.js but we'll need some spare time to find out why Travis CI won't build the native extensions in that version.

**Comment by dennisoelkers** [comment]
:+1:

**Comment by joschi** [comment]
Running the build on the Ubuntu 14.04 Trusty Tahr infrastructure seems to have fixed the issue with the ancient C++ compiler on the old Ubuntu 12.04 LTS containers. Unfortunately this is still in beta at Travis CI and takes a little bit longer until builds start.

**Pull request merged**
