### PR TITLE
OkHttp

### PR DESCRIPTION
**Pull request by joschi**
Replace various HTTP clients with [OkHttp](https://square.github.io/okhttp/).

Breaking changes:
* Individual timeout settings (like `versionchecks_connect_timeout`) are now consolidated into `http_connect_timeout`, `http_read_timeout`, and `http_write_timeout`.

Remarks:
* Replacing the Ning Async HTTP Client in graylog2-rest-client is another task.

### CODE REVIEW

**Comment by bernd** [comment]
I read through the diff but did not run any tests yet.

* How about using a `MediaType` for stuff like this? `.header(HttpHeaders.CONTENT_TYPE, "application/json")`
* I don't think that using the same http timeouts should apply for the internal cluster communication and external communication like `HttpPollTransport`, `HTTPAlarmCallback` and the `VersionCheckThread`.
* Removing the http options for the version check is a backwards incompatible change in my book. Also see comment regarding the same http timeouts for everything.

**Comment by bernd** [comment]
Any reason for having the OkHttp client as a singleton? Having to remember to call `#clone()` on the instance might lead to nasty bugs. :confused:

**Comment by bernd** [comment]
Another case where using the same settings for all clients might not work: If the `http_proxy_uri` is set, the internal cluster communication would use that, no?

**Comment by joschi** [comment]
> Removing the http options for the version check is a backwards incompatible change in my book. 

That's kind of the intention of this PR (consolidating timeout settings for "external" HTTP requests). In my opinion having individual timeout settings for every HTTP connection type (version checks, HTTP polling, HTTP alarm callback) doesn't make sense and is inconsistent as there is only 1 setting for using a proxy server with the connections.

> Any reason for having the OkHttp client as a singleton?

Not really and the potential errors with having to call `#clone()` for custom configuration is a good point. I'll change that.

> Another case where using the same settings for all clients might not work: If the http_proxy_uri is set, the internal cluster communication would use that, no?

That's right. Is there any case where "internal" cluster communication would require a proxy at all?

**Comment by bernd** [comment]
> That's right. Is there any case where "internal" cluster communication would require a proxy at all?

Probably not. I guess we can handle that if an issue pops up.

**Pull request merged**
