### PR TITLE
Include link to replay an alert in alert mail notification template.

### PR DESCRIPTION
**Pull request by linuspahl**
## Motivation and Context

With this PR we are including a "Alert Replay" link in the template for alert mail notifications.

Fixes https://github.com/Graylog2/graylog2-server/issues/15678

### CODE REVIEW

**Review by luk-kaminski — APPROVED** [review]
LGTM, thx!

**Comment by HenryTheSir** [comment]
hi @linuspahl ,

while building this manuel in current release, i observed that the wrong id field gets used in this PR.

In my opinion the event_definition_id needs to be set in the url and not event.id
And the URL seams to be wrong to? there needs to be an additional definitions after /alerts/ 
best regards

**Comment by linuspahl** [comment]
Hi @HenryTheSir!

just to be sure I understand you correctly. Did you build this functionality manually and are wondering why this PR implements the link differently or did the link this PR implements result in an error for you?

It looks like you are creating a link to replay the search for the event definition of an alert, while this PR implements a link to replay the alert (which also considers e.g. the aggregation time range of an alert). 

Best regards

**Comment by HenryTheSir** [comment]
My bad - sorry this function was completly unaware to me! 
You are right and URL and ID are corret in the url.

best regards

**Pull request merged**
