### PR TITLE
Refactor NodeId class and all usages

### PR DESCRIPTION
**Pull request by todvora**
The original NodeId class is doing too much - reading, geneating, persisting and providing node id. It makes sense to separate the persistence logic and the value itself. Additionally, NodeId is now ~~interface~~ abstract class (compatibility reasons), which is easy to use and provides clear communication and mocking options in tests. In the future 6.0 release, we should replace this abstract class with an interface, to fully separate the contract and the implementation.

## Motivation and Context
Code cleanup, separated responsibilities, better interfaces, removed many mocks in tests which increases readability.

## How Has This Been Tested?
Existing set of unit and integration tests, added unit test for the FilePersistedNodeIdProvider

/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#4470,Graylog2/graylog-plugin-integrations#1256,Graylog2/graylog-plugin-enterprise-integrations#957

/nocl

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by bernd — CHANGES_REQUESTED** [review]
Looking at all the changes, this seems to be a breaking Java API change. Will 3rd-party input, output, and notification plugins still work without adjustments? We have users and customers that write their own plugins.

If not, we either need to revert the breaking changes or wait until the next major release.

**Comment by todvora** [comment]
@bernd I think everything should be OK. The fully qualified class name is the same (it's interface now, instead of the actual implementation), the injections will work, the interface offers the same methods. Even the toString call still returns the node id. 

I will try to verify that code in this revision works fine with a plugin packaged before the change, just to be sure.

The only problem could be the missing constructor - clients won't be able to create a new instance of the NodeId directly. And the actual implementation is package-protected. Is that a problem? 

Do you see any other problems? 

Thanks!

**Comment by bernd** [comment]
> @bernd I think everything should be OK. The fully qualified class name is the same (it's interface now, instead of the actual implementation), the injections will work, the interface offers the same methods. Even the toString call still returns the node id.
> 
> I will try to verify that code in this revision works fine with a plugin packaged before the change, just to be sure.
> 
@todvora Thank you! :pray: 

> The only problem could be the missing constructor - clients won't be able to create a new instance of the NodeId directly. And the actual implementation is package-protected. Is that a problem?
>
That shouldn't be an issue. Regular plugin usage should only require injecting the `NodeId` and not creating a custom instance. Maybe in plugin unit tests, but those don't affect the runtime compatibility.

> Do you see any other problems?
> 
I was mostly worried about the `toString()` :arrow_right: `getNodeId()` change. But you took care of that. Thanks!

What do you think about pulling the `toString()` method into the interface to ensure that all future `NodeId` implementations return the node ID? The `toString()` method is part of the API contract, unfortunately.

**Comment by todvora** [comment]
> What do you think about pulling the toString() method into the interface to ensure that all future NodeId implementations return the node ID? The toString() method is part of the API contract, unfortunately.

I thought about it as well, but don't think it's technically possible. Java won't let us to define a default toString in the interface.

**Comment by bernd** [comment]
> > What do you think about pulling the toString() method into the interface to ensure that all future NodeId implementations return the node ID? The toString() method is part of the API contract, unfortunately.
> 
> I thought about it as well, but don't think it's technically possible. Java won't let us to define a default toString in the interface.

Ah damn, bummer. :smile: Thanks for checking!

**Comment by todvora** [comment]
I have tried to run this change against a plugin built for 5.0 release and it failed with following exception:

```
2022-12-19 16:19:22,966 INFO : org.graylog2.buffers.OutputBuffer - Initialized OutputBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
2022-12-19 16:19:23,457 ERROR: org.graylog2.bootstrap.CmdLineTool - Startup error:
java.lang.IncompatibleClassChangeError: Found interface org.graylog2.plugin.system.NodeId, but class was expected
	at org.graylog.plugins.auditlog.AuditLogger.doLog(AuditLogger.java:118) ~[?:?]
	at org.graylog.plugins.auditlog.AuditLogger.log(AuditLogger.java:77) ~[?:?]
	at org.graylog.plugins.auditlog.AuditLogger.success(AuditLogger.java:61) ~[?:?]
	at org.graylog2.audit.AuditEventSender.success(AuditEventSender.java:37) ~[graylog.jar:?]
	at org.graylog2.bootstrap.ServerBootstrap.startCommand(ServerBootstrap.java:219) ~[graylog.jar:?]
	at org.graylog2.bootstrap.CmdLineTool.doRun(CmdLineTool.java:324) ~[graylog.jar:?]
	at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:260) [graylog.jar:?]
	at org.graylog2.bootstrap.Main.main(Main.java:45) [graylog.jar:?]
Exception in thread "main" java.lang.IncompatibleClassChangeError: Found interface org.graylog2.plugin.system.NodeId, but class was expected
	at org.graylog.plugins.auditlog.AuditLogger.doLog(AuditLogger.java:118)
	at org.graylog.plugins.auditlog.AuditLogger.log(AuditLogger.java:77)
	at org.graylog.plugins.auditlog.AuditLogger.success(AuditLogger.java:61)
	at org.graylog2.audit.AuditEventSender.success(AuditEventSender.java:37)
	at org.graylog2.bootstrap.ServerBootstrap.startCommand(ServerBootstrap.java:219)
	at org.graylog2.bootstrap.CmdLineTool.doRun(CmdLineTool.java:324)
	at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:260)
	at org.graylog2.bootstrap.Main.main(Main.java:45)
```

The solution for now is to change the interface into an abstract class. Then it's indeed backwards compatible, preserves most of the refactoring benefits and will allow us to make the switch to clean interface in 6.0 release.

**Comment by bernd** [comment]
> I have tried to run this change against a plugin built for 5.0 release and it failed with following exception:
> 
> ```
> 2022-12-19 16:19:22,966 INFO : org.graylog2.buffers.OutputBuffer - Initialized OutputBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
> 2022-12-19 16:19:23,457 ERROR: org.graylog2.bootstrap.CmdLineTool - Startup error:
> java.lang.IncompatibleClassChangeError: Found interface org.graylog2.plugin.system.NodeId, but class was expected
> 	at org.graylog.plugins.auditlog.AuditLogger.doLog(AuditLogger.java:118) ~[?:?]
> 	at org.graylog.plugins.auditlog.AuditLogger.log(AuditLogger.java:77) ~[?:?]
> 	at org.graylog.plugins.auditlog.AuditLogger.success(AuditLogger.java:61) ~[?:?]
> 	at org.graylog2.audit.AuditEventSender.success(AuditEventSender.java:37) ~[graylog.jar:?]
> 	at org.graylog2.bootstrap.ServerBootstrap.startCommand(ServerBootstrap.java:219) ~[graylog.jar:?]
> 	at org.graylog2.bootstrap.CmdLineTool.doRun(CmdLineTool.java:324) ~[graylog.jar:?]
> 	at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:260) [graylog.jar:?]
> 	at org.graylog2.bootstrap.Main.main(Main.java:45) [graylog.jar:?]
> Exception in thread "main" java.lang.IncompatibleClassChangeError: Found interface org.graylog2.plugin.system.NodeId, but class was expected
> 	at org.graylog.plugins.auditlog.AuditLogger.doLog(AuditLogger.java:118)
> 	at org.graylog.plugins.auditlog.AuditLogger.log(AuditLogger.java:77)
> 	at org.graylog.plugins.auditlog.AuditLogger.success(AuditLogger.java:61)
> 	at org.graylog2.audit.AuditEventSender.success(AuditEventSender.java:37)
> 	at org.graylog2.bootstrap.ServerBootstrap.startCommand(ServerBootstrap.java:219)
> 	at org.graylog2.bootstrap.CmdLineTool.doRun(CmdLineTool.java:324)
> 	at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:260)
> 	at org.graylog2.bootstrap.Main.main(Main.java:45)
> ```
> 
> The solution for now is to change the interface into an abstract class. Then it's indeed backwards compatible, preserves most of the refactoring benefits and will allow us to make the switch to clean interface in 6.0 release.

@todvora Thank you for testing! :pray:

**Review by bernd — APPROVED** [review]
Looks good to me now from a compatibility perspective. I didn't thoroughly review and test the changes, though.

**Pull request merged**
