### PR TITLE
Fix pagination problems on Events page

### PR DESCRIPTION
**Pull request by gally47**
## Motivation and Context

fixes https://github.com/Graylog2/graylog2-server/issues/15273

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by gally47** [comment]
> I couldn't test it much as for the events & alerts page only shows the loading state: Screenshot 2023-04-27 at 12 54 06
> 
> Do I need another branch for it to work?

No other branch needed, just tested it again and for me it works fine.
Screenshot 2023-04-28 at 14 31 33

**Comment by gally47** [comment]
> I finally managed to get it set up!
> 
> For me the bugs are not fixed though, here are my test results:
> 
> ❌ Alerts & Events list still shows a lot of pages Screenshot 2023-05-02 at 16 30 36
> 
> ❌ When clicking on the button for the last page it shows a page with no entries ❌ When clicking on the last page itself it shows a page with no entries ❌ When navigating to the last page via url it shows a page with no entries ❌ The pages before the last page show no entries Screenshot 2023-05-02 at 16 38 04
> 
> ✅ URL navigation for existing pages works ✅ Navigation through the pagination at the bottom works in general ✅ Page size can be changed

- Showing a lot of pages is not a problem that is related to the number of events.
- For all the other points, those only happen when `currentPage * currentPageSize > 10000` I don't know why but that's how it is set in the backend.

**Comment by moesterheld** [comment]
> * For all the other points, those only happen when `currentPage * currentPageSize > 10000` I don't know why but that's how it is set in the backend. Maybe @moesterheld can help?

The 10.000 record limit is a limitation coming from ElasticSearch. See also #3571 . The correct way to fix this would be to change to another Elastic API, which is currently not planned. Maybe we should handle this as an error in the UI? If the response should be changed when running into this situation, let me know

**Comment by gally47** [comment]
Screenshot 2023-05-05 at 16 41 06

**Comment by moesterheld** [comment]
works as expected from a user's perspective

**Review by grotlue — APPROVED** [review]
Looks good! Thank you!

**Pull request merged**
