### PR TITLE
Dynamic search results update

### PR DESCRIPTION
**Pull request by dennisoelkers**
* Updating search results, histogram and field charts periodically.
* Add controls to pause/resume updates or change interval.
* Pause updates when a message is expanded.

### CODE REVIEW

**Comment by bernd** [comment]
Refs Graylog2/graylog2-web-interface#133

**Comment by edmundoa** [comment]
I took the liberty of making some changes on the way of refreshing the search histogram data. I will take a look at the issues with field graphs tomorrow.

**Comment by edmundoa** [comment]
@dennisoelkers I committed the changes we did together this morning, and continued making the auto-refresh only update the field graphs data. Feel free to merge if you see no issues with those changes :+1:

**Comment by lennartkoopmann** [comment]
Thanks!! :)

What was the reason to only update field graphs and not the histogram etc?

**Comment by edmundoa** [comment]
We update everything, on my last comment I meant that we refresh the field graphs data instead of re-rendering them completely. We also do that in the search histogram btw :)

**Comment by lennartkoopmann** [comment]
Yippie! :)

**Pull request merged**
