### PR TITLE
Upgrade to moment 2.14.1

### PR DESCRIPTION
**Pull request by joschi**
Security vulnerability: https://nodesecurity.io/advisories/55

### CODE REVIEW

**Comment by kroepke** [comment]
Does this apply to our plugins as well?

**Comment by joschi** [comment]
> Does this apply to our plugins as well?

If they are bundling their own version of `moment`, they are affected as well.

**Comment by edmundoa** [comment]
At least some of them do, not remember exactly which ones, though.

**Comment by edmundoa** [comment]
LGTM 👍

**Pull request merged**
