### PR TITLE
Use rate-limited logging in pipeline processor

### PR DESCRIPTION
**Pull request by patrickmann**
The pipeline processor may generate an excessive number of log messages since it runs on every message.
Introduce rate-limited logging to mitigate this.
See #14555 for details.

/nocl

### CODE REVIEW

**Review by kodjo-anipah — COMMENTED** [review]
Its working but other logs would still end up polluting the logs I guess we should extend the scope 
image

**Comment by patrickmann** [comment]
>I guess we should extend the scope

I considered that, but it's a pretty open-ended thing. Maybe we do it as needed?

**Comment by kodjo-anipah** [comment]
> > I guess we should extend the scope
> 
> I considered that, but it's a pretty open-ended thing. Maybe we do it as needed?

Makes sense, can you resolve the conflict?

**Review by kodjo-anipah — APPROVED** [review]
LGTM

**Pull request merged**
