### PR TITLE
fix: rerender multi select when value changes

### PR DESCRIPTION
**Pull request by Gaya**
## Description

When clearing values from the `<Select />` component the inner state would not update to the newly provided value(s) when they were passed as a prop in a "controlled" manner.

## Motivation and Context

It makes sure the `<Select />` rerenders on value change. It might not be the most ideal way of solving it, but while digging deeper into the component and `react-select` itself it was hard to spot where it went wrong.

I believe it had something to do with `react-select`'s `StateManager`, since it didn't update its value to the passed prop.

The solution is to add a `key` prop based on the value so `react-select` forces a rerender.

Fixes: https://github.com/Graylog2/graylog2-server/issues/12265
Fixes: https://github.com/Graylog2/graylog2-server/issues/12259

## How Has This Been Tested?

Manually in the browser

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by dennisoelkers — COMMENTED** [review]
This fixes the issue of the state of the select not being updated. The downside of this is though, that upon every rerender, the select is blurred. This prevents users from being able to enter multiple values in one go, because the input is not focussed anymore after selecting an option.

**Review by linuspahl — CHANGES_REQUESTED** [review]
In my opinion using the `key` attribute to solve this problem is a little bit extreme. This way the `react-select` component and its child components will remount.

It also has some other (related) disadvantages, like the select loosing the focus when changing its value:
select

It looks like another solution could be to ensure the `value` we provide for the `react-select` is never `undefined`: `value: formattedValue ?? '',`

**Comment by Gaya** [comment]
Good points! Going to look into again.

**Comment by Gaya** [comment]
@dennisoelkers @linuspahl forgot to mention I comitted a new fix

**Comment by Gaya** [comment]
Closing in favour of https://github.com/Graylog2/graylog2-server/pull/12297

**Pull request closed without merging**
