### PR TITLE
Array Contains function: Fix unhandled exception when passed null array

### PR DESCRIPTION
**Pull request by danotorrey**
## Description

When the `array_contains` pipeline function was passed a null array (for example through selecting a non-existent path through `json_path`), the function would internally throw an exception and return null. This fix resolves that, and correctly returns `false` since a null array cannot contain an values.

## Motivation and Context

Needed for Illuminate processing content. 

## How Has This Been Tested?

Well-covered with unit tests.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by kingzacko1** [comment]
Handling a null array looks good. Does the function already handle the scenario where the string to check might be null? I thought Michael said either case should return false. @danotorrey

**Comment by ryan-carroll-graylog** [comment]
Null array looks good on my end too. Also lean toward handling null lookup values since that's the behavior of other functions (e.g. `LookupHasValue`).

`ArrayContains` already looks like it's ok with null values in most circumstances, with the exception being arrays with `IntNode`/`LongNode` values where we call `value.equals(number.intValue()`.

**Comment by danotorrey** [comment]
Thanks for the feedback. I added some handling just in case one of the JSON elements is null, and also improved the test coverage of null values. Looks like the function is handling the standard null value fine, but good to have some test coverage of that now.

**Review by ryan-carroll-graylog — APPROVED** [review]
Looks good and tests successfully with the latest!

**Review by kingzacko1 — APPROVED** [review]
LGTM!

**Pull request merged**
