### PR TITLE
Link to input in message details

### LINKED ISSUE #2829: Link to input in message detail's "Received by" content
## Expected Behavior

When viewing a message's details it should be possible to click a link to navigate to the input, [as is possible](https://github.com/Graylog2/graylog2-server/blob/d9de77674e4a8d795f93628f46e5cbf6c5cb585e/graylog2-web-interface/src/components/search/MessageDetail.jsx#L69) with the receiving node.  Since `/system/inputs` is currently just a big list, perhaps the link would be to `/system/inputs#someInputId`.
## Current Behavior

Navigating from a message to its receiving input (perhaps to view extractors, etc.) involves several steps.
## Context

It's common for me to want to check some piece of input configuration after viewing a message.
### Environment
- Graylog Version: 2.0.3
- Elasticsearch Version:  2.2.0
- MongoDB Version:  2.6.12
- Operating System:  Red Hat Enterprise Linux Server release 6.7
- Browser version:  Firefox 48

### PR DESCRIPTION
**Pull request by supahgreg**
This PR makes the Input name in the `Received by` section of message details a link to the Input on the Inputs page (if the Input still exists).

## Description

This PR introduces aupport for linking and jumping (once) directly to an `EntityListItem` within an `EntityList`,  and then uses that to link to an input from the `Received by` section of message details.

The ReviewBot items are unrelated to the changes in this PR, so I've skipped addressing them (for now).

## Motivation and Context

Currently the details section links to the receiving node, but not the corresponding input.  Being able to directly jump from a message to the related input on the Inputs page eliminates several manual steps.

Closes #2829. 

## How Has This Been Tested?

Verified I can click the message details input name/link and get to the corresponding input on the Inputs page.

## Screenshots (if appropriate):
image
image

image
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by dennisoelkers** [comment]
@supahgreg: Thanks a lot for this PR! What do you think of opening a dropdown when clicking on the input name instead, which offers a couple of options, e.g. including/excluding this input from the search, or jumping to the inputs page (as implemented in your PR)?

**Comment by supahgreg** [comment]
@dennisoelkers  Sure, I'll look into that.

**Comment by dennisoelkers** [comment]
@supahgreg: We can also take it from here, if you do not have the time for it.

**Comment by supahgreg** [comment]
I should have time.  Seems interesting :)

**Pull request closed without merging**
