### PR TITLE
Add default param to set_field function

### LINKED ISSUE #5911: Pipeline rule with geo lookup and possible empty array
I am trying to setup a pipeline rule to get some additional geo information, as described in http://docs.graylog.org/en/3.0/pages/geolocation.html#.
The problem I am facing is that part of the result of the lookup can be empty.
In the below code for the rule setting the country code works fine, but the fields which depend on the subdivisions object can lead to the error

"For rule 'rule geoip lookup': In call to function 'set_field' at 7:2 an exception was thrown: Index: 0, Size: 0".

This happens because the subdivisions object is sometimes empty, for instance:

```
...
"country": {
  "confidence": null,
  "geoname_id": 1605651,
  "is_in_european_union": false,
  "iso_code": "TH",
  "names": {
    "de": "Thailand",
    "ru": "Тайланд",
    "pt-BR": "Tailândia",
    "ja": "タイ王国",
    "en": "Thailand",
    "fr": "Thaïlande",
    "zh-CN": "泰国",
    "es": "Tailandia"
  }
},
...
"subdivisions": []
```

Code for the rule:

```
rule "rule geoip subdivision lookup"
when
  has_field("IP")
then
  let geo = lookup("geoip-lookup", to_string($message.IP));

  set_field("IP_country_code", geo["country"].iso_code);
  set_field("IP_region_code", geo["subdivisions"].[0].iso_code);
  set_field("IP_region_name", geo["subdivisions"].[0].names.en);
end
```

Currently it seems not to be possible to only set the fiels IP_region_code and IP_region_name, when the array is not empty - or to use a default value, if the array is empty.

(Also posted in https://community.graylog.org/t/pipeline-rule-with-geo-lookup-and-possible-empty-array/10013)

### PR DESCRIPTION
**Pull request by patrickmann**
Extends parameter list of `set_field` by an optional default parameter. The default can be specified as a positional parameter (5th parameter value) or named as `default`. 
The default is assigned if 
- the primary value is null
- evaluation of the primary value throws an exception. In this case (provided the default is valid), the exception is suppressed. This is desired so we can specify a default when an array value is not present, resulting in _index out of bounds_ exception.

## Description

The default parameter value is assigned whenever the value parameter is null; or when an exception is encountered in evaluating the value parameter. 

## Motivation and Context

See linked issue for details

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

Resolves #5911

### CODE REVIEW

**Review by kodjo-anipah — APPROVED** [review]
tested locally, LGTM

**Comment by boosty** [comment]
@patrickmann @kodjo-anipah Thanks for working on this! 

Could you please backport this to 4.3?

**Comment by patrickmann** [comment]
I can take care of the backport

**Comment by gustavohellwig** [comment]
Hi. For me, the issue is still happening. 
`Error: In call to function 'to_string' at 11:37 an exception was thrown: Index 0 out of bounds for length 0)
`
my config are:

**Pull request merged**
