### PR TITLE
Log failure warning message even if input is already in Failing status

### PR DESCRIPTION
**Pull request by danotorrey**
## Description

Change InputFailureRecorder to log failure warning each time an input triggers a failing condition. 

/nocl Seems not noteworthy enough to mention in the top-level change log.

## Motivation and Context

Many inputs include retry logic, which pauses the input until the certain error conditions resolve (such as the remote host being unavailable). The retries occur indefinitely in many cases. Indeed, the input continues to mark the input as Failing, which shows up in the user interface. But, it would also be helpful to continue to log that reties are occurring in the server log, so there is a very clear indication in the log that an input continuing to fail (the absence of such messages seem to indicate that the input is working successfully).

## How Has This Been Tested?

Ran an input with an unreachable server host name and verified that the following log is repeatedly logged, even if the input is already failing.

```
2024-02-02 09:55:38,406 WARN : org.graylog.enterprise.integrations.services.RetrofitHTTPCall$1 - API request threw exception [Connect timed out.] on attempt [31].
java.net.SocketTimeoutException: Connect timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546) ~[?:?]
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[?:?]
```

## Types of changes

- [ ] Logging adjustment
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by kingzacko1 — APPROVED** [review]
Makes sense and LGTM.

**Comment by danotorrey** [comment]
@mpfz0r I will go ahead and merge this PR now, but let me know if you see any issues with it, and I can revise.

**Comment by mpfz0r** [comment]
> @mpfz0r I will go ahead and merge this PR now, but let me know if you see any issues with it, and I can revise.

@danotorrey  Ah sorry for the late feedback.
I did this on purpose back then to reduce the amount of logs. 
The last message states that the Input is broken. So I didn't see a reason why we need to repeat that log message contentiously.
But it's not a big deal. Our server log is super chatty already, I guess it's a lost cause.

**Comment by danotorrey** [comment]
@mpfz0r Thanks for the feedback, and I agree that we do want to try to keep verbosity out of the server log when possible.  The main use case I am thinking of here is when the support team is working to investigate input failures. There are times when inputs fall into longer retry loops when the remote side is unavailable. It's helpful to know how long those situations are happening for, and I don't think we can quite tell from the system notification. My thinking is, if an input is failing, it's probably worth complaining loudly about it in the server log with each retry, since it's a condition that the user would want to address, and that also makes it easier to see in the log when troubleshooting with Support.

Another option could be to introduce an optional parameter boolean `logIfAlreadyFailing`, which could be used in the retry case. What do you think?

**Comment by mpfz0r** [comment]
> It's helpful to know how long those situations are happening for, and I don't think we can quite tell from the system notification

Wouldn't we create a log message when it starts working again?

> it's probably worth complaining loudly about it in the server log with each retry, since it's a condition that the user would want to address

I have the impression that a lot of users don't monitor the server log.
That's why we have the system notifications.

I agree that it helps for troubleshooting. Could we make it a debug log then?
That could at least be changed at runtime, the config parameter would need a server restart.

**Comment by danotorrey** [comment]
> Wouldn't we create a log message when it starts working again?

@mpfz0r That is a good point. I think that is actually already sufficient to address the need from a support perspective when looking at the log. With the start and end of when an input issue was happening, and any in between retry log messages do not really matter. We can always turn on debug logging for an input to get more detailed info about retries or internal working.

Thanks for the feedback and talking it through @mpfz0r. I will add a PR to roll-back the change.

**Comment by danotorrey** [comment]
@mpfz0r It looks like we are not currently logging when an input enters the running state again. Perhaps that is where my main concern was from. An error is logged when an input enters the failing state, but there is no log when it again resumes. I think capturing both in the log would be helpful, but I still agree that intermediate failure messages are not needed.

If it makes sense to you, I could add that log statement here: https://github.com/Graylog2/graylog2-server/blob/c97aca5075442966fd9658360e593538b868ed54/graylog2-server/src/main/java/org/graylog2/plugin/InputFailureRecorder.java#L73

**Comment by mpfz0r** [comment]
> It looks like we are not currently logging when an input enters the running state again
My bad. I assumed that was the case.

I like your suggestion. we would need to pass the Class to `setRunning()` though.

**Comment by danotorrey** [comment]
> t looks like we are not currently logging when an input enters the running state again. Perhaps that is where my main concern was from. An error is logged when an input enters the failing state, but there is no log when it again resumes. I think capturing both in the log would be helpful, but I still agree that intermediate failure messages are not needed.
> 
> If it makes sense to you, I could add that log statement here:

@mpfz0r Please ignore my last comment. After testing, do indeed log a message once the input transitions back to running:

> Input [My Input/65bad5e340ad3d2c823742a6] is now RUNNING

I'll roll-back the logging change in a new PR.

**Comment by danotorrey** [comment]
PR filed to revert the logging change: https://github.com/Graylog2/graylog2-server/pull/18186

Thanks again for the feedback @mpfz0r.

**Pull request merged**
