### PR TITLE
Backport add geoipdb refresh

### PR DESCRIPTION
**Pull request by roberto-graylog**
## Description

Backport of #13106 
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by ryan-carroll-graylog — APPROVED** [review]
Looks good! Retested on 4.3 updating the Geo-Location Processor config as well as updating the database files and all works as expected.

**Comment by danotorrey** [comment]
This backport LGTM 👍

As discussed, there is one outstanding issue where GeoIP files are still monitored when GeoLocation is not enabled (and throw errors when files are not present). @roberto-graylog Do you want to include that fix in this same backport PR?

**Comment by roberto-graylog** [comment]
> Looks good! Retested on 4.3 updating the Geo-Location Processor config as well as updating the database files and all works as expected.

Sorry Ryan, I will have to make a quick change to this.  I am testing right now.

**Comment by ryan-carroll-graylog** [comment]
> > Looks good! Retested on 4.3 updating the Geo-Location Processor config as well as updating the database files and all works as expected.
> 
> Sorry Ryan, I will have to make a quick change to this. I am testing right now.

No worries. I hadn't seen @danotorrey 's catch in the chat so I'll wait for the updates. I've got my 4.3 VM set up to re-test when they come in.

**Review by danotorrey — APPROVED** [review]
LGTM and tests successfully. I think this can be merged once the additional fix in https://github.com/Graylog2/graylog2-server/pull/13144 is pushed up to this PR.

@roberto-graylog

**Review by danotorrey — APPROVED** [review]
The new commit added LGTM! Ready for merging as far as I can see.

**Review by kingzacko1 — APPROVED** [review]
LGTM

**Pull request merged**
