### PR TITLE
Separate REST routes generator

### PR DESCRIPTION
**Pull request by joschi**
This change set moves the generation step for our REST routes for graylog2-rest-client into graylog2-rest-client itself. The graylog2-rest-routes submodule now simply consists of the generator code and is used as a compile-time dependency in graylog2-rest-client (during Maven's `generate-sources` phase) instead of a compile- and runtime dependency.

### CODE REVIEW

**Comment by kroepke** [comment]
My only problem is that I cannot get Intellij to regenerate the resources on "make". Generate sources and update folders does not work either.

I wonder why that works with AutoValues on make, what do they do differently?

**Comment by kroepke** [comment]
I see, the autovalue stuff is an annotation processor which are getting executed on make.

So if ResourceRoutesParser was an AnnotationProcessor (which it really should be anyway because it processes annotations), then everything would work.

Given the ongoing discussion maybe we should postpone this?

**Comment by joschi** [comment]
One problem with the annotation processor is that this would've to happen in each sub-project containing JAX-RS resource classes because it only works on source files (but not on already compiled dependencies like it is now).

**Comment by joschi** [comment]
The problem with IntelliJ IDEA being unable to generate sources is strange. I also can't get it to work but running `mvn generate-sources` in the graylog2-rest-client sub-project is working as intended.

**Comment by kroepke** [comment]
So apparently this wasn't working before anyway (with Intellij) so we should just go ahead with this change to fix the build.

feel free to merge :+1:

**Pull request merged**
