### PR TITLE
Better logging of message keys ignored during indexing

### PR DESCRIPTION
**Pull request by luk-kaminski**
## Description
Better logging of message keys ignored during indexing.

## Motivation and Context
Related to #12990. If we drop from the message some fields that do not have proper field names, we should at least inform about it in the logs, instead of doing it silently.

## How Has This Been Tested?
Manually.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by bernd — COMMENTED** [review]
This is a user-visible behavior change, so it needs a changelog entry.

**Review by patrickmann — COMMENTED** [review]
Looks good. Since we are touching this file, here's another small improvement we could include:
Message.java (508,66) and (508,88): _Replace this call to "replaceAll()" by a call to the "replace()" method._

> The underlying implementation of String::replaceAll calls the java.util.regex.Pattern.compile() method each time it is called even if the first argument is not a regular expression. This has a significant performance cost and therefore should be used with care.
> When String::replaceAll is used, the first argument should be a real regular expression. If it’s not the case, String::replace does exactly the same thing as String::replaceAll without the performance drawback of the regex.

**Review by mpfz0r — APPROVED** [review]
LGTM :+1:

**Comment by mpfz0r** [comment]
> Looks good and works as expected: log msg shows up and is rate-limited correctly.
> 
> Since we are touching this file, here's another small improvement we could include: Message.java (508,66) and (508,88): _Replace this call to "replaceAll()" by a call to the "replace()" method._

@patrickmann 
Makes sense, but this is within `Message#toString()` and thus only called for debugging. 
Let's do this in a separate PR.

**Pull request merged**
