### PR TITLE
TCP Transport added Support for SSL Client Authentication

### PR DESCRIPTION
**Pull request by gbu-censhare**
The promised new pull request Including TestCases,

Only Supported Key Format is PKCS8, to Provide a Parser vor PKCS1 one should include BountyCastle Crypto Extensions. 

"Please use Guava's Joiner instead of implementing this yourself."  -> Guava's Joiner doesn't support Enumerations.

Best, Georg

### CODE REVIEW

**Comment by gbu-censhare** [comment]
just merged your changes is, my local build is still working.

**Comment by joschi** [comment]
@gbu-censhare In this case the build is failing because the source files you've added don't have the expected license header. Just run `mvn license:format` and they'll be added automatically.

**Comment by gbu-censhare** [comment]
ah, thanks, license header added :)

**Comment by bernd** [comment]
Closing this in favor of #1363. Thank you very much!

**Comment by gbu-censhare** [comment]
Thanks, my pleasure :+1:

**Pull request closed without merging**
