### PR TITLE
Store Message receive and processing times

### LINKED ISSUE #16284: Store message receive and processing times in OS / ES
With #6022 we've started recording per-message receive and processing timestamps.
We didn't add those timestamps as message fields, because we wanted to make sure every index
has the new mapping for those fields.

We can finally add those fields for the 5.2 release

See
https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/plugin/Message.java#L136-L146

and 
https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/plugin/Message.java#L878

### PR DESCRIPTION
**Pull request by mpfz0r**
With #6022 we've started recording per-message receive and processing timestamps. 
We didn't add those timestamps as message fields, because we wanted to make sure every index 
has a proper datetime format mapping for those fields.

With a bit of delay :smirk: we can finally store those fields on each Message.

Fixes #16284

Refs #16163

Forwarder support: https://github.com/Graylog2/graylog-plugin-enterprise/pull/6560

### CODE REVIEW

**Comment by mpfz0r** [comment]
@Graylog2/architecture 

I'm wondering if the timestamp fields are actually that useful.
Wouldn't it be better to just store the processing duration instead?
See
https://github.com/Graylog2/graylog2-server/pull/18150/commits/e02943ff7c57343801cb8ac1b7626099fe9ed51b

**Comment by bernd** [comment]
> @Graylog2/architecture
> 
> I'm wondering if the timestamp fields are actually that useful. Wouldn't it be better to just store the processing duration instead? See [e02943f](https://github.com/Graylog2/graylog2-server/commit/e02943ff7c57343801cb8ac1b7626099fe9ed51b)

@mpfz0r I think the timestamp fields have their use cases. I agree that the duration is better for dashboards since we can't compute any values in our queries, AFAIK.

We can store the duration as well. Let's call it `gl2_processing_duration_ms` though.

The new field needs to be added to our index templates. If we don't want to wait again until everyone has the field, we need a migration step that adds the field to all active write indices.

**Comment by mpfz0r** [comment]
> > @Graylog2/architecture
> > I'm wondering if the timestamp fields are actually that useful. Wouldn't it be better to just store the processing duration instead? See [e02943f](https://github.com/Graylog2/graylog2-server/commit/e02943ff7c57343801cb8ac1b7626099fe9ed51b)
> 
> @mpfz0r I think the timestamp fields have their use cases. I agree that the duration is better for dashboards since we can't compute any values in our queries, AFAIK.

Doing that on the fly would involve a painless scripted query, not ideal, no.

> We can store the duration as well. Let's call it `gl2_processing_duration_ms` though.

Ack :+1: 
 
> The new field needs to be added to our index templates. If we don't want to wait again until everyone has the field, we need a migration step that adds the field to all active write indices.

Is that necessary? The field will automatically be detected as a numerical value.

**Review by kodjo-anipah — APPROVED** [review]
LGTM processing time, processing duration & receiving time are all there

**Pull request merged**
