### PR TITLE
Suppress unneeded Azure error logging

### PR DESCRIPTION
**Pull request by danotorrey**
## Description

Suppress additional Azure SDK error logs.

Additional PRs will be needed in the following repositories where we maintain additional copies of the log4j config for different build targets. I will file those once review on this first PR is complete.
https://github.com/Graylog2/fpm-recipes/blob/5.0/recipes/graylog-server/files/log4j2.xml
https://github.com/Graylog2/graylog-docker/blob/5.0/config/log4j2.xml

/nocl
## Motivation and Context

 
See https://github.com/Graylog2/graylog-plugin-enterprise-integrations/pull/1033 for additional details and motivation.

## How Has This Been Tested?

Manual testing to ensure the expected logs are now suppressed. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by danotorrey** [comment]
Thanks for testing that out @ryan-carroll-graylog! Ahh yes, I think we can silence that one too. Just pushed it up.

**Review by ryan-carroll-graylog — APPROVED** [review]
Looks good and no longer seeing extraneous error messages in the logs.

**Comment by danotorrey** [comment]
@thll Just wanted to check-in with you before merging this. Do you see any issues with this error suppression? Once it is merged, it would need to be integrated into https://github.com/Graylog2/graylog-plugin-enterprise-integrations/pull/1030.

**Comment by thll** [comment]
> @thll Just wanted to check-in with you before merging this. Do you see any issues with this error suppression? Once it is merged, it would need to be integrated into [Graylog2/graylog-plugin-enterprise-integrations#1030](https://github.com/Graylog2/graylog-plugin-enterprise-integrations/pull/1030).

@danotorrey If we are sure that we can safely ignore **all** log messages from these loggers, then it's probably OK.

Is there any reason you are setting the log level to `fatal`? I think the azure libs are logging with slf4j, which afaik doesn't have a `fatal` log level. So to make it more obvious that we are essentially switching off logging entirely, we could also set the logging level to `off`.

**Comment by danotorrey** [comment]
@thll Apologies, the main PR is https://github.com/Graylog2/graylog-plugin-enterprise-integrations/pull/1033, and I meant to start the discussion there. I will continue the discussion there, since there are some relevant details in that PR.

**Comment by danotorrey** [comment]
@thll @ryan-carroll-graylog The loggers have been set to `off`. This still tests successfully for me: 

```
2023-03-17 08:13:06,972 INFO : org.graylog.enterprise.integrations.azure.external.AzureLogsProcessor - Input [[Azure Event Hubs/lklkh/64145b120e6287129c4ff57e]] is now receiving on partition [0].
2023-03-17 08:14:22,036 INFO : org.graylog.enterprise.integrations.azure.external.AzureLogsProcessor - Input [[Azure Event Hubs/lklkh/64145b120e6287129c4ff57e]] lost ownership of partition [0]. The partition ownership was likely taken by another Graylog node to help balance the receiving load.
2023-03-17 08:14:22,041 INFO : org.graylog.enterprise.integrations.azure.external.AzureLogsProcessor - Input [[Azure Event Hubs/lklkh/64145b120e6287129c4ff57e]] has stopped receiving on partition [0].

```

**Comment by danotorrey** [comment]
I filed these two additional PRs for docker images and OS packages. We maintain a separate default `log4j2.xml` for those targets as well. 
https://github.com/Graylog2/graylog-docker/pull/245
https://github.com/Graylog2/fpm-recipes/pull/124

**Review by ryan-carroll-graylog — APPROVED** [review]

**Pull request merged**
