### PR TITLE
Simplify pivot aggregation search in events

### PR DESCRIPTION
**Pull request by todvora**
/nocl

## Description
This ~~tiny~~ change simplifies significantly the request-response structure of the aggregation. This then avoids many possible parsing errors of the aggregations structure.

## Motivation and Context
Fixes https://github.com/Graylog2/graylog2-server/issues/17314

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by patrickmann** [comment]
Fixes most of the exceptions with missing fields. 
But if only non-existent fields are specified as group-by, we still see exceptions in `EventProcessorExecutionJob`. No events are generated.
A corner case, but _replay search_ shows correct event counts, even for this case.

**Review by patrickmann — COMMENTED** [review]
Can't handle only missing group-by fields

**Comment by todvora** [comment]
Thanks @patrickmann for the review, I'll look at this specific case as well. Adding full integration tests now, so it will be easier to verify such behavior.

**Comment by todvora** [comment]
I can reproduce the problem with all-unknown fields error in an integration test now, continue on a fix.

**Review by dennisoelkers — APPROVED** [review]

**Pull request merged**
