### PR TITLE
Fix index count on IndexSetPage

### LINKED ISSUE #11375: Graylog 4.1 showing wrong indices number under management
Graylog 4.1 is showing wrong indices number under management in the UI 
## Expected Behavior

The number of indices under graylog management should be equal to the number of indexes.
## Current Behavior

The current version of graylog 4-1 is showing only 4 number of indices under management by default.   

## Possible Solution

The indices under management should be equal to the number of indexes

> management number should be equal to the number of indexes. 

## Steps to Reproduce (for bugs)

1. Update Graylog 3.1 to 4.1 version with 6.8.18 elastic [version]([url](url))
2. 
3.
4.

## Context

Graylog is not showing up data from some of the indices 

> ``

## Your Environment

* Graylog Version:
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

### PR DESCRIPTION
**Pull request by supahgreg**
Fixes the index count on `IndexSetPage`.

## Description

Previously, `_totalIndexCount` was counting the keys of the `indexerOverview` response (introduced w/ #10401; [specifically this](https://github.com/Graylog2/graylog2-server/pull/10401/files#diff-e80e8ae830a0552545b2659d7a199aa7274ac4ffa50f68a7f0d2c822a99133d2R110-R114)), rather than the response's `indices` key.  This PR updates that function so it counts the right thing.

## Motivation and Context

Fixes #11375.

## How Has This Been Tested?

It hasn't been tested.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by dennisoelkers — CHANGES_REQUESTED** [review]
Good catch! Looks good and works. Can you run `yarn lint:changes --fix` and commit the resulting diff? The spacing is off in your change.

**Comment by supahgreg** [comment]
Oops, sorry about that.  I've ran `yarn lint:changes --fix` and corrected the related errors.

**Review by dennisoelkers — APPROVED** [review]
Thanks a lot, @supahgreg! Good work!

**Comment by dennisoelkers** [comment]
@supahgreg: If you are interested in a little thank you from our side, feel free to drop me your details in a short email!

**Pull request merged**
