### PR TITLE
Return remediation steps with events

### PR DESCRIPTION
**Pull request by ryan-carroll-graylog**
## Description

Adds remediation steps to general events details view.

## Motivation and Context

Closes: https://github.com/Graylog2/graylog2-server/issues/19354

## How Has This Been Tested?

Locally in dev environment.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ryan-carroll-graylog** [comment]
@zeeklop took a look at https://github.com/Graylog2/graylog2-server/issues/19354#issuecomment-2214933456 and it seemed like the path of least resistance was to just add a nullable `remediation_steps` to the event context. Let me know if y'all see any issues with this and if not I'll go ahead and move forward with this approach.
/cc @kingzacko1 @danotorrey

**Comment by zeeklop** [comment]
Thank you @ryan-carroll-graylog I'm taking a look now. Should I add the front-end changes to this branch?

**Comment by ryan-carroll-graylog** [comment]
> Thank you @ryan-carroll-graylog I'm taking a look now. Should I add the front-end changes to this branch?

No problem @zeeklop, yeah I think adding everything to this branch makes sense while we work out the details. I don't think it'll be a big changeset.

**Review by zeeklop — APPROVED** [review]
Looks good! Thank you Ryan. Tested successfully.

**Review by kingzacko1 — APPROVED** [review]
LGTM!

**Pull request merged**
