### PR TITLE
Add GELF AMQP input

### PR DESCRIPTION
**Pull request by bernd**
The current `AMQPInput` is not really useful because it uses the `RadioMessageCodec`. It would be more useful to have a GELF AMQP input which reads GELF messages off an AMQP broker.

* Let `RadioAMQPInput` inherit from `MessageInput` instead of `AMQPInput`.
* Replace `AMQPInput` with `GELFAMQPInput`.
* Fix a typo spotted along the way.

Any objections?

### CODE REVIEW

**Comment by joschi** [comment]
:+1: LGTM.

**Comment by kroepke** [comment]
Only thing I see is that renaming an input will lead to warnings if anyone
has already used it because the class name won't be valid anymore.
Other than that I'm good with it.
Maybe just a doc problem?

**Comment by joschi** [comment]
The change should be documented.

In general we might want to think about a migration mechanism for inputs (or any entity that relies on a certain FQCN). Maybe a simple `Map<String, String>` in the right place is sufficient or we add a unique identifier to our entities (so that they are found and instantiated by a fixed string instead of the FQCN).

**Comment by bernd** [comment]
Using "rename" here was a bit misleading. It is basically a new input. The current `AMQPInput` is in fact a Radio AMQP input with other default values for the configuration.

And yes, that should be documented because it is a breaking change. Thanks for the review!

**Comment by lennartkoopmann** [comment]
Nice stuff, people waited for this. Thanks. :)

**Comment by henrikjohansen** [comment]
<3 !!!

**Pull request merged**
