### PR TITLE
Backport: Add support for more verbose authentication failure

### PR DESCRIPTION
**Pull request by danotorrey**
Backport PR #8136 to `cloud-3.3`, so that plugins that depend on it will work.

Please merge https://github.com/Graylog2/graylog-project-internal/pull/28 before merging this PR.

### CODE REVIEW

**Comment by danotorrey** [comment]
> What are all those version bumps in the `pom.xml` files about? This doesn't look correct.

@thll Thanks for seeing that. Not sure why the commit for the bump of the poms was included. I dropped that commit from this branch.

**Comment by juju2112** [comment]
@danotorrey I'm seeing this error in the build:

```
[2020-05-28T21:17:53.341Z] [ERROR] Failed to execute goal on project graylog-plugin-collector: Could not resolve dependencies for project org.graylog.plugins:graylog-plugin-collector:jar:4.0.0-SNAPSHOT: Could not find artifact org.graylog2:graylog2-server:jar:tests:4.0.0-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]
```

Does it need to use a the cloud manifest?

```
[2020-05-28T21:07:17.024Z] + graylog-project-cli status
[2020-05-28T21:07:17.024Z] Running in a CI environment, using repository root: .repos
[2020-05-28T21:07:17.024Z] Current project status
[2020-05-28T21:07:17.024Z]   Manifests: [manifests/master.json]
[2020-05-28T21:07:17.024Z]   Module versions
[2020-05-28T21:07:17.024Z]     graylog-parent                          3.3.1-SNAPSHOT (branch: HEAD)
[2020-05-28T21:07:17.398Z]     graylog-plugin-collector                4.0.0-SNAPSHOT (branch: master, parent: 4.0.0-SNAPSHOT)
[2020-05-28T21:07:17.398Z]     graylog-plugin-aws                      4.0.0-SNAPSHOT (branch: master, parent: 4.0.0-SNAPSHOT)
[2020-05-28T21:07:17.398Z]     graylog-plugin-threatintel              4.0.0-SNAPSHOT (branch: master, parent: 4.0.0-SNAPSHOT)
[2020-05-28T21:07:17.398Z]     graylog-plugin-enterprise-parent        4.0.0-SNAPSHOT (branch: master, parent: 4.0.0-SNAPSHOT)
[2020-05-28T21:07:17.398Z]     graylog-plugin-enterprise-integrations  4.0.0-SNAPSHOT (branch: master, parent: 4.0.0-SNAPSHOT)
[2020-05-28T21:07:17.398Z]     graylog-plugin-integrations             4.0.0-SNAPSHOT (branch: master, parent: 4.0.0-SNAPSHOT)

```

**Comment by thll** [comment]
> Does it need to use the cloud manifest?

Nope, there were just a bunch of wrong versions in the `pom.xml` files. I would expect the build to pass now.

**Comment by thll** [comment]
>I would expect the build to pass now.

@juju2112: of course the build doesn't pass 😬

IMO we need to use the *main* `3.3` manifest, not the *cloud* version:

```
 $ gp status
Current project status
  Manifests: [manifests/3.3.json]
  Module versions
    graylog-parent                          3.3.1-SNAPSHOT (branch: backport-pr-8136)
    graylog-plugin-collector                3.3.1-SNAPSHOT (branch: 3.3, parent: 3.3.1-SNAPSHOT)
    graylog-plugin-aws                      3.3.1-SNAPSHOT (branch: 3.3, parent: 3.3.1-SNAPSHOT)
    graylog-plugin-threatintel              3.3.1-SNAPSHOT (branch: 3.3, parent: 3.3.1-SNAPSHOT)
    graylog-plugin-enterprise-parent        3.3.1-SNAPSHOT (branch: 3.3, parent: 3.3.1-SNAPSHOT)
    graylog-plugin-enterprise-integrations  3.3.1-SNAPSHOT (branch: 3.3, parent: 3.3.1-SNAPSHOT)
    graylog-plugin-integrations             3.3.1-SNAPSHOT (branch: 3.3, parent: 3.3.1-SNAPSHOT)

```
@bernd, @danotorrey what do you think? Should we use the *main* 3.3. manifest or the *cloud* one?

**Comment by bernd** [comment]
> @bernd, @danotorrey what do you think? Should we use the _main_ 3.3. manifest or the _cloud_ one?

Not sure what you mean by "main" manifest. :smile:  The cloud build needs to use either `manifests/cloud/master.json` or `manifests/cloud/stable-3.3.json`. We cannot use `manifests/master.json` or `manifests/3.3.json` because those don't include the cloud plugin.

**Comment by bernd** [comment]
@thll Lol, sorry. I wasn't aware that we are in the graylog2-server repo. :joy:

**Comment by thll** [comment]
>Not sure what you mean by "main" manifest.

`manifests/3.3.json`

**Comment by thll** [comment]
> I wasn't aware that we are in the graylog2-server repo.

Yep, get's confusing now. But that's why I think `manifests/3.3.json` would be the correct one here.

**Comment by bernd** [comment]
> I think we need a `manifests/cloud-3.3.json` manifest that is using the `cloud-3.3` branch for the server. That way Jenkins automatically uses the `manifests/cloud-3.3.json` manifest for the build if the target branch for the PR is `cloud-3.3`.

Which doesn't make a difference if only the server has a `cloud-3.3` branch, of course. But once we also have a `cloud-3.3` branch in other repos, it makes a difference.

**Comment by thll** [comment]
> That way Jenkins automatically uses the manifests/cloud-3.3.json manifest for the build if the target branch for the PR is cloud-3.3

@bernd Ok I would have expected `manifests/cloud-3.3.json` being used for PRs only in the cloud repository. But either way I'm fine with it being triggered for PR's in other repos. Just thought it would be easier.

**Comment by thll** [comment]
@bernd Thanks for the clarification. I'm all for using what;s easiest for the Jenkins integration then.

**Comment by bernd** [comment]
@thll Sorry for editing your comment. That was a mistake. :disappointed:

**Comment by juju2112** [comment]
I merged Graylog2/ci-pipeline-shared#1, so this PR should build successfully after the `cloud-3.3` branch is set up in `graylog-plugin-cloud`.

**Comment by danotorrey** [comment]
> I merged [Graylog2/ci-pipeline-shared#1](https://github.com/Graylog2/ci-pipeline-shared/pull/1), so this PR should build successfully after the `cloud-3.3` branch is set up in `graylog-plugin-cloud`.

Thanks @juju2112! 

I have created the `cloud-3.3` branch in `graylog-plugin-cloud` and am running the build again...

**Comment by danotorrey** [comment]
@thll Yayy, build passed. I think you can merge this now. Once done, we can start using the `manifests/cloud/cloud-3.3.json` manifest.

**Pull request merged**
