### PR TITLE
Modify tokenizer to handle single and double quote

### PR DESCRIPTION
**Pull request by voodoodrul**
Reference: https://github.com/Graylog2/graylog2-server/issues/1359

### CODE REVIEW

**Comment by joschi** [comment]
Thanks for your contribution to Graylog. In order to continue, we need you to sign our [contributor assignment agreement](https://www.graylog.org/contributing-to-graylog/).

**Comment by voodoodrul** [comment]
Jochen,

I will sign right away. I assume I leave the Graylog section blank - to be
filled in by the recipient - and since I'm an individual, "you" and "name"
are the same printed first and last name? Or should I use a signature on
one of these?

Thanks!

- Jesse

**Comment by joschi** [comment]
CLA received. :+1:

@voodoodrul Could you please update the test cases or add new test cases in `TokenizerConverterTest` as well?

**Comment by joschi** [comment]
Thanks for adding the tests! LGTM. :+1:

**Pull request merged**
