### PR TITLE
Remove `add-module-exports` babel plugin.

### PR DESCRIPTION
**Pull request by dennisoelkers**
## Motivation and Context

This plugin was used before mainly for interop between ancient Typescript parts and core. Recently, it was only needed for tests doing `require()` calls without a `default` suffix (we should get rid of `require` in tests anyway).

This change is removing the plugin and changes test calls.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by Gaya** [comment]
@dennisoelkers is it possible that the plugins are failing on Jennkins because of this change? Other than that I can only encourage changes like this.

**Comment by dennisoelkers** [comment]
@Gaya: Yes, this PR requires the referenced plugin PR. If you want to test it, you should check out both simultaneously. The plugin PR is referencing this PR for jenkins, so its build is green.

**Comment by Gaya** [comment]
> @Gaya: Yes, this PR requires the referenced plugin PR. If you want to test it, you should check out both simultaneously. The plugin PR is referencing this PR for jenkins, so its build is green.

Hmmm, it's showing a Maven build error here. Or is this not the build we should be looking at with referenced builds?

**Review by Gaya — APPROVED** [review]
Checked and tested. Looks good!

**Pull request merged**
