### PR TITLE
remove close index button on index set overview page

### LINKED ISSUE #17570: Remove close index button on index set overview page
Remove the close option for an index. On the overview page of an specific index set. Closing an index will be deprecated in the future.
image

### PR DESCRIPTION
**Pull request by kodjo-anipah**
Removing the close index button from the index overview page. 
fixes #17570
/nocl

### CODE REVIEW

**Comment by bernd** [comment]
@kodjo-anipah Do we already have a changelog entry for this? If not, please add one. Thank you! :slightly_smiling_face:

**Comment by kodjo-anipah** [comment]
> @kodjo-anipah Do we already have changelog and UPGRADING.md entries for this? Thank you! 🙂

@bernd  oh thanks for the reminder I will add it

**Comment by kodjo-anipah** [comment]
@bernd  I added a change log to the pr. This is only a frontend changed and we usually don't add those to the UPGRADING.md, still want me to start a new section?

**Comment by bernd** [comment]
> @bernd I added a change log to the pr. This is only a frontend changed and we usually don't add those to the UPGRADING.md, still want me to start a new section?

Yeah, good point. Let's skip the UPGRADING.md until we remove the API endpoint. Can you change the changelog type to "r" (removed)?

**Review by grotlue — APPROVED** [review]
Looking good, I checked and couldn't find the close button anymore.

I realized that the E2E tests for closing and reopening an index set would fail after merging this, so I created a PR for this: https://github.com/Graylog2/e2e-tests/pull/680

**Pull request merged**
