### PR TITLE
Backend validation of search query time range limit #9487

### LINKED ISSUE #9487: Relative timerage selector and search doesn't adhere to query time range limit
## Expected Behavior

The search page should adhere to the query time range limit and shouldn't allow users to use a larger time range.

image

## Current Behavior

The configured query time range limit is not used. The selection of time ranges is not changed and the backend doesn't restrict searches to the configured range.

Peek 2020-11-14 19-12

## Related Issues

Refs #1901
Refs #3263
Refs #4787

## Steps to Reproduce (for bugs)

1. Configure a small query time range limit at "System / Configuration"
2. Go back to the search page and search for a longer time range

## Your Environment

* Graylog Version: 4.0.0-rc.2

### PR DESCRIPTION
**Pull request by todvora**
This change prevents executing queries with time range out of allowed time range limit if any is configured. It adds the backend validation and complements the already existing frontend validation of the time range.

## Description
Extended SearchExecutionGuard to check time range limit configuration and validate time range of every executed query.

## Motivation and Context
Fixes #9487

/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#2738

## How Has This Been Tested?
Added unit test. Manually verified on localhost:8080/search?q=&rangetype=relative&relative=2592000 with a very low time range limit configured.

## Screenshots (if appropriate):
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by linuspahl** [comment]
@todvora When I test this branch locally I get an error for Java test in the enterprise repo (`java: no suitable constructor found`). I rebased the master first. Can you may reproduce the error as well?

**Comment by todvora** [comment]
Let me check that!

**Comment by linuspahl** [comment]
Thanks to @todvora, I realized I had to checkout the latest version of the related enterprise branch.

**Review by dennisoelkers — APPROVED** [review]
Looks good, works fine!

**Comment by todvora** [comment]
Thx!

**Pull request merged**
