### PR TITLE
Converts the time format without adjusting to the user timezone

### PR DESCRIPTION
**Pull request by simonychuang**
Currently for a user with a timezone of UTC(-X) when using the date picker the displayed selected date is one day before the actual clicked date.

please see https://github.com/Graylog2/graylog-plugin-enterprise/pull/6095

/nocl

## How Has This Been Tested?

Tested manually on local env

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by ryan-carroll-graylog — APPROVED** [review]
Looks good and tests successfully!

**Review by danotorrey — APPROVED** [review]
LGTM and tests successfully with users in timezones that span different days.

**Comment by ryan-carroll-graylog** [comment]
@simonychuang looks like some front end tests are failing if you're not already tracking.

**Comment by simonychuang** [comment]
> @simonychuang looks like some front end tests are failing if you're not already tracking.

@ryan-carroll-graylog Yeah going to check with Linus because it looks like it was intentional to convert the date into the user timezone so just going to make sure we don't break anything by making this change

**Comment by ryan-carroll-graylog** [comment]
> > @simonychuang looks like some front end tests are failing if you're not already tracking.
> 
> @ryan-carroll-graylog Yeah going to check with Linus because it looks like it was intentional to convert the date into the user timezone so just going to make sure we don't break anything by making this change

Ah ok gotcha, good call.

**Comment by linuspahl** [comment]
I can have a detailed look, once I am back next week.

In every case we intentionally convert the date into the user timezone. Here is the related issue:
https://github.com/Graylog2/graylog2-server/issues/16096
and the related PR: https://github.com/Graylog2/graylog-plugin-enterprise/pull/5555

I can imagine the described problem will occur again with these changes.

My guess is we need to adjust the format outside of this component, before we make the request.

**Review by linuspahl — CHANGES_REQUESTED** [review]
I gave it a try and when I am testing it with a user that has e.g. the timezone Europe/Berlin, I can reproduce the bug described in https://github.com/Graylog2/graylog2-server/issues/16096

**Comment by linuspahl** [comment]
I can also see a benefit in always using the internal format (ISO 8601) for the new selected date time, provided by the date time picker `onChange` method.

We could just implement

```
const _onChange = useCallback((newDate: Date, modifiers: DayModifiers, event: React.MouseEvent<HTMLDivElement>) => (
    onChange(adjustFormat(newDate, 'internal'), modifiers, event)
  ), [onChange]);```

and pass it to the day picker. But we should still check if this causes problems in other cases where to implement the date picker.

**Review by zeeklop — APPROVED** [review]
Looks good to me. Nice work!

Tested with `Europe/Berlin` `America/Argentina/Buenos_Aires`  and `America/New_York` all 3 time zones worked as expected.

**Comment by linuspahl** [comment]
Closing this in favour of https://github.com/Graylog2/graylog2-server/pull/17677

**Pull request closed without merging**
