### PR TITLE
Fix GeoIP Processor NullPointerException Bug

### PR DESCRIPTION
**Pull request by roberto-graylog**
## Description

Reverted commit 424d3c77d0f915c94becac74565563e0dfbac234, which addressed the NullPointerException caused by null Latitude/Longitude returned by MaxMind.  Instead, updated MaxMindIpLocationResolver::doGetGeoIpData to catch Exception (rather than individual exceptions to revert behavior to exact prior behavior.  Updated MaxMindIpLocationResolverTest to conform to new behavior of MaxMindIpLocationResolver::doGetGeoIpData.

## Motivation and Context

While the pr **geoipresolver_error** addresses the NullPointerException caused by MaxMind returning a Null Latitude/Longitude pair, the end result is a `GeoLocationInformation` object with all empty/invalid fields (i.e. 0 or 'N/A').  The end result is that all these empty fields would be added to the message.  

Instead, catching `Exception` will allow any error to be logged, and an empty `GeoLocationInformation` to be thrown.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by danotorrey — CHANGES_REQUESTED** [review]
@roberto-graylog The logic in this PR looks good to me and tests successfully. 👍 

Just a couple small requests:
I think this PR should also remove the `GeoLocationInformation.create` method that was added in the previous PR. Looks like it's now no longer referenced other than in the tests. 

https://github.com/Graylog2/graylog2-server/blob/c7ecff1317dbacbcabbbcfd240a255d43119b130/graylog2-server/src/main/java/org/graylog/plugins/map/geoip/GeoLocationInformation.java#L47-L89

I also suggest using a shorter/more concise PR title. I think by default, the PR title will be used for the merge commit title, and if it's too long (more than 50 chars I think), an "..." will appear at the end of commit title at the time of merging. Perhaps a title similar to "Revise MaxMind GeoIP NullPointerException fix" would work.

**Review by ryan-carroll-graylog — APPROVED** [review]
Looks good to me. I ran some tests using IPs with location data as well as the IPs without data that were listed in the issue comments, and for IPs without location data the location fields were omitted and the IP was logged.

**Comment by danotorrey** [comment]
@roberto-graylog The code LGTM! Thanks @roberto-graylog Did you see the feedback I had about the PR title in the comment above?

**Comment by danotorrey** [comment]
Fixes https://github.com/Graylog2/graylog2-server/issues/12788

**Pull request merged**
