### PR TITLE
Update to elasticsearch 6.x compatibility

### LINKED ISSUE #4957: Update index mapping templates to support Elasticsearch 6 indices
Currently the server supports versions 2.x and 5.x via a subclass.

In order to allow upgrading Elasticsearch (and allowing write access at the same time), we need to update it to be 6.x compatible.

It is acceptable for this change to trigger deprecation warnings.

### PR DESCRIPTION
**Pull request by kroepke**
Primarily adapt index mapping template changes for 6.x backends.
Updated jest+jackson dependency for minor URL compatibility with 6.x servers.

Add elasticsearch request logger for debugging request/response layer: enable with `TRACE` on `org.graylog2.indexer.cluster.jest.RequestResponseLogger`

fixes #4957

### CODE REVIEW

**Comment by kroepke** [comment]
This also enhances the random http input to provide geolocation information for easier testing of map features.

**Comment by bernd** [comment]
@kroepke Please add the missing license headers.

**Comment by bernd** [comment]
I found this log message:

```
[2018-08-24T18:54:25,832][WARN ][o.e.d.a.a.i.t.p.PutIndexTemplateRequest] Deprecated field [template] used, replaced by [index_patterns]
```

Are we ignoring this warning for now?

**Comment by kroepke** [comment]
Yes, that deprecation warning we'll likely ignore for now because we'll fix it in 3.0 anyway.

**Pull request merged**
