### PR TITLE
Always provide the correct time range type during builder initialization

### PR DESCRIPTION
**Pull request by todvora**
Our AbsoluteRange builder needs an explicit type set in order to work properly. We can avoid that by predefining the type during the builder initialization, as we are doing in other generic types.

## Motivation and Context
```
AbsoluteRange range = AbsoluteRange.builder()
                .from(DateTime.now().minus(1000 * 60 * 50))
                .to(DateTime.now())
                .build();
```
This snippet would throw an IllegalStateException, because the type is not set. But the type is already predefined by the class itself and we can simply provide it from inside.

## How Has This Been Tested?
Added unit test

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Review by luk-kaminski — APPROVED** [review]
LGTM, thx!

**Review by dennisoelkers — APPROVED** [review]
Looks great now! Thanks! :pray:

**Review by janheise — APPROVED** [review]
LGTM!

**Review by dennisoelkers — APPROVED** [review]
Thanks a lot! :pray:

**Pull request merged**
