### PR TITLE
Load cloud plugin and display ForwarderReceivedBy

### PR DESCRIPTION
**Pull request by ousmaneo**
These change load check function and Received by component from cloud plugin
It will then check if the message Node is a local node, If not it will display the Received By section using the loaded component.

/jenkins-pr-deps Graylog2/graylog-plugin-cloud#611

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by Gaya — APPROVED** [review]
LGTM 👏

**Comment by edmundoa** [comment]
The build has a failing test, not sure if it's related to the changes here:
`09:45:16  [INFO] FAIL src/components/users/UsersOverview/UsersOverview.test.jsx`

**Comment by ousmaneo** [comment]
@edmundoa I don't think this is related to my changes. Also, all tests are passing on my local. 
I will restart the build to see

**Comment by Gaya** [comment]
@ousmaneo @edmundoa I've had this error happen at random too. And also one in another component. Maybe we can ask if others are experiencing the same issues. Looks more like a memory / timeout thing.

**Pull request merged**
