### PR TITLE
update LOAD_BALANCERS in DocsHelper

### PR DESCRIPTION
**Pull request by omercnet**
in 2.1 this page moved to configuration/load_balancers.html

### CODE REVIEW

**Comment by joschi** [comment]
@omercnet Please rebase your branch on the current `master` branch of the `graylog2-server` repository.

**Comment by omercnet** [comment]
@joschi commit was moved to `master` but I can't seem to be able to edit the PR to merge from my master
should I open a new PR ?

**Comment by joschi** [comment]
@omercnet You should be able to rebase your `patch-1` branch on `origin/master` and then force push that branch to GitHub. The PR will then automatically refresh.

See http://stackoverflow.com/a/17182696/49505 for an example.

**Comment by omercnet** [comment]
@joschi done

**Pull request merged**
