### PR TITLE
Shorten widget titles with ellipsis when overflowing available space.

### PR DESCRIPTION
**Pull request by dennisoelkers**
## Motivation and Context

Prior to this change, a widget's title was always shown in full, even when there was not enough space, leading to unwanted line breaks and even taking over space of the actual visualization.

This change is now implementing shortening of the widget's title and adding an ellipsis when the available space is exceeded.

## Screenshots (if appropriate):

Before:

image

After:

image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by linuspahl — COMMENTED** [review]
With a small widget and / or monitor size, the title can disappear:

image
Unfortunately I do not have a good solution for this in mind. It would be great if the title has a `min-width` and we display the actions in a new line, when the widget is too small.

I also noticed we are displaying the message "Double click the title to edit it." when hovering over the title. We should also display the full title here, otherwise the full title can not be displayed easily.

**Comment by dennisoelkers** [comment]
I would say for a small widget it's okay if the title disappears. Showing the actions in a new line would cost too much space from the visualization, especially for small widgets/resolutions. As long as we show the full title on hover, the user is still able to see the title on demand.

**Comment by linuspahl** [comment]
Alright, in this case let's define a min width of e.g. `20px` for the title, to ensure it will never be completely hidden, like in this case: 

image

Compared with the previous widget header it is now possible that we hide widget actions, when a widget is very small. But IMO this is an edge case.
image

**Review by linuspahl — APPROVED** [review]
Looks good to me!

**Pull request merged**
