### PR TITLE
Replay support for Enterprise event Search Filters

### PR DESCRIPTION
**Pull request by danotorrey**
`graylog2-server` changes needed for https://github.com/Graylog2/graylog-plugin-enterprise/pull/6475

/nocl

### CODE REVIEW

**Review by kingzacko1 — APPROVED** [review]
LGTM!

**Review by zeeklop — APPROVED** [review]
Tested successfully.

**Review by kingzacko1 — APPROVED** [review]
Front end event replay changes look good too! Awesome job y'all!

**Comment by danotorrey** [comment]
@zeeklop Would you be able to take a look at the merge conflict?

**Pull request merged**
