### PR TITLE
Provide a different default db for maxmind in cloud

### PR DESCRIPTION
**Pull request by mpfz0r**

### CODE REVIEW

**Comment by mpfz0r** [comment]
@ousmaneo @grotlue do you still need this? or did this get solved already in a different PR?

**Comment by ousmaneo** [comment]
Hi @mpfz0r, yes, we still need this. We will take of it.

**Comment by ousmaneo** [comment]
Hi @mpfz0r, We still need this PR to go into the master. A cherry-pick of the commit has been done for the backport. Once it's in I can take care of the backport PR, thank you.

**Comment by mpfz0r** [comment]
Duplicate of #14061

**Pull request closed without merging**
