### PR TITLE
(Backport 5.0) Prevent changing unmodifiable Event Definition condition types

### PR DESCRIPTION
**Pull request by ryan-carroll-graylog**
5.0 Backport for https://github.com/Graylog2/graylog2-server/pull/14110

/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/4554

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ryan-carroll-graylog** [comment]
@zeeklop @kingzacko1 I had to manually massage `EventConditionForm` because of we were still using the `.jsx` version and some other changes that weren't backported. I'm pretty sure I got everything and it works in testing, but some extra scrutiny on that wouldn't hurt.

Also, do you know what the linter errors are about? The reviewbot doesn't really give me any info and my Intellij linter isn't showing any issues.

**Comment by kingzacko1** [comment]
Were there more changes made to the EventConditionForm that would prevent us from just pulling it over as it is now in master? If so we should be able to make this work. Looks like it's just complaining about import order. If you have your IntelliJ configured properly it should resolve that automatically when you save a frontend file you are working on. @ryan-carroll-graylog

**Review by zeeklop — APPROVED** [review]
Looks good to me. Nice work with the type definition in the front end

**Comment by ryan-carroll-graylog** [comment]
> Were there more changes made to the EventConditionForm that would prevent us from just pulling it over as it is now in master? If so we should be able to make this work. Looks like it's just complaining about import order. If you have your IntelliJ configured properly it should resolve that automatically when you save a frontend file you are working on. @ryan-carroll-graylog

@kingzacko1 Yeah unfortunately there were some significant changes made to add System Event Definitions in 5.1+ in this area of the app. Those changes were made mid work on the master PR so I was able to cherry-pick Zeek's and your front-end commits without issue, and then apply Linus's suggestions so I think I have everything that applies to our work.

I must not have m IntelliJ configured properly for front end then. I moved around the imports to match what's in master so hopefully that fixes it, but I may have to get with y'all to setup IntelliJ correctly.

**Comment by ryan-carroll-graylog** [comment]
> > Were there more changes made to the EventConditionForm that would prevent us from just pulling it over as it is now in master? If so we should be able to make this work. Looks like it's just complaining about import order. If you have your IntelliJ configured properly it should resolve that automatically when you save a frontend file you are working on. @ryan-carroll-graylog
> 
> @kingzacko1 Yeah unfortunately there were some significant changes made to add System Event Definitions in 5.1+ in this area of the app. Those changes were made mid work on the master PR so I was able to cherry-pick Zeek's and your front-end commits without issue, and then apply Linus's suggestions so I think I have everything that applies to our work.
> 
> I must not have m IntelliJ configured properly for front end then. I moved around the imports to match what's in master so hopefully that fixes it, but I may have to get with y'all to setup IntelliJ correctly.

I think I figured out the IntelliJ linter issue, I had the ESlint plugin installed but not enabled...

**Comment by kingzacko1** [comment]
Sigma event definitions types cannot be changed, but I am hitting an error when trying to create an Aggregation event definition. Are you able to do this successfully? @ryan-carroll-graylog   
image

**Comment by ryan-carroll-graylog** [comment]
> Sigma event definitions types cannot be changed, but I am hitting an error when trying to create an Aggregation event definition. Are you able to do this successfully? @ryan-carroll-graylog image

@kingzacko1 Just re-tried creating and editing Aggregation and Correlation event definitions I'm not seeing any errors. @danotorrey @zeeklop did/are y'all seeing any errors here?

**Comment by ryan-carroll-graylog** [comment]
> > Sigma event definitions types cannot be changed, but I am hitting an error when trying to create an Aggregation event definition. Are you able to do this successfully? @ryan-carroll-graylog image
> 
> @kingzacko1 Just re-tried creating and editing Aggregation and Correlation event definitions I'm not seeing any errors. @danotorrey @zeeklop did/are y'all seeing any errors here?

Ah just refreshed everything and am seeing the error now @kingzacko1, looking into it.

**Comment by kingzacko1** [comment]
Okay good deal. I blew away my environment and was still seeing it when starting up fresh. Haven't tracked down the issue yet though.

**Comment by danotorrey** [comment]
I am pulling the latest code and testing now. I'll let you know how it goes.

**Comment by ryan-carroll-graylog** [comment]
It looks like was missing `entityTypes` in `EventConditionForm.tsx` which was needed by `FilterAggregationForm.jsx`. Just pushed an update, and all appears to be working. Thanks for catching that @kingzacko1 .

**Review by danotorrey — APPROVED** [review]
LGTM and tests successfully on 5.0

**Review by kingzacko1 — APPROVED** [review]
Latest changes look good and test successfully :+1:

**Pull request merged**
