### PR TITLE
Add OSHI as system stats reporter

### PR DESCRIPTION
**Pull request by desiderantes**
This commit adds a new Operating System and Hardware Information library, OSHI, that does not require the cumbersome packaging that Sigar currently needs. This library has a very active community and a pretty good set of platform options. 

## Description
A new config option, enable_oshi, is added, defaults to false.
Implementations for FS, network, OS, and process probes.

## Motivation and Context
Sigar is pretty much unmaintained, and a replacement with a friendly license would be a nice addition.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by dennisoelkers** [comment]
Hey @desiderantes, thanks for your contribution, very much appreciated! I think having something which does not require sigar's packaging would be nice, but just for completeness: things have changed license-wise, as sigar [switched to MIT in 2019](https://github.com/oshi/oshi/issues/593).

On another note:
  - Are there any shortcomings that OSHI has in contrast to our current use of sigar?
  - Why would we keep both implementations and make it configurable? Shouldn't it be transparent for the user so we can just replace the implementation?

**Comment by desiderantes** [comment]
Hi @dennisoelkers, to answer your questions: There is some data that Oshi does not report, mostly the TCP stats and some FS stats. That's also why I did not just replace Sigar, since I am not sure how relevant the missing data is.

**Comment by dbwiddis** [comment]
Not sure if this issue is still pending, but I just stumbled on it.  I'll be [adding TCP stats to OSHI soon](https://github.com/oshi/oshi/issues/1173).  I think we may already have the FS stats you use, just in a different place than you're looking.

**Comment by desiderantes** [comment]
@dbwiddis That's awesome! I'll update this PR when that gets merged. About the FS stats, I'll need to take a better look at the docs, thanks!

**Comment by dbwiddis** [comment]
You might need a _little_ help navigating the docs. :)

A lot of the read/write stats aren't applicable at the (software) FS level so they are on the (hardware) `HWDiskStore` object. You can use the mount points to map them to each other if needed.   If there are others missing let me know and I'll see if it's possible to add them.

**Comment by dbwiddis** [comment]
OK, TCP stats merged into OSHI's master branch and available in the latest SNAPSHOT. I'll probably push a 4.7.0 release sooner rather than later but want to give you the chance to test it first.  The TCPv4 stats should match what you were already getting from sigar, the v6 and UDP stuff is extra. :)

**Comment by desiderantes** [comment]
@dennisoelkers I updated this PR since you last saw it, the new changes are:

- It removes SIGAR completely
- Included OSHI TCP stats
- Reworked FS stats to make it faster
- Updated to latest OSHI

**Comment by mpfz0r** [comment]
Closing this in favour of #9840 
Thank you very much @desiderantes \o/

**Pull request closed without merging**
