### PR TITLE
Update css-loader, less-loader, style-loader dependencies and configuration

### PR DESCRIPTION
**Pull request by Gaya**
Dependency updates to css-loader, less-loader, and style-loader to support new versions and APIs.

## Description

Updates loaders to latest dependencies and changes the configuration needed in webpack's config. 

Updates method of importing lazy css instead of `style/useable` as per described here: https://github.com/webpack-contrib/style-loader#lazystyletag

Removes icon font from Bootstrap config giving trouble.

Replaced `insertAt` config to match new API.

**__This Requires plugins to also follow the new method of importing lazy CSS__**

- [ ] Collector: https://github.com/Graylog2/graylog-plugin-collector/pull/159
- [ ] Enterprise: https://github.com/Graylog2/graylog-plugin-enterprise/pull/1745

## Motivation and Context

The loaders were at old versions and needed to be updated.

## How Has This Been Tested?

- If building the project through `graylog-project yarn build` still works (also includes changes to plugin lazy importing)
- Tested by going to the pages where the components live and see if they don't break.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Refactoring (non-breaking change)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

/jenkins-pr-deps Graylog2/graylog-plugin-collector#159,Graylog2/graylog-plugin-enterprise#1745

### CODE REVIEW

**Comment by Gaya** [comment]
Couple of things still failing. Seems like the tests are not working with the lazy loading at the moment. I'll take a look at what's going on later.

**Comment by Gaya** [comment]
@dennisoelkers @kyleknighted I got it working, however it will fail on the plugins that still use the current way of lazy loading. There was a trick to include the other two PRs, right?

**Comment by Gaya** [comment]
@dennisoelkers @kyleknighted this PR seems to be in order now. We'd need to merge the two other PRs of the plugins too once we merge this one.

**Review by dennisoelkers — APPROVED** [review]
Looks good, works fine, great work! :tada:

**Pull request merged**
