### PR TITLE
Fix remove link placement on tag-remove elements

### PR DESCRIPTION
**Pull request by edmundoa**
Just a small fix of something I saw in the new filter used in the collector plugin.

### CODE REVIEW

**Comment by mariussturm** [comment]
Works on all browsers but Chrome stable 59 (Version 59.0.3071.86 (Official Build) (64-bit)).
The 'X' is a little bit over the middle line of the text.

**Comment by edmundoa** [comment]
As the change looks good in Chrome Canary, we are waiting a bit to see if the next Chrome version is not showing that issue. Otherwise we will work the PR a bit and try to fix the placement on all browsers.

**Comment by bernd** [comment]
@edmundoa @mariussturm Any progress on this?

**Comment by bernd** [comment]
@edmundoa @mariussturm ping

**Comment by edmundoa** [comment]
@bernd @mariussturm this is looking good for me in Chrome 61.0.3163.91, so I think we can look into it again.

**Comment by bernd** [comment]
@edmundoa Thank you!

**Comment by edmundoa** [comment]
@mariussturm I think the latest code should fix the issue you were still seeing in Chrome for Linux. Please take a look and let me know if it still looks odd!

**Pull request merged**
