### PR TITLE
Fix flickering of theme

### PR DESCRIPTION
**Pull request by kmerz**
## Motivation
Prior to this change, when opening a popover, the opened popover would
flicker white then back to dark when in dark mode.

## Description
This change will do not set a default state for the mode. Which will
prevent the flickering.

### CODE REVIEW

**Review by dennisoelkers — CHANGES_REQUESTED** [review]
Wouldn't it be better to keep the implicit `undefined` for the theme state? This would allow us to express explicitly on a typing level that the theme might not be set.

**Comment by kyleknighted** [comment]
@dennisoelkers I like `undefined` as well before the render, but not a fan of the typings allowing `undefined` because I felt like an undefined mode in the theme should cause an error as well. What do you propose as a good solution? Is the type allowing an `undefined` the best way?

**Comment by dennisoelkers** [comment]
@kyleknighted: IMO we should keep a strict, non-optional typing in `ThemeProvider`, but for the `GraylogThemeProvider` we already kind of have a non-defined initial state, we just make it implicit by using `''`. Instead we should allow `mode` to be `undefined` and deal with that case  in the related places.

**Comment by kmerz** [comment]
This is fixed by another PR.

**Pull request closed without merging**
