### PR TITLE
Query duration stats collection. Simple endpoint to retrieve timerange-based histogram.

### PR DESCRIPTION
**Pull request by luk-kaminski**
Query duration stats collection. Simple endpoint to retrieve timerange-based histogram.

## Description
Alpha PR that should allow to make some first steps in the area of this task: #16164.
The general concept is:
1. Store in-memory execution stats of recent queries (to be decided what `recent` means, currently it is certain number of most recent queries, configurable with `query_latency_monitoring_window_size`).
2. Provide an REST endpoint that would create period-based histogram-like data about those current stats.

This should allow FE to draw a diagram representing current state of the system, smth like that:
image

This could also be a groundwork for more complex monitoring visualisations.

At current stage, we are fine with BE-only code, that provides the data, without visualizing them:
image

/jpd Graylog2/graylog-plugin-enterprise#6307
/nocl

## Motivation and Context
General motivation is described here : #16164

## How Has This Been Tested?
Manually and with unit tests.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by todvora — CHANGES_REQUESTED** [review]
I can't approve this PR. To me, the https://github.com/Graylog2/graylog2-server/issues/16164 is about creating a simple and predefined histogram. But this PR created a framework for creating generic histograms. This brings extreme complexity that's not needed to fulfill the feature request. 

I'd simplify it to absolute minimum - iterate over the `Collection<QueryExecutionStats>`, group by time-range and compute a few metrics. Deliver as Map or list of records. 

Currently, we don't need any complexity and flexibility. But we'll have to maintain it.

I'd like to ask @janheise and @dennisoelkers to decide how to continue with this PR. My very naive and simple solution for the task would probably look like this: https://gist.github.com/todvora/0cb519456e1afb2e1ddfcf3be4fe8302

**Comment by luk-kaminski** [comment]
> I can't approve this PR. To me, the #16164 is about creating a simple and predefined histogram. But this PR created a framework for creating generic histograms. This brings extreme complexity that's not needed to fulfill the feature request.
> 
> I'd simplify it to absolute minimum - iterate over the `Collection<QueryExecutionStats>`, group by time-range and compute a few metrics. Deliver as Map or list of records.
> 
> Currently, we don't need any complexity and flexibility. But we'll have to maintain it.
> 
> I'd like to ask @janheise and @dennisoelkers to decide how to continue with this PR. My very naive and simple solution for the task would probably look like this: https://gist.github.com/todvora/0cb519456e1afb2e1ddfcf3be4fe8302

@dennisoelkers @janheise - Yes, it is true, we need a neutral judge on this one.
My point of view is that #16164 is still a fuzzy task and just a step in a proper direction. Many aspects of histograms may be changed. I wanted to have a general code, which tries to follow some SOLID principles. I am against hardcoding everything in single class, as Tomas suggests.

**Comment by dennisoelkers** [comment]
@luk-kaminski, @todvora: I am still trying to understand the implications. What is the reason we are not using Dropwizard's [Metrics](https://metrics.dropwizard.io/4.2.0/) library to aggregate the data as we do in other parts of the product?

**Comment by luk-kaminski** [comment]
> @luk-kaminski, @todvora: I am still trying to understand the implications. What is the reason we are not using Dropwizard's [Metrics](https://metrics.dropwizard.io/4.2.0/) library to aggregate the data as we do in other parts of the product?

I am not sure if it is enough even at this point.
We need histogram of one type of values (related to duration) bucketed or binned based on completely different feature (period). That's smth com.codahale.metrics.Histogram does not seem to support.

**Comment by todvora** [comment]
Agree with @luk-kaminski, dropwizard doesn't seem to offer functionality beyond simple histograms. It would be nice to use something existing and already used in graylog. But for this feature request, we need a bit more.

**Review by todvora — APPROVED** [review]
I think it's a bit overengineered but won't block the change. Feel free to merge anytime. Thanks!

**Pull request merged**
