### PR TITLE
Dependency updates

### PR DESCRIPTION
**Pull request by joschi**
* https://www.elastic.co/guide/en/elasticsearch/reference/2.4/release-notes-2.4.4.html
* https://github.com/google/guava/wiki/Release21
* https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.8.6
* https://github.com/rabbitmq/rabbitmq-java-client/releases/tag/v4.0.2
* https://github.com/rabbitmq/rabbitmq-java-client/releases/tag/v4.0.1

Test dependencies:
* https://joel-costigliola.github.io/assertj/assertj-core-news.html#assertj-core-3.6.2
* http://jqno.nl/equalsverifier/changelog/#version-22
* https://github.com/ArcBees/Jukito/releases/tag/jukito-parent-1.5

### CODE REVIEW

**Comment by kroepke** [comment]
I would greatly appreciate links to the corresponding changelogs.
In the light of the recent problem we had with the grizzly changes I'd like to be more careful about updating dependencies but it is very difficult to review when you have to hunt for individual projects' changelogs.

**Comment by kroepke** [comment]
Of course this applies mostly to the dependencies we ship, the ones in test scope are much less critical and don't necessarily need changelogs here.

**Comment by joschi** [comment]
@kroepke I've added the changelogs of the updated dependencies.

**Comment by kroepke** [comment]
thx!

**Pull request merged**
