### PR TITLE
Improve system error notification message for failed CustomHTTPNotifions

### PR DESCRIPTION
**Pull request by kingzacko1**
## Description

During debugging another issue realized that the error message in System Notifications posted for failed Custom HTTP Notifications is not particularly helpful. This change adds the error response body if the server sends one and reverts to the URL as before if not.

/nocl small error message improvement
## Motivation and Context

improve error messages so they can more easily be used to address underlying issue causing the error

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by danotorrey — COMMENTED** [review]
@kingzacko1 This LGTM and tests successfully for improving the error message when the host can be resolved and a socket opened. But, when the host cannot be resolved of the host does not respond, it falls in to the `catch` on line 174. While we are looking at this code, should we log a system notification there too?

**Review by ryan-carroll-graylog — COMMENTED** [review]
LGTM other than Dan's comment.

**Review by ryan-carroll-graylog — APPROVED** [review]
Looks good and tests successfully with the latest

**Review by danotorrey — APPROVED** [review]
Thanks for the update @kingzacko1!

**Pull request merged**
