### PR TITLE
Disallow exporting non-exportable Event Definitions in Content Packs

### PR DESCRIPTION
**Pull request by ryan-carroll-graylog**
Enables controlling what Event Definition config types are able to be exported to a Content Pack.
Sigma Event Definition config specific changes are in: https://github.com/Graylog2/graylog-plugin-enterprise/pull/4304

## Description

With the introduction of Sigma Rule Event Definitions, there are some there are some types of Event Definitions that should not be able to be exported to Content Packs. This change creates an `isContentPackExportable()` function in the  `EventProcessorConfig` interface, which defaults to true but allows sub-classes to override to false. This is then checked in the `EventDefinitionFacade` when providing the list of exportable Event Definitions to the User.

## Motivation and Context

Sigma Rule Event Definitions are not meant to be exportable to Content Packs as exporting Rules will be done using the Sigma Rule Entities themselves, and exporting a Content Pack with Sigma Rule Event Definitions causes the export to fail.

Addresses: https://github.com/Graylog2/graylog-plugin-enterprise/issues/4292

## How Has This Been Tested?

Locally with development environment and unit testing.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ryan-carroll-graylog** [comment]
@danotorrey @kingzacko1 let me know what you think of this solution to the issue.

I also considered simply checking for the `sigma-v1` config type in `EventDefinitionFacade::listEntityExcerpts` e.g.:
```
    public Set<EntityExcerpt> listEntityExcerpts() {
        return eventDefinitionService.streamAll()
                .filter(ed -> ed.config().type().equals("sigma-v1")
                .map(this::createExcerpt)
                .collect(Collectors.toSet());
    }
```
But it would require checking for a hard coded String since the `SigmaEventProcessorConfig` class can't be referenced directly from `graylog2-server`, which seemed fragile and would introduce Sigma specific code to the repo.

Let me know if you think the current approach is too heavy handed or you have ideas for a better way to filter out the Sigma Event Definitions.

**Review by kingzacko1 — APPROVED** [review]
I agree we'd rather not include the actual event type name in the filtering here. I think this approach makes sense for what we want to accomplish, seems minimally intrusive, looks good, and tests successfully.

**Comment by danotorrey** [comment]
Thanks for this @ryan-carroll-graylog! I'll review after lunch.

**Review by danotorrey — APPROVED** [review]
Nice solution! Thanks @ryan-carroll-graylog!

**Pull request merged**
