### PR TITLE
Simplifying jsRoutes a bit.

### PR DESCRIPTION
**Pull request by dennisoelkers**
* Removing unneeded keys
* Fixing linter hints
* Rename jsRoutes to ApiRoutes

### CODE REVIEW

**Comment by garybot2** [comment]
Looks like we would not be able to merge this PR because of merge conflicts. Please rebase, fix conflicts, and force push to your branch.

**Comment by bernd** [comment]
Please do not forget to check all UI plugins that might use the jsRoutes object.

**Comment by edmundoa** [comment]
Never forget! :+1:

**Comment by edmundoa** [comment]
LGTM!

**Pull request merged**
