### PR TITLE
Always serialize joda Durations as milliseconds

### PR DESCRIPTION
**Pull request by mpfz0r**
Add a  Joda DurationSerializer that ignores the `SerializationFeature.WRITE_DURATIONS_AS_TIMESTAMPS` setting and always serializes `org.joda.time.Duration` to milliseconds. This became necessary with the Jackson 2.13 update, which forced us to disable `WRITE_DURATIONS_AS_TIMESTAMPS` to have `java.time.Duration` objects serialized as strings.

#Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/4320

/nocl

### CODE REVIEW

**Comment by patrickmann** [comment]
Looks good and fixes the problem.
Looking around for other instances of `joda.time.Duration` that end up in the DB I found these:
- `@JsonProperty(FIELD_CREATION_DURATION)`
These are also serialized to milliseconds.

**Comment by bernd** [comment]
@mpfz0r @patrickmann Thanks for the fix! Good work! :pray: 

Can you elaborate on how this worked before the Jackson update? Did we deliberately serialize joda-time and java.time durations differently in the old version, or was that by accident?

**Comment by mpfz0r** [comment]
> Can you elaborate on how this worked before the Jackson update?

The jackson update changed the default for `java.time.Duration`. We had to disable `WRITE_DURATIONS_AS_TIMESTAMPS` to make it backwards compatibile. 
joda Durations always serialized into milliseconds, so disabling `WRITE_DURATIONS_AS_TIMESTAMPS` changed the behaviour for them.

We couldn't have both at the same time anymore.

We could've done it the other way around, and writing a custom serializer for java time Durations instead.
Or change all our code to move away from joda Durations, but that's more involved, and probably not a good idea in this phase of the release.

**Comment by bernd** [comment]
> > Can you elaborate on how this worked before the Jackson update?
> 
> The jackson update changed the default for `java.time.Duration`. We had to disable `WRITE_DURATIONS_AS_TIMESTAMPS` to make it backwards compatibile. joda Durations always serialized into milliseconds, so disabling `WRITE_DURATIONS_AS_TIMESTAMPS` changed the behaviour for them.
> 

Got it. Thank you! :pray:

**Review by patrickmann — APPROVED** [review]

**Review by bernd — APPROVED** [review]
LGTM. Tested in my test environment. The licenses page works and also the field refresh interval on the indices page.

**Comment by patrickmann** [comment]
> Can you elaborate on how this worked before the Jackson update?

In Jackson 2.9
- the [Java Duration deserializer](https://github.com/kezhuw/jackson-modules-java8/blob/b8ccc50a245825621fd455850b2125cb9d8f4f87/datetime/src/main/java/com/fasterxml/jackson/datatype/jsr310/ser/DurationSerializer.java) honors `WRITE_DATES_AS_TIMESTAMPS` and ignores `WRITE_DURATIONS_AS_TIMESTAMPS`
- Joda Duration deserializer [honors](https://github.com/FasterXML/jackson-datatype-joda/blob/31a02d03967b97f0f81ba809ca680eda2f66a42c/src/main/java/com/fasterxml/jackson/datatype/joda/ser/DurationSerializer.java#L36) `WRITE_DURATIONS_AS_TIMESTAMPS`

Since the default setting for WRITE_DURATIONS_AS_TIMESTAMPS is enabled and GL 4.3 explicitly disables `WRITE_DATES_AS_TIMESTAMPS` we end up deserializing Java Durations to string and Joda Durations to milliseconds.

In Jackson 2.13 Java Duration deserializer has been corrected to use WRITE_DURATIONS_AS_TIMESTAMPS. When this serialization feature was disabled in GL 5.0 to be compatible with serialization of Java Durations in GL 4.3 we broke compatibility with previously serialized values of Joda Duration.

**Comment by bernd** [comment]
@patrickmann Awesome, thanks for the detailed explanation! :pray:

**Pull request merged**
